/** Settings navigation in the persistent sidebar and route-owned page content. */
import * as stylex from "@stylexjs/stylex";
import { control, settings } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const appearanceSettingsStyles = stylex.create({
  navigation: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    padding: "9px 8px 12px",
  },
  back: {
    display: "inline-flex",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 7,
    height: control.regularHeight,
    marginBottom: 12,
    paddingInline: 8,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    cursor: "pointer",
  },
  search: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    height: 30,
    marginBottom: 14,
    paddingInline: 10,
    borderRadius: t.radiusLg,
    borderStyle: "none",
    backgroundColor: t.fillSecondary,
    boxShadow: {
      default: `inset 0 0 0 1px ${t.borderWeak}`,
      ":focus-within": `inset 0 0 0 1px ${t.borderDefault}`,
    },
    color: t.iconTertiary,
  },
  searchIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  searchInput: {
    minWidth: 0,
    flex: 1,
    padding: 0,
    borderStyle: "none",
    outlineStyle: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    "::placeholder": { color: t.textTertiary },
  },
  navList: { display: "flex", flexDirection: "column", gap: 1 },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    width: "100%",
    height: control.regularHeight,
    paddingInline: 7,
    borderRadius: t.radiusBase,
    borderStyle: "none",
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textSecondary,
    fontSize: t.fontBase,
    fontWeight: 400,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    cursor: "pointer",
    textDecoration: "none",
  },
  navItemActive: { backgroundColor: t.fillGhostSelected, color: t.textPrimary },
  emptyNavigation: {
    padding: "6px 8px",
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  content: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    backgroundColor: t.bgBase,
  },
  contentInner: {
    display: "flex",
    flexDirection: "column",
    containerType: "inline-size",
    gap: settings.sectionGap,
    width: `min(${settings.contentWidth}, calc(100% - 2 * ${settings.contentGutter}))`,
    minHeight: "100%",
    marginInline: "auto",
    paddingBlock: "48px 80px",
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    minHeight: 22,
    paddingInline: 8,
  },
  panel: { display: "flex", flexDirection: "column", gap: settings.sectionGap },
});
