/** Controls unique to Settings › Appearance. */
import * as stylex from "@stylexjs/stylex";
import { settings } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const appearancePanelStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", gap: settings.sectionGap },
  tintControl: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    width: 150,
  },
  tintSlider: { width: 120, minWidth: 0, flex: "0 1 auto" },
  sliderControl: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: 16,
    cursor: "pointer",
    touchAction: "none",
    userSelect: "none",
  },
  sliderTrack: {
    position: "relative",
    width: "100%",
    height: 6,
    borderRadius: t.radiusXs,
    backgroundColor: t.strokeTertiary,
    userSelect: "none",
  },
  sliderThumb: {
    boxSizing: "border-box",
    width: 14,
    height: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokePrimary,
    borderRadius: t.radiusFull,
    outlineStyle: { default: "none", ":focus-within": "solid" },
    outlineWidth: 2,
    outlineColor: t.strokeFocused,
    outlineOffset: 2,
    userSelect: "none",
  },
  tintThumb: {
    backgroundColor: "hsl(var(--nyte-tint-hue) var(--nyte-tint-intensity) 50%)",
  },
  tintSlot: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    // Wide enough for "100%"; the hue swatch centers in the same slot.
    width: 26,
    flexShrink: 0,
  },
  tintSwatch: {
    display: "block",
    width: 20,
    height: 20,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeTertiary,
    borderRadius: t.radiusFull,
    backgroundColor: t.strokeTertiary,
  },
  tintSwatchActive: {
    backgroundColor: "hsl(var(--nyte-tint-hue) var(--nyte-tint-intensity) 50%)",
  },
  tintValue: {
    color: t.textSecondary,
    fontSize: t.fontXs,
    fontVariantNumeric: "tabular-nums",
    lineHeight: t.leadingSm,
    textAlign: "center",
  },
  density: {
    display: "flex",
    flexDirection: "column",
    width: {
      default: 150,
      "@media (max-width: 500px)": "100%",
      "@container (max-width: 500px)": "100%",
    },
    minWidth: 0,
    maxWidth: "100%",
    boxSizing: "border-box",
  },
  densitySlider: {
    width: "100%",
    paddingBlock: 8,
  },
  densityDetent: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 3,
    height: 3,
    borderRadius: t.radiusFull,
    backgroundColor: t.textQuaternary,
    opacity: 0.5,
    pointerEvents: "none",
    transform: "translate(-50%, -50%)",
  },
  densityThumb: {
    backgroundColor: t.textPrimary,
  },
  densityLabels: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: 4,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  codeFontPreview: {
    overflow: "hidden",
    borderRadius: t.radiusSm,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: "20px",
  },
  diffLine: {
    display: "grid",
    gridTemplateColumns: "32px minmax(0, 1fr)",
    minHeight: 20,
    paddingInlineEnd: 8,
    whiteSpace: "pre",
  },
  diffRemovedLine: {
    borderInlineStart: `3px solid ${t.removed}`,
    backgroundColor: t.diffRemovedLineBg,
  },
  diffAddedLine: {
    borderInlineStart: `3px solid ${t.added}`,
    backgroundColor: t.diffAddedLineBg,
  },
  codePreviewText: {
    display: "block",
    minWidth: 0,
    overflow: "hidden",
    fontFamily: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "pre",
  },
  diffRemovedNumber: { color: t.removed, textAlign: "center" },
  diffAddedNumber: { color: t.textSuccess, textAlign: "center" },
  codeKeyword: { color: t.textDanger },
  codeIdentifier: { color: t.textAccent },
});
