/** Customize inventory feature styles. */
import * as stylex from "@stylexjs/stylex";
import { t } from "../theme/vars.stylex.ts";

export const customizeStyles = stylex.create({
  surface: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    backgroundColor: t.bgBase,
  },
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: 720,
    minHeight: "100%",
    marginInline: "auto",
    padding: "16px 24px 40px",
    gap: 12,
  },
  searchRow: { display: "flex", alignItems: "center", gap: 8 },
  searchField: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    height: 32,
    paddingInline: 10,
    borderRadius: t.radiusLg,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: t.strokeSecondary, ":focus-within": t.strokeFocused },
    backgroundColor: t.fillSecondary,
    color: t.iconTertiary,
    outlineStyle: { default: "none", ":focus-within": "solid" },
    outlineWidth: 2,
    outlineColor: t.focusRing,
    outlineOffset: -2,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    height: "100%",
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontFamily: t.fontSans,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    outlineStyle: "none",
    "::placeholder": { color: t.textTertiary },
  },
  tabs: { display: "flex", alignItems: "center", gap: 4, paddingBlock: 2 },
  tab: {
    display: "inline-flex",
    alignItems: "center",
    height: 28,
    paddingInline: 10,
    borderRadius: t.radiusFull,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textSecondary,
    fontFamily: t.fontSans,
    fontSize: t.fontSm,
    fontWeight: 500,
    lineHeight: t.leadingSm,
    cursor: "pointer",
  },
  tabActive: {
    borderColor: t.accent,
    backgroundColor: { default: t.accent, ":hover": t.accent },
    color: t.textOnColor,
  },
  inventory: { display: "flex", flexDirection: "column", gap: 8, minWidth: 0 },
  inventoryHeading: { display: "flex", alignItems: "baseline", gap: 6, paddingInline: 6 },
  inventoryTitle: {
    margin: 0,
    color: t.textPrimary,
    fontSize: t.fontBase,
    fontWeight: 600,
    lineHeight: t.leadingBase,
  },
  inventoryCount: { color: t.textTertiary, fontSize: t.fontSm, lineHeight: t.leadingSm },
  settingsNote: {
    paddingInline: 6,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    padding: 1,
    overflow: "hidden",
    borderRadius: t.radiusXl,
    backgroundColor: t.strokeTertiary,
  },
  row: {
    "--nyte-row-height": "48px",
    "--nyte-row-gap": "10px",
    "--nyte-row-padding-inline": "10px",
    "--nyte-row-leading-size": "16px",
    // The list paints its hairlines as 1px gaps in its own background, so every
    // row needs an opaque resting fill and square corners to cover them.
    "--_row-fill": t.bgSubtle,
    paddingBlock: 6,
    borderRadius: 0,
  },
  rowTitle: { fontWeight: 500 },
  badge: {
    flexShrink: 0,
    padding: "2px 6px",
    borderRadius: t.radiusFull,
    backgroundColor: t.fillSecondary,
    color: t.textTertiary,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
  },
  failedBadge: { backgroundColor: t.fillDangerSubtle, color: t.textDanger },
  quiet: {
    minHeight: 48,
    display: "flex",
    alignItems: "center",
    paddingInline: 10,
    backgroundColor: t.bgSubtle,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  loadingLine: {
    width: "42%",
    height: 8,
    borderRadius: t.radiusFull,
    backgroundColor: t.fillSecondary,
  },
  error: { color: t.textDanger, fontSize: t.fontSm, lineHeight: t.leadingSm },
});
