/** Customize inventory feature styles. */
import * as stylex from "@stylexjs/stylex";
import { control } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const customizeStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", gap: 26, paddingBlock: 18 },
  noSession: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 240,
    gap: 5,
    padding: 32,
    textAlign: "center",
  },
  noSessionTitle: { color: t.textPrimary, fontSize: t.fontLg, fontWeight: 600 },
  noSessionDetail: { maxWidth: 380, color: t.textTertiary, fontSize: t.fontBase },
  section: { display: "flex", flexDirection: "column", gap: 8 },
  sectionHeading: { display: "flex", flexDirection: "column", gap: 3 },
  sectionTitle: { margin: 0, color: t.textPrimary, fontSize: t.fontBase, fontWeight: 600 },
  sectionDescription: { margin: 0, color: t.textTertiary, fontSize: t.fontSm },
  list: { display: "flex", flexDirection: "column", gap: 2 },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minHeight: 42,
    padding: "7px 9px",
    borderRadius: t.radiusLg,
    backgroundColor: t.bgFaint,
  },
  rowIcon: {
    display: "grid",
    placeItems: "center",
    width: 18,
    color: t.iconTertiary,
    flexShrink: 0,
  },
  rowBody: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0 },
  rowTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: t.textPrimary,
    fontSize: t.fontBase,
    fontWeight: 500,
  },
  rowDetail: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: t.textTertiary,
    fontSize: t.fontSm,
  },
  badge: {
    flexShrink: 0,
    padding: "2px 6px",
    borderRadius: t.radiusFull,
    backgroundColor: t.fillSecondary,
    color: t.textTertiary,
    fontSize: t.fontXs,
  },
  failedBadge: { backgroundColor: t.fillDangerSubtle, color: t.textDanger },
  select: {
    width: 190,
    height: control.regularHeight,
    flexShrink: 0,
    paddingInline: 8,
    borderRadius: t.radiusLg,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.borderWeak,
    backgroundColor: t.bgBase,
    color: t.textPrimary,
    fontSize: t.fontBase,
    outline: "none",
  },
  quiet: {
    minHeight: 42,
    display: "flex",
    alignItems: "center",
    paddingInline: 9,
    borderRadius: t.radiusLg,
    backgroundColor: t.bgFaint,
    color: t.textTertiary,
    fontSize: t.fontBase,
  },
  loadingLine: {
    width: "42%",
    height: 8,
    borderRadius: t.radiusFull,
    backgroundColor: t.fillSecondary,
  },
  error: { color: t.textDanger, fontSize: t.fontSm },
});
