/** Settings › Models geometry beyond the shared settings patterns. */
import * as stylex from "@stylexjs/stylex";
import { t } from "../theme/vars.stylex.ts";

export const modelsSettingsStyles = stylex.create({
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 32,
    paddingInline: 10,
    borderRadius: t.radiusBase,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: t.borderWeak, ":focus-within": t.borderDefault },
    backgroundColor: t.bgFaint,
    color: t.iconTertiary,
  },
  searchInput: {
    minWidth: 0,
    flex: 1,
    padding: 0,
    borderStyle: "none",
    outlineStyle: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    "::placeholder": { color: t.textTertiary },
  },
  groupHeading: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: 8,
    minHeight: 44,
    paddingInline: 6,
    paddingBlock: 4,
  },
  groupTrigger: {
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: "transparent",
    textAlign: "left",
    cursor: "pointer",
  },
  groupLabel: {
    display: "flex",
    alignItems: "center",
    flex: "1 1 auto",
    minWidth: 0,
    minHeight: 36,
    gap: 8,
    padding: 6,
    color: t.iconSecondary,
  },
  groupPanel: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: t.strokeQuaternary,
  },
  groupTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: t.textPrimary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
  },
  groupMeta: {
    flex: 1,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  groupActions: { display: "inline-flex", gap: 2, marginInlineStart: "auto" },
  modelRow: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    columnGap: 12,
    minHeight: 44,
    padding: "8px 12px",
    "::after": {
      position: "absolute",
      insetInline: 12,
      insetBlockEnd: 0,
      height: 1,
      backgroundColor: t.strokeQuaternary,
      content: '""',
    },
    ":last-child::after": { display: "none" },
  },
  modelBody: { display: "flex", flexDirection: "column", minWidth: 0 },
  modelName: {
    color: t.textPrimary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  modelMeta: {
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
  },
  quiet: {
    display: "flex",
    alignItems: "center",
    minHeight: 44,
    paddingInline: 12,
    borderRadius: t.radiusXl,
    backgroundColor: t.bgFaint,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  keyForm: { display: "flex", flexDirection: "column", gap: 6 },
  keyRow: { display: "flex", alignItems: "center", gap: 6 },
  keyInput: {
    flex: 1,
    minWidth: 0,
    height: 26,
    paddingInline: 8,
    borderRadius: t.radiusBase,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: t.borderWeak, ":focus": t.borderDefault },
    outlineStyle: "none",
    backgroundColor: t.bgBase,
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    "::placeholder": { color: t.textTertiary, fontFamily: t.fontSans },
  },
  keyHint: { color: t.textTertiary, fontSize: t.fontSm, lineHeight: t.leadingSm },
  alert: { color: t.textDanger, fontSize: t.fontSm, lineHeight: t.leadingSm },
});
