import * as stylex from "@stylexjs/stylex";
import { t } from "../theme/vars.stylex.ts";

export const searchPaletteStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    flex: 1,
  },
  searchRow: {
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 10,
    minHeight: 56,
    paddingInline: 18,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.borderWeak,
    color: t.iconSecondary,
  },
  input: {
    minWidth: 0,
    height: 40,
    padding: 0,
    borderStyle: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontFamily: t.fontSans,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
    "::placeholder": { color: t.textTertiary },
  },
  tabs: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    paddingInline: 8,
    paddingBlock: 7,
    overflowX: "auto",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.borderWeak,
  },
  tab: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 26,
    flexShrink: 0,
    paddingBlock: 3,
    paddingInline: 10,
    borderStyle: "none",
    borderRadius: t.radiusSm,
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 2,
    outlineColor: t.focusRing,
    outlineOffset: -2,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textSecondary,
    fontFamily: t.fontSans,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    cursor: "pointer",
  },
  tabSelected: { backgroundColor: t.fillGhostSelected, color: t.textPrimary },
  results: {
    minHeight: 0,
    maxHeight: "min(320px, calc(100vh - 220px))",
    flexGrow: 1,
    flexShrink: 1,
    padding: 8,
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  groupLabel: {
    paddingInline: 12,
    paddingBlockStart: 7,
    paddingBlockEnd: 4,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    userSelect: "none",
  },
  result: {
    minHeight: 32,
    alignItems: "center",
    paddingBlock: 6,
    paddingInline: 12,
    columnGap: 10,
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":is([data-highlighted])": t.fillGhostHover,
    },
    color: t.textSecondary,
  },
  empty: {
    display: "grid",
    placeItems: "center",
    minHeight: 152,
    padding: 24,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textAlign: "center",
  },
});
