/**
 * Sidebar feature styles.
 * Based on https://github.com/interfaces-lab/honk/blob/main/packages/app/src/desktop-extensions/vertical-sidebar/view.tsx
 */
import * as stylex from "@stylexjs/stylex";
import { sidebar } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const sidebarStyles = stylex.create({
  rail: {
    display: "flex",
    flexDirection: "column",
    width: sidebar.width,
    minWidth: 0,
    minHeight: 0,
    flexShrink: 0,
    containerType: "inline-size",
    containerName: "nyte-sidebar",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  contentLayer: {
    display: { default: "flex", "[hidden]": "none" },
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  primaryActions: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    paddingInline: sidebar.gutter,
    paddingBlockStart: 6,
  },
  navRow: {
    "--_shortcut-opacity": {
      default: "0",
      ":hover": { "@media (hover: hover) and (pointer: fine)": "1" },
      ":focus-visible": "1",
    },
    display: "flex",
    alignItems: "center",
    gap: sidebar.rowGap,
    width: "100%",
    height: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    borderRadius: t.radiusLg,
    borderStyle: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    color: {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
      ":focus-visible": t.textPrimary,
    },
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    fontWeight: 400,
    textAlign: "left",
    cursor: "pointer",
    flexShrink: 0,
    transitionProperty: "background-color",
    transitionDuration: t.durationFast,
    transitionTimingFunction: t.easeOut,
  },
  navRowActive: {
    "--_shortcut-opacity": "1",
    backgroundColor: {
      default: t.fillGhostSelected,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostSelected },
    },
    color: t.textPrimary,
  },
  navIcon: {
    display: "grid",
    placeItems: "center",
    width: sidebar.iconSlot,
    height: sidebar.iconSlot,
    color: "inherit",
    flexShrink: 0,
  },
  navLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  shortcutSlot: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    minWidth: sidebar.trailingWidth,
    flexShrink: 0,
    opacity: "var(--_shortcut-opacity)",
    transitionProperty: "opacity",
    transitionDuration: t.durationFast,
    transitionTimingFunction: t.easeOut,
  },
  shortcutPersistent: { opacity: 1 },
  scroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: sidebar.sectionGap,
    paddingInline: sidebar.gutter,
    paddingBlockStart: sidebar.gutter,
    paddingBlockEnd: sidebar.gutter,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    minWidth: 0,
  },
  sectionHeader: {
    "--_section-chevron-opacity": {
      default: "0",
      ":hover": { "@media (hover: hover) and (pointer: fine)": "1" },
      ":focus-within": "1",
    },
    display: "flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    height: sidebar.rowHeight,
    paddingInlineEnd: sidebar.rowPaddingInline,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    fontWeight: 400,
    flexShrink: 0,
  },
  sectionToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
    height: "100%",
    paddingInlineStart: sidebar.rowPaddingInline,
    paddingInlineEnd: 4,
    flex: 1,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: "transparent",
    color: "inherit",
    fontSize: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  sectionChevron: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: t.iconTertiary,
    opacity: "var(--_section-chevron-opacity)",
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  sectionChevronOpen: { transform: "rotate(90deg)" },
  sectionLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  workspaceCollection: {
    display: { default: "flex", "[hidden]": "none" },
    flexDirection: "column",
    gap: sidebar.listGap,
    minWidth: 0,
  },
  row: {
    "--_workspace-folder-display": {
      default: "inline-flex",
      ":hover": "none",
      ":focus-within": "none",
    },
    "--_workspace-chevron-display": {
      default: "none",
      ":hover": "inline-flex",
      ":focus-within": "inline-flex",
    },
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: sidebar.rowGap,
    width: "100%",
    minHeight: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    borderRadius: t.radiusBase,
    borderStyle: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textAlign: "left",
    cursor: "pointer",
    flexShrink: 0,
    transitionProperty: "background-color, color",
    transitionDuration: t.durationFast,
    transitionTimingFunction: t.easeOut,
  },
  /**
   * The row is the drag source and the pulse keeps the leading slot; the
   * hover actions replace the timestamp in the trailing column.
   */
  sessionRowShell: {
    "--_row-actions-opacity": {
      default: "0",
      ":hover": "1",
      ":focus-within": "1",
    },
    "--_row-actions-pointer-events": {
      default: "none",
      ":hover": "auto",
      ":focus-within": "auto",
    },
    "--_row-meta-opacity": {
      default: "1",
      ":hover": "0",
      ":focus-within": "0",
    },
    "--_session-row-background": {
      default: "transparent",
      ":hover": t.fillGhostHover,
      ":focus-within": t.fillGhostHover,
    },
    position: "relative",
    width: "100%",
    minWidth: 0,
    borderRadius: t.radiusBase,
  },
  sessionRow: {
    backgroundColor: "var(--_session-row-background)",
    touchAction: "none",
    userSelect: "none",
    WebkitUserDrag: "none",
  },
  /** Replaces the row's title while renaming; same footprint, so the list does not jump. */
  sessionRenameRow: {
    display: "flex",
    alignItems: "center",
    gap: sidebar.rowGap,
    width: "100%",
    minHeight: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    borderRadius: t.radiusBase,
    backgroundColor: t.fillGhostSelected,
  },
  sessionRenameInput: {
    flex: 1,
    minWidth: 0,
    height: 22,
    paddingInline: 6,
    borderRadius: t.radiusSm,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: t.borderWeak, ":focus-visible": t.strokeFocused },
    backgroundColor: t.bgElevated,
    color: t.textPrimary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    outline: "none",
  },
  rowSelected: {
    "--_session-row-background": {
      default: t.fillGhostSelected,
      ":hover": t.fillGhostSelected,
      ":focus-within": t.fillGhostSelected,
    },
    color: t.textPrimary,
  },
  rowIcon: {
    display: "grid",
    placeItems: "center",
    width: sidebar.iconSlot,
    height: sidebar.iconSlot,
    color: t.iconTertiary,
    flexShrink: 0,
  },
  workspaceGlyph: {
    position: "relative",
    display: "grid",
    placeItems: "center",
    width: "100%",
    height: "100%",
  },
  workspaceFolder: {
    position: "absolute",
    display: "var(--_workspace-folder-display)",
  },
  workspaceChevron: {
    position: "absolute",
    display: "var(--_workspace-chevron-display)",
    transform: "rotate(-90deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationSlow,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  workspaceChevronOpen: { transform: "rotate(0deg)" },
  rowTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  workspaceUnavailable: { color: t.textTertiary },
  trailing: {
    display: "grid",
    width: sidebar.trailingWidth,
    marginInlineStart: "auto",
    flexShrink: 0,
  },
  /** Wide enough for both hover actions, so the title never runs under them. */
  sessionTrailing: {
    width: `max(${sidebar.trailingWidth}, calc(2 * ${sidebar.actionSize}))`,
  },
  rowMeta: {
    gridArea: "1 / 1",
    alignSelf: "center",
    justifySelf: "end",
    color: t.textTertiary,
    fontSize: t.fontXs,
    fontVariantNumeric: "tabular-nums",
    opacity: "var(--_row-meta-opacity)",
  },
  rowActions: {
    gridArea: "1 / 1",
    display: "inline-flex",
    justifySelf: "end",
    alignItems: "center",
    opacity: "var(--_row-actions-opacity)",
    pointerEvents: "var(--_row-actions-pointer-events)",
  },
  sessionRowActions: {
    position: "absolute",
    zIndex: 1,
    insetInlineEnd: sidebar.rowPaddingInline,
    top: "50%",
    transform: "translateY(-50%)",
  },
  rowDragging: {
    cursor: "grabbing",
    opacity: 0.65,
    userSelect: "none",
    WebkitUserDrag: "none",
  },
  action: {
    display: "grid",
    placeItems: "center",
    width: sidebar.actionSize,
    height: sidebar.actionSize,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillSecondaryHover },
    color: t.iconTertiary,
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.5 },
  },
  workspaceRowShell: {
    "--_row-actions-opacity": {
      default: "0",
      ":hover": "1",
      ":focus-within": "1",
    },
    "--_row-actions-pointer-events": {
      default: "none",
      ":hover": "auto",
      ":focus-within": "auto",
    },
    position: "relative",
    minWidth: 0,
  },
  workspaceRowTrigger: {
    paddingInlineEnd: `calc(${sidebar.rowPaddingInline} + ${sidebar.actionSize} + 2px)`,
  },
  workspaceCreateAction: {
    position: "absolute",
    zIndex: 1,
    insetInlineEnd: sidebar.rowPaddingInline,
    top: "50%",
    display: "grid",
    placeItems: "center",
    width: sidebar.actionSize,
    height: sidebar.actionSize,
    padding: 0,
    transform: "translateY(-50%)",
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillSecondaryHover },
    },
    color: t.iconTertiary,
    opacity: "var(--_row-actions-opacity)",
    pointerEvents: "var(--_row-actions-pointer-events)",
    cursor: "pointer",
    transitionProperty: "opacity, background-color",
    transitionDuration: t.durationFast,
    transitionTimingFunction: t.easeOut,
  },
  sessionList: {
    display: { default: "flex", "[hidden]": "none" },
    flexDirection: "column",
    gap: sidebar.listGap,
    flexShrink: 0,
  },
  sessionGroupLabel: {
    minHeight: sidebar.rowHeight,
    paddingInlineStart: `calc(${sidebar.rowPaddingInline} + ${sidebar.iconSlot} + ${sidebar.rowGap})`,
    paddingInlineEnd: sidebar.rowPaddingInline,
    paddingBlock: 4,
    color: t.textTertiary,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
    userSelect: "none",
  },
  quiet: {
    display: "flex",
    alignItems: "center",
    minHeight: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    paddingBlock: 0,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    flexShrink: 0,
  },
  sessionQuiet: {
    paddingInlineStart: `calc(${sidebar.rowPaddingInline} + ${sidebar.iconSlot} + ${sidebar.rowGap})`,
  },
  showMore: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    minHeight: sidebar.rowHeight,
    paddingInline: `calc(${sidebar.rowPaddingInline} + ${sidebar.iconSlot} + ${sidebar.rowGap})`,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textTertiary,
    fontSize: t.fontBase,
    textAlign: "left",
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.72 },
    flexShrink: 0,
  },
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    paddingInline: sidebar.gutter,
    paddingBlock: sidebar.gutter,
    flexShrink: 0,
  },
  footerRow: { display: "flex", alignItems: "center", gap: 2, minWidth: 0 },
  accountButton: {
    width: "auto",
    minWidth: 0,
    flex: 1,
  },
  footerSettings: {
    display: "grid",
    placeItems: "center",
    width: sidebar.rowHeight,
    height: sidebar.rowHeight,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.iconTertiary,
    cursor: "pointer",
    flexShrink: 0,
  },
  footerSettingsActive: {
    backgroundColor: {
      default: t.fillGhostSelected,
      ":hover": t.fillGhostSelected,
    },
    color: t.iconPrimary,
  },
  avatarSlot: { borderRadius: t.radiusSm, overflow: "hidden" },
  avatar: { display: "block", width: "100%", height: "100%", objectFit: "cover" },
});
