/**
 * Sidebar feature styles.
 * Based on https://github.com/interfaces-lab/honk/blob/main/packages/app/src/desktop-extensions/vertical-sidebar/view.tsx
 */
import * as stylex from "@stylexjs/stylex";
import { sidebar } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const sidebarStyles = stylex.create({
  rail: {
    display: "flex",
    flexDirection: "column",
    width: sidebar.width,
    minWidth: 0,
    minHeight: 0,
    flexShrink: 0,
    containerType: "inline-size",
    containerName: "uji-sidebar",
  },
  primaryActions: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    paddingInline: sidebar.gutter,
  },
  navRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    height: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    borderRadius: t.radiusBase,
    borderStyle: "none",
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textPrimary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    fontWeight: 400,
    textAlign: "left",
    cursor: "pointer",
    flexShrink: 0,
    transitionProperty: "background-color",
    transitionDuration: t.durationFast,
  },
  navRowActive: { backgroundColor: t.fillGhostSelected },
  navRowDisabled: { cursor: "default", opacity: 0.5 },
  navIcon: {
    display: "grid",
    placeItems: "center",
    width: sidebar.iconSlot,
    height: sidebar.iconSlot,
    color: t.iconSecondary,
    flexShrink: 0,
  },
  navLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  shortcutSlot: {
    display: "flex",
    justifyContent: "flex-end",
    width: sidebar.trailingWidth,
    flexShrink: 0,
  },
  search: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    height: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    borderRadius: t.radiusBase,
    backgroundColor: t.bgFaint,
    color: t.iconSecondary,
    flexShrink: 0,
    boxShadow: { default: "none", ":focus-within": `inset 0 0 0 1px ${t.strokeFocused}` },
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontSize: t.fontBase,
    outline: "none",
    "::placeholder": { color: t.textTertiary },
  },
  clearSearch: {
    display: "grid",
    placeItems: "center",
    width: sidebar.actionSize,
    height: sidebar.actionSize,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.iconTertiary,
    cursor: "pointer",
    flexShrink: 0,
  },
  scroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: sidebar.sectionGap,
    paddingInline: sidebar.gutter,
    paddingBlockStart: sidebar.gutter,
    paddingBlockEnd: sidebar.gutter,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    minWidth: 0,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    height: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    color: t.textTertiary,
    fontSize: t.fontBase,
    fontWeight: 400,
    flexShrink: 0,
  },
  sectionLabel: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  row: {
    "--_row-meta-opacity": {
      default: "1",
      ":hover": "0",
      ":focus-within": "0",
    },
    "--_row-actions-opacity": {
      default: "0",
      ":hover": "1",
      ":focus-within": "1",
    },
    "--_row-actions-pointer-events": {
      default: "none",
      ":hover": "auto",
      ":focus-within": "auto",
    },
    "--_workspace-folder-opacity": {
      default: "1",
      ":hover": "0",
      ":focus-within": "0",
    },
    "--_workspace-chevron-opacity": {
      default: "0",
      ":hover": "1",
      ":focus-within": "1",
    },
    display: "flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    minHeight: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    borderRadius: t.radiusBase,
    borderStyle: "none",
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textAlign: "left",
    cursor: "pointer",
    flexShrink: 0,
    transitionProperty: "background-color, color",
    transitionDuration: t.durationFast,
  },
  rowSelected: { backgroundColor: t.fillGhostSelected, color: t.textPrimary },
  rowIcon: {
    display: "grid",
    placeItems: "center",
    width: sidebar.iconSlot,
    height: sidebar.iconSlot,
    color: t.iconTertiary,
    flexShrink: 0,
  },
  workspaceGlyph: {
    position: "relative",
    display: "grid",
    placeItems: "center",
    width: "100%",
    height: "100%",
  },
  workspaceFolder: {
    position: "absolute",
    display: "inline-flex",
    opacity: "var(--_workspace-folder-opacity)",
    transitionProperty: "opacity",
    transitionDuration: t.durationFast,
    transitionTimingFunction: "ease",
  },
  workspaceChevron: {
    position: "absolute",
    display: "inline-flex",
    opacity: "var(--_workspace-chevron-opacity)",
    transitionProperty: "opacity, transform",
    transitionDuration: t.durationNormal,
    transitionTimingFunction: "ease",
  },
  workspaceChevronOpen: { transform: "rotate(90deg)" },
  rowTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  trailing: {
    display: "grid",
    width: sidebar.trailingWidth,
    marginInlineStart: "auto",
    flexShrink: 0,
  },
  rowMeta: {
    gridArea: "1 / 1",
    alignSelf: "center",
    justifySelf: "end",
    color: t.textQuaternary,
    fontSize: t.fontXs,
    fontVariantNumeric: "tabular-nums",
    opacity: "var(--_row-meta-opacity)",
  },
  rowActions: {
    gridArea: "1 / 1",
    display: "inline-flex",
    justifySelf: "end",
    alignItems: "center",
    opacity: "var(--_row-actions-opacity)",
    pointerEvents: "var(--_row-actions-pointer-events)",
  },
  rowDragging: {
    cursor: "grabbing",
    opacity: 0.65,
    userSelect: "none",
    WebkitUserDrag: "none",
  },
  action: {
    display: "grid",
    placeItems: "center",
    width: sidebar.actionSize,
    height: sidebar.actionSize,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillSecondaryHover },
    color: t.iconTertiary,
    cursor: "pointer",
  },
  workspaceCollapsible: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    minWidth: 0,
  },
  sessionList: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    height: {
      default: "var(--collapsible-panel-height)",
      "[data-starting-style]": 0,
      "[data-ending-style]": 0,
    },
    paddingInlineStart: sidebar.gutter,
    overflow: "hidden",
    flexShrink: 0,
    transitionProperty: "height",
    transitionDuration: {
      default: "150ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  quiet: {
    minHeight: sidebar.rowHeight,
    paddingInline: sidebar.rowPaddingInline,
    paddingBlock: 4,
    color: t.textQuaternary,
    fontSize: t.fontBase,
    flexShrink: 0,
  },
  showMore: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    minHeight: sidebar.rowHeight,
    paddingInline: `calc(${sidebar.rowPaddingInline} + ${sidebar.iconSlot} + 4px)`,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.textTertiary,
    fontSize: t.fontBase,
    textAlign: "left",
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.72 },
    flexShrink: 0,
  },
  renameInput: {
    flex: 1,
    minWidth: 0,
    height: 24,
    paddingInline: 5,
    borderRadius: t.radiusSm,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.borderAccent,
    backgroundColor: t.bgElevated,
    color: t.textPrimary,
    fontSize: t.fontBase,
    outline: "none",
  },
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: sidebar.listGap,
    paddingInline: sidebar.gutter,
    paddingBlock: sidebar.gutter,
    flexShrink: 0,
  },
  footerRow: { display: "flex", alignItems: "center", gap: 2, minWidth: 0 },
  accountButton: { width: "auto", minWidth: 0, flex: 1 },
  footerSettings: {
    display: "grid",
    placeItems: "center",
    width: sidebar.rowHeight,
    height: sidebar.rowHeight,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.iconTertiary,
    cursor: "pointer",
    flexShrink: 0,
  },
  accountPlaceholder: { height: sidebar.rowHeight, visibility: "hidden", flex: 1 },
  avatarSlot: { borderRadius: t.radiusSm, overflow: "hidden" },
  avatar: { display: "block", width: "100%", height: "100%", objectFit: "cover" },
});
