import { create } from "@stylexjs/stylex";
import { layer, shell, sidebar } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const titlebarStyles = create({
  bar: {
    position: "relative",
    zIndex: layer.chrome,
    display: "flex",
    alignItems: "center",
    height: shell.titlebarHeight,
    paddingInlineEnd: 10,
    paddingInlineStart: 10,
    flexShrink: 0,
    WebkitAppRegion: "drag",
  },
  contentFill: {
    position: "absolute",
    insetBlock: 0,
    insetInlineStart: `calc(${sidebar.width} - 1px)`,
    insetInlineEnd: 0,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.strokeQuaternary,
    backgroundClip: "padding-box",
    backgroundColor: t.bgBase,
    pointerEvents: "none",
  },
  contentFillSidebarHidden: { insetInlineStart: 0, borderInlineStartWidth: 0 },
  workbenchTrack: {
    position: "absolute",
    zIndex: 3,
    insetBlock: 0,
    insetInlineEnd: 0,
    display: "flex",
    alignItems: "center",
    gap: 2,
    width: "var(--nyte-active-workbench-width, 500px)",
    minWidth: 0,
    paddingInlineStart: 6,
    paddingInlineEnd: 10,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.strokeTertiary,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.strokeTertiary,
    backgroundColor: t.bgBase,
    WebkitAppRegion: "no-drag",
  },
  workbenchTrackSidebarHiddenMac: { maxWidth: "calc(100% - 112px)" },
  workbenchTrackSidebarHidden: { maxWidth: "calc(100% - 38px)" },
  workbenchReservation: {
    width: "calc(var(--nyte-active-workbench-width, 500px) - 10px)",
    flexShrink: 0,
  },
  titleSlotWorkbenchOpen: {
    insetInlineEnd: "calc(var(--nyte-active-workbench-width, 500px) + 44px)",
  },
  // macOS reserves a traffic-light lane at the leading edge.
  barMac: { paddingInlineStart: shell.trafficLightInset },
  actionTrack: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    flexShrink: 0,
    position: "relative",
    zIndex: 1,
    WebkitAppRegion: "no-drag",
  },
  navigationTrack: {
    position: "absolute",
    zIndex: 2,
    insetInlineStart: `calc(${sidebar.width} - 64px)`,
    insetBlock: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    WebkitAppRegion: "no-drag",
  },
  spacer: { flex: 1, minWidth: 0 },
  titleSlot: {
    position: "absolute",
    zIndex: 1,
    insetBlock: 0,
    insetInlineStart: `calc(${sidebar.width} + 12px)`,
    insetInlineEnd: 96,
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    pointerEvents: "none",
  },
  // 72px of traffic lights, the 28px toggle, then a 12px title gap on macOS;
  // elsewhere the toggle alone.
  titleSlotSidebarHiddenMac: { insetInlineStart: 112 },
  titleSlotSidebarHidden: { insetInlineStart: 38 },
  sessionTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  sessionBack: {
    display: "inline-flex",
    flexShrink: 0,
    pointerEvents: "auto",
    WebkitAppRegion: "no-drag",
  },
  sessionTitle: {
    maxWidth: "min(420px, 50vw)",
    overflow: "hidden",
    color: t.textSecondary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
