import type { ResolvedValues, SelectConfig, TextConfig } from "dialkit";
import { decisions } from "./decisions";
import type { Decision } from "./decisions";
import type { Measured } from "./measure";

const picks = ["undecided", "v1", "v2", "custom"] as const;

export type Pick = (typeof picks)[number];

export interface Choice {
  readonly pick: Pick;
  readonly custom: string;
  readonly note: string;
}

export type Choices = ReadonlyMap<string, Choice>;

/** What the preview shows: the choices as made, or every decision forced to one side. */
export type Compare = "choices" | "v1" | "v2";

const emptyChoice: Choice = { pick: "undecided", custom: "", note: "" };

function choiceOf(choices: Choices, id: string): Choice {
  return choices.get(id) ?? emptyChoice;
}

function optionLabel(side: string, value: string | undefined) {
  return value === undefined || value === "" ? side : `${side} · ${value}`;
}

type DecisionFolder = {
  _collapsed: boolean;
  pick: SelectConfig;
  custom: TextConfig;
  note: TextConfig;
};

type DecisionConfig = Record<string, Record<string, DecisionFolder>>;

export function decisionConfig(measured: ReadonlyMap<string, Measured>) {
  const config: DecisionConfig = {};

  /*
   * DialKit labels come from config keys and paths split on dots, so each
   * decision sits under its group and title; no title contains a dot.
   */
  for (const decision of decisions) {
    const values = measured.get(decision.id);
    const code = decision.kind === "code";
    const group = config[decision.group] ?? {};
    config[decision.group] = group;
    group[decision.title] = {
      _collapsed: true,
      pick: {
        type: "select",
        options: [
          { value: "undecided", label: "Undecided" },
          { value: "v1", label: optionLabel("v1", code ? decision.v1Text : values?.v1) },
          {
            value: "v2",
            label: optionLabel("v2", code ? decision.v2Text : Object.values(decision.set)[0]),
          },
          { value: "custom", label: "Custom" },
        ],
        default: decision.pick,
      },
      custom: {
        type: "text",
        placeholder: code ? "Custom decision" : (Object.keys(decision.set)[0] ?? "Any CSS"),
      },
      note: {
        type: "text",
        placeholder:
          decision.note === undefined
            ? `Look: ${decision.look}`
            : `Look: ${decision.look} ${decision.note}`,
      },
    };
  }

  return config;
}

export function choicesFrom(values: ResolvedValues<DecisionConfig>): Choices {
  const result = new Map<string, Choice>();

  for (const decision of decisions) {
    const folder = values[decision.group]?.[decision.title];

    if (folder === undefined) continue;
    const pick = picks.find((candidate) => candidate === folder.pick) ?? "undecided";
    result.set(decision.id, { pick, custom: folder.custom, note: folder.note });
  }

  return result;
}

/**
 * The declarations one decision contributes. v1 contributes nothing: removing
 * the override is what hands the property back to the desktop tokens.
 */
function declarationsFor(decision: Decision, pick: Pick, custom: string) {
  const entries = Object.entries(decision.set);

  if (pick === "v2") return entries;
  const first = entries[0];

  if (pick !== "custom" || first === undefined || custom.trim() === "") return [];

  return [[first[0], custom.trim()] as const, ...entries.slice(1)];
}

export function resolveOverrides(choices: Choices, compare: Compare) {
  const result = new Map<string, string>();

  for (const decision of decisions) {
    const choice = choiceOf(choices, decision.id);
    const pick = compare === "choices" ? choice.pick : compare;

    for (const [property, value] of declarationsFor(decision, pick, choice.custom))
      result.set(property, value);
  }

  return result;
}

/** Stylesheet text for the chosen decisions that preview through CSS instead of tokens. */
export function resolvePreviewCss(choices: Choices, compare: Compare) {
  return decisions
    .filter((decision) => {
      const pick = compare === "choices" ? choiceOf(choices, decision.id).pick : compare;

      return pick === "v2" && decision.previewCss !== undefined;
    })
    .map((decision) => decision.previewCss ?? "")
    .join("\n");
}

function summaryOf(decision: Decision, choice: Choice) {
  if (choice.pick === "v2") return decision.v2Text ?? "";

  if (choice.pick === "custom") return choice.custom;

  return decision.v1Text ?? "";
}

export function exportCss(choices: Choices): string {
  const lines = [
    "/*",
    " * Token choice, generated by packages/lab/index.html.",
    " * v2 values are live expressions over the lab palette (palette.css);",
    " * keep them as var()/color-mix so translucent steps composite correctly.",
    " */",
    ":root {",
  ];

  for (const decision of decisions) {
    if (decision.kind === "code") continue;
    const choice = choiceOf(choices, decision.id);
    const declarations = declarationsFor(decision, choice.pick, choice.custom);

    if (declarations.length === 0) continue;
    const note = choice.note === "" ? "" : `: ${choice.note}`;
    const source = choice.pick === "v2" ? ` (${decision.source})` : "";
    lines.push(`  /* ${decision.title}, ${choice.pick}${source}${note} */`);

    for (const [property, value] of declarations) lines.push(`  ${property}: ${value};`);
  }

  lines.push("}");

  const code = decisions.filter(
    (decision) => decision.kind === "code" && choiceOf(choices, decision.id).pick !== "undecided",
  );

  if (code.length === 0) return lines.join("\n");
  lines.push("", "/* Code changes chosen (no token can express these):");

  for (const decision of code) {
    const choice = choiceOf(choices, decision.id);
    const note = choice.note === "" ? "" : ` (${choice.note})`;
    lines.push(` * ${decision.title}: ${choice.pick}, ${summaryOf(decision, choice)}${note}`);
  }

  lines.push(" */");

  return lines.join("\n");
}
