/**
 * Every decision between the desktop tokens (v1) and the Notion Calendar
 * tokens (v2), in the order worth walking them.
 *
 * `set` holds the v2 declarations. Values stay live CSS expressions that
 * resolve inside the fixture: `var(--text-secondary)` from palette.css, never
 * a flattened hex, so translucent steps keep compositing over whatever surface
 * sits beneath them.
 *
 * v2 colour sources are Notion Calendar's own `--nds-*` tokens, read from the
 * calendar.notion.so bundles its desktop app caches (cron-*.js, useStores-*.js).
 */

export type DecisionKind = "color" | "length" | "shadow" | "font" | "code";

export interface Decision {
  readonly id: string;
  /** The side chosen for the desktop tokens; the panel opens on it. */
  readonly pick: "v1" | "v2";
  readonly group: string;
  readonly title: string;
  /** Where in the preview the difference shows, and what has to be open to see it. */
  readonly look: string;
  readonly kind: DecisionKind;
  /** v2 declarations. The first property is the one a custom value replaces. */
  readonly set: Readonly<Record<string, string>>;
  readonly source: string;
  readonly note?: string;
  /** For `code` decisions, which have nothing to preview: what each side means. */
  readonly v1Text?: string;
  readonly v2Text?: string;
  /**
   * CSS injected into the fixture while v2 is chosen, for decisions no token
   * can reach. It targets the popups by ARIA role, which Base UI sets, so the
   * preview runs on the real desktop surfaces without touching their code.
   */
  readonly previewCss?: string;
}

const calendarSans =
  'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI Variable Display", "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif';

export const decisions: readonly Decision[] = [
  {
    id: "surface-chrome",
    pick: "v2",
    group: "Surfaces",
    title: "Window and main pane",
    look: "the titlebar, the transcript pane, the workbench rail.",
    kind: "color",
    set: { "--nyte-page-base": "var(--surface-page)" },
    source: "nds-surface-page",
  },
  {
    id: "surface-editor",
    pick: "v2",
    group: "Surfaces",
    title: "Editor and elevated surfaces",
    look: "the composer, user message bubbles, the Send arrow, the open Agents tray.",
    kind: "color",
    set: { "--nyte-page-base": "var(--surface-page)" },
    source: "nds-surface-page",
    note: "Menus and dialogs read Raised surface, not this.",
  },
  {
    id: "surface-sidebar",
    pick: "v2",
    group: "Surfaces",
    title: "Sidebar",
    look: "the sidebar and the window behind it.",
    kind: "color",
    set: { "--nyte-sidebar-base": "var(--surface-wash)" },
    source: "nds-surface-wash",
    note: "v1 dark lets 64% of the window material through; v2 keeps that layer and moves only the colour.",
  },
  {
    id: "surface-raised",
    pick: "v2",
    group: "Surfaces",
    title: "Raised surface",
    look: "the Agents pill; menu, popover and dialog panels; the icon rail; the Panel's commit box.",
    kind: "color",
    set: { "--nyte-bg-raised": "var(--surface-elevated)" },
    source: "nds-surface-elevated",
  },
  {
    id: "ink-base",
    pick: "v2",
    group: "Ink",
    title: "Base ink",
    look: "everywhere.",
    kind: "color",
    set: { "--nyte-ink": "var(--text-primary)" },
    source: "nds-text-primary",
    note: "v1 steps mix from this, so v2 here keeps each layer translucent. Dark v2 ink is 81% white; the mixes compound.",
  },
  {
    id: "text-secondary",
    pick: "v1",
    group: "Ink",
    title: "Secondary text",
    look: "the titlebar title, sidebar labels, the Agents pill, dialog text.",
    kind: "color",
    set: { "--nyte-text-secondary": "var(--text-secondary)" },
    source: "nds-text-secondary",
    note: "v1 is ink at 74%; v2 is opaque in light. Keep the layer: v1 here, v2 Base ink.",
  },
  {
    id: "text-tertiary",
    pick: "v1",
    group: "Ink",
    title: "Tertiary text",
    look: "the Workspaces heading, chat times, the composer placeholder, menu shortcuts and headings.",
    kind: "color",
    set: { "--nyte-text-tertiary": "var(--text-tertiary)" },
    source: "nds-text-tertiary",
  },
  {
    id: "text-quaternary",
    pick: "v2",
    group: "Ink",
    title: "Disabled text",
    look: "Surface: Menu, the disabled Enter full screen row.",
    kind: "color",
    set: { "--nyte-text-quaternary": "var(--text-quaternary)" },
    source: "nds-text-quaternary",
  },
  {
    id: "icon-primary",
    pick: "v2",
    group: "Ink",
    title: "Primary icons",
    look: "hover only: Filter workspaces, the Settings gear, a chat row's pin and archive.",
    kind: "color",
    set: { "--nyte-icon-primary": "var(--icon-primary)" },
    source: "nds-icon-primary",
  },
  {
    id: "icon-secondary",
    pick: "v2",
    group: "Ink",
    title: "Secondary icons",
    look: "the titlebar buttons, the composer +, the workbench rail icons, popover row icons.",
    kind: "color",
    set: { "--nyte-icon-secondary": "var(--icon-secondary)" },
    source: "nds-icon-secondary",
  },
  {
    id: "icon-tertiary",
    pick: "v2",
    group: "Ink",
    title: "Tertiary icons",
    look: "Filter, Add workspace, the Settings gear, Collapse workbench.",
    kind: "color",
    set: { "--nyte-icon-tertiary": "var(--icon-tertiary)" },
    source: "nds-icon-tertiary",
    note: "v2 is Calendar's own tertiary; calendar.css used icon-secondary.",
  },
  {
    id: "state-hover",
    pick: "v2",
    group: "Fills and states",
    title: "Hover fill",
    look: "inline code, Wrap long lines in Surface: Menu, hovered rows and icon buttons.",
    kind: "color",
    set: { "--nyte-fill-hover": "var(--state-hover)" },
    source: "nds-state-hover",
    note: "v1 is ink at 8%; v2 is black 4%, white 5% in dark.",
  },
  {
    id: "state-selected",
    pick: "v2",
    group: "Fills and states",
    title: "Selected fill",
    look: "the selected chat, hovered menu rows, the open Move to row, the Workbench: Panel tab.",
    kind: "color",
    set: { "--nyte-fill-selected": "var(--state-selected)" },
    source: "derived (Calendar ships no selected state)",
    note: "calendar.css reuses hover here.",
  },
  {
    id: "fill-quiet",
    pick: "v2",
    group: "Fills and states",
    title: "Quiet fill (secondary buttons, chips)",
    look: "the ⌘N key cap, the composer +, Cancel in Surface: Dialog.",
    kind: "color",
    set: { "--nyte-fill-quiet": "var(--gray-30)" },
    source: "nds-fill-grayTertiary",
    note: "v2 is opaque in dark. Keep the layer: v1 here, v2 Base ink.",
  },
  {
    id: "fill-strong",
    pick: "v2",
    group: "Fills and states",
    title: "Strong fill",
    look: "the disabled Send, the Surface: Popover highlight, Commit and push in the Panel.",
    kind: "color",
    set: { "--nyte-fill-strong": "var(--gray-100)" },
    source: "nds-tint-primaryHover",
    note: "v2 is opaque in dark. Keep the layer: v1 here, v2 Base ink.",
  },
  {
    id: "scrim",
    pick: "v2",
    group: "Fills and states",
    title: "Dialog scrim",
    look: "Surface: Dialog, the backdrop.",
    kind: "color",
    set: { "--nyte-bg-scrim": "var(--scrim)" },
    source: "derived (lab palette)",
  },
  {
    id: "stroke-primary",
    pick: "v2",
    group: "Strokes",
    title: "Strong border",
    look: "the quote bar in the last reply.",
    kind: "color",
    set: { "--nyte-stroke-primary": "var(--stroke-primary)" },
    source: "nds-stroke-primary",
  },
  {
    id: "stroke-secondary",
    pick: "v2",
    group: "Strokes",
    title: "Border",
    look: "menu and popover hairlines and separators, the dialog edge, the composer while focused, the Panel's commit box.",
    kind: "color",
    set: { "--nyte-stroke-secondary": "var(--stroke-secondary)" },
    source: "nds-stroke-secondary",
  },
  {
    id: "stroke-tertiary",
    pick: "v2",
    group: "Strokes",
    title: "Faint border (rings)",
    look: "user bubble, composer and inline code rings, the Agents pill, Workbench: Panel dividers.",
    kind: "color",
    set: { "--nyte-stroke-secondary": "var(--stroke-secondary)" },
    source: "nds-stroke-secondary",
    note: "Calendar has two stroke steps; v1 has four.",
  },
  {
    id: "stroke-quaternary",
    pick: "v2",
    group: "Strokes",
    title: "Hairline",
    look: "the sidebar's right edge.",
    kind: "color",
    set: { "--nyte-stroke-tertiary": "var(--gray-30)" },
    source: "nds-fill-grayTertiary",
    note: "v2 is opaque in dark. Keep the layer: v1 here, v2 Base ink.",
  },
  {
    id: "accent",
    pick: "v2",
    group: "Accent and status",
    title: "Accent",
    look: "the TypeScript file icon in Workbench: Panel, a ticked Viewed box there, keyboard focus rings (Tab), selected text.",
    kind: "color",
    set: { "--nyte-accent-base": "#3985d3" },
    source: "nds-fill-uiBlue",
  },
  {
    id: "text-accent",
    pick: "v2",
    group: "Accent and status",
    title: "Accent text, links, caret",
    look: "the running-chat spinners, the Agents pill's status, the link in the last reply.",
    kind: "color",
    set: { "--nyte-text-accent": "rgb(35 131 226)" },
    source: "nds-text-uiBluePrimary",
    note: "The caret follows primary ink, not this.",
  },
  {
    id: "fill-primary",
    pick: "v1",
    group: "Accent and status",
    title: "Primary action fill",
    look: "type in the composer, then look at Send.",
    kind: "color",
    set: { "--nyte-fill-inverse": "#3985d3" },
    source: "nds-fill-uiBlue",
    note: "Calendar's primary button is blue, not the inverted ink. Hover is state-hover laid over the fill.",
  },
  {
    id: "danger-fill",
    pick: "v1",
    group: "Accent and status",
    title: "Danger fill",
    look: "Delete in Surface: Dialog.",
    kind: "color",
    set: { "--nyte-red": "#e56458" },
    source: "nds-fill-uiRed",
  },
  {
    id: "danger-text",
    pick: "v1",
    group: "Accent and status",
    title: "Danger text",
    look: "Delete chat in Surface: Menu, hovered Delete in Surface: Dialog, removed counts in the Panel.",
    kind: "color",
    set: { "--nyte-text-danger": "rgb(212 76 71)" },
    source: "nds-text-uiRedPrimary",
    note: "Calendar menus use #BD4841.",
  },
  {
    id: "warning",
    pick: "v2",
    group: "Accent and status",
    title: "Warning text",
    look: "click the Agents pill above the composer: the waiting agent's dot.",
    kind: "color",
    set: { "--nyte-text-warning": "rgb(203 145 47)" },
    source: "nds-text-uiYellowPrimary",
  },
  {
    id: "success",
    pick: "v1",
    group: "Accent and status",
    title: "Success text",
    look: "the added counts in Workbench: Panel.",
    kind: "color",
    set: { "--nyte-text-success": "rgb(68 131 97)" },
    source: "nds-text-greenSecondary",
  },
  {
    id: "mention",
    pick: "v2",
    group: "Accent and status",
    title: "Mention and match text",
    look: "the file chip in the last user message.",
    kind: "color",
    set: { "--nyte-text-accent": "rgb(35 131 226)" },
    source: "proposed (Calendar has no cyan)",
  },
  {
    id: "switch",
    pick: "v2",
    group: "Accent and status",
    title: "Switch on",
    look: "Show whitespace in Surface: Menu.",
    kind: "color",
    set: { "--nyte-accent-base": "#3985d3" },
    source: "nds-fill-uiBlue",
  },
  {
    id: "diff-added",
    pick: "v2",
    group: "Accent and status",
    title: "Diff added",
    look: "Workbench: Panel, added lines and the changed words in them.",
    kind: "color",
    set: {
      "--nyte-diff-added-line-bg": "light-dark(var(--green-30), var(--green-50))",
      "--nyte-diff-added-text-bg": "light-dark(var(--green-100), var(--green-200))",
    },
    source: "proposed: nds-fill-greenTertiary / greenPrimary",
    note: "Dark reads the ramp's 50 and 200 washes; its 30 and 100 steps are opaque tints.",
  },
  {
    id: "diff-removed",
    pick: "v2",
    group: "Accent and status",
    title: "Diff removed",
    look: "Workbench: Panel, removed lines and the changed words in them.",
    kind: "color",
    set: {
      "--nyte-diff-removed-line-bg": "light-dark(var(--red-30), var(--red-50))",
      "--nyte-diff-removed-text-bg": "light-dark(var(--red-100), var(--red-200))",
    },
    source: "proposed: nds-fill-redTertiary / redPrimary",
    note: "Dark reads the ramp's 50 and 200 washes; its 30 and 100 steps are opaque tints.",
  },
  {
    id: "user-shell",
    pick: "v1",
    group: "Conversation",
    title: "User message shell",
    look: "the rounded corners of each user message; the bubble covers the rest.",
    kind: "color",
    set: { "--nyte-conversation-user-shell-bg": "var(--surface-page)" },
    source: "nds-surface-page",
    note: "v2 is opaque; v1 is the sidebar at 60%.",
  },
  {
    id: "user-bubble",
    pick: "v2",
    group: "Conversation",
    title: "User message",
    look: "user message bubbles, fill and ring.",
    kind: "color",
    set: {
      "--nyte-conversation-user-bg": "var(--surface-elevated)",
      "--nyte-conversation-user-ring": "var(--stroke-secondary)",
    },
    source: "nds-surface-elevated + stroke-secondary",
  },
  {
    id: "composer",
    pick: "v2",
    group: "Conversation",
    title: "Composer",
    look: "the composer fill and ring, and the open Agents tray.",
    kind: "color",
    set: {
      "--nyte-composer-bg": "var(--surface-elevated)",
      "--nyte-composer-ring": "var(--stroke-secondary)",
    },
    source: "nds-surface-elevated + stroke-secondary",
  },
  {
    id: "shadow-popover",
    pick: "v2",
    group: "Elevation",
    title: "Popover shadow",
    look: "Surface: Menu, Submenu, Popover, the model picker.",
    kind: "shadow",
    set: { "--nyte-shadow-popover": "var(--shadow-sm)" },
    source: "nds elevation-low = shadow-sm",
    note: "Calendar splits these: menus shadow-sm, pickers shadow-md.",
  },
  {
    id: "shadow-modal",
    pick: "v2",
    group: "Elevation",
    title: "Modal shadow",
    look: "Surface: Dialog.",
    kind: "shadow",
    set: { "--nyte-shadow-modal": "var(--shadow-lg)" },
    source: "nds elevation-high = shadow-lg",
  },
  {
    id: "floating-material",
    pick: "v2",
    group: "Elevation",
    title: "Floating material (menus, popovers, palette, dialogs)",
    look: "Surface: Menu, Popover or Dialog, and the model picker.",
    kind: "code",
    set: {},
    source: "nds-surface-elevated-wax + nds-wax-effect",
    note: "v2 blurs the page through; the floating surface needs backdrop-filter.",
    v1Text: "opaque bg-elevated (floating-surface.stylex.ts)",
    v2Text:
      "light rgba(255,255,255,.8) + blur(12px); dark rgba(32,32,32,.9) + blur(12px) brightness(120%); 1px stroke-secondary edge",
    previewCss: `
[role="menu"], [role="listbox"], [role="dialog"], [role="alertdialog"] {
  background-color: var(--material-fill) !important;
  -webkit-backdrop-filter: var(--material-effect) !important;
  backdrop-filter: var(--material-effect) !important;
  background-clip: var(--material-clip) !important;
}`,
  },
  {
    id: "font",
    pick: "v1",
    group: "Type",
    title: "Interface font",
    look: "every label; v2 is SF Pro on macOS.",
    kind: "font",
    set: { "--nyte-font-family-sans": calendarSans },
    source: "Calendar system stack",
  },
  {
    id: "line-height-base",
    pick: "v2",
    group: "Type",
    title: "Interface line height",
    look: "sidebar, menu and rail rows, dialog text and buttons; the transcript keeps its own.",
    kind: "length",
    set: { "--nyte-line-height-base": "18px" },
    source: "Calendar bodySm 13/18",
    note: "v1 derives 22px from 13px.",
  },
  {
    id: "titlebar-height",
    pick: "v1",
    group: "Geometry",
    title: "Titlebar height",
    look: "the titlebar and everything below it.",
    kind: "length",
    set: { "--nyte-titlebar-height": "44px" },
    source: "calendar.css",
    note: "At 44 the controls must be centred on the traffic lights (y 17), not the bar.",
  },
  {
    id: "sidebar-row-padding",
    pick: "v1",
    group: "Geometry",
    title: "Sidebar row padding",
    look: "each sidebar row's inset from the edge.",
    kind: "length",
    set: { "--nyte-sidebar-row-padding-inline": "8px" },
    source: "calendar.css",
  },
  {
    id: "sidebar-row-gap",
    pick: "v1",
    group: "Geometry",
    title: "Sidebar row gap",
    look: "the gap between icon and label in sidebar rows.",
    kind: "length",
    set: { "--nyte-sidebar-row-gap": "8px" },
    source: "calendar.css",
  },
  {
    id: "menu-radius",
    pick: "v2",
    group: "Geometry",
    title: "Menu radius",
    look: "the corners of Surface: Menu and Submenu.",
    kind: "length",
    set: { "--nyte-menu-radius": "10px" },
    source: "calendar.css",
    note: "The composer popover and the model picker keep 14.",
  },
  {
    id: "menu-item-radius",
    pick: "v2",
    group: "Geometry",
    title: "Menu row radius",
    look: "Surface: Menu, the checked rows' corners or any hovered row.",
    kind: "length",
    set: { "--nyte-menu-item-radius": "6px" },
    source: "calendar.css",
  },
  {
    id: "menu-item-height",
    pick: "v1",
    group: "Geometry",
    title: "Menu row height",
    look: "Surface: Menu, row pitch and menu height.",
    kind: "length",
    set: { "--nyte-menu-item-height": "30px" },
    source: "calendar.css",
    note: "The composer popover's rows have their own token.",
  },
  {
    id: "menu-item-padding",
    pick: "v2",
    group: "Geometry",
    title: "Menu row padding",
    look: "Surface: Menu, label inset and row height.",
    kind: "length",
    set: {
      "--nyte-menu-item-padding-inline": "6px",
      "--nyte-menu-item-padding-block": "5px",
    },
    source: "calendar.css",
  },
  {
    id: "menu-item-gap",
    pick: "v2",
    group: "Geometry",
    title: "Menu row gap",
    look: "Surface: Menu, the gap between icon and label.",
    kind: "length",
    set: { "--nyte-menu-item-gap": "6px" },
    source: "calendar.css",
  },
  {
    id: "dialog-radius",
    pick: "v2",
    group: "Geometry",
    title: "Dialog radius",
    look: "Surface: Dialog, the corners.",
    kind: "length",
    set: { "--nyte-dialog-radius": "12px" },
    source: "calendar.css",
  },
  {
    id: "dialog-padding",
    pick: "v2",
    group: "Geometry",
    title: "Dialog padding",
    look: "Surface: Dialog, the inset around title, text and buttons.",
    kind: "length",
    set: { "--nyte-dialog-padding": "24px" },
    source: "calendar.css",
  },
  {
    id: "button-box",
    pick: "v2",
    group: "Needs code",
    title: "Button box",
    look: "Cancel and Delete in Surface: Dialog, Commit and push in Workbench: Panel.",
    kind: "code",
    set: {},
    source: "Calendar Button (useStores)",
    note: "No preview: ui.tsx buttonBase writes literals.",
    v1Text: "28 tall · padding 10 · radius 8 · gap 6 · 13/500",
    v2Text: "30 tall (28 condensed) · padding 12 (8) · radius 6 · gap 4 · 13/18 medium",
  },
  {
    id: "button-secondary",
    pick: "v2",
    group: "Needs code",
    title: "Secondary button surface",
    look: "Cancel in Surface: Dialog.",
    kind: "code",
    set: {},
    source: "Calendar Button secondary",
    note: "No preview.",
    v1Text: "flat fillSecondary (base 4%)",
    v2Text: "linear-gradient(#FCFCFC, #F7F7F7) + inset 1px stroke-secondary + shadow-xs",
  },
  {
    id: "button-states",
    pick: "v2",
    group: "Needs code",
    title: "Button hover and pressed",
    look: "hover Delete in Surface: Dialog, or Send after typing.",
    kind: "code",
    set: {},
    source: "Calendar Button primary",
    note: "No preview.",
    v1Text: "a second fill colour (fill-primary-hover)",
    v2Text: "state-hover / state-pressed layered over the fill as a gradient",
  },
  {
    id: "focus-ring",
    pick: "v2",
    group: "Needs code",
    title: "Focus ring",
    look: "press Tab in the preview; rings only draw for keyboard focus.",
    kind: "code",
    set: {},
    source: "--highlight-focus",
    note: "No preview.",
    v1Text: "2px outline in the accent",
    v2Text: "box-shadow 0 0 0 1px uiBlue",
  },
  {
    id: "titlebar-controls",
    pick: "v2",
    group: "Needs code",
    title: "Titlebar control alignment",
    look: "the titlebar buttons against the traffic lights, clearest with Titlebar height on v2.",
    kind: "code",
    set: {},
    source: "Calendar sidebar controls (top 9.1, gap 4)",
    note: "No preview.",
    v1Text: "controls centred in the bar",
    v2Text: "controls centred on the traffic lights",
  },
  {
    id: "model-picker-radius",
    pick: "v2",
    group: "Needs code",
    title: "Model picker radii",
    look: "click the model chip in the composer and compare it with Surface: Menu.",
    kind: "code",
    set: {},
    source: "model-picker.tsx",
    note: "No preview.",
    v1Text: "palette radius 14, rows 8 (radius-2xl / radius-lg)",
    v2Text: "follow the menu: radius 10, rows 6",
  },
];

export const groups = [...new Set(decisions.map((decision) => decision.group))];
