import * as stylex from "@stylexjs/stylex";
import { t } from "@nyte-ai/ui/vars.stylex";

export const demoStyles = stylex.create({
  window: {
    display: "flex",
    flexDirection: "column",
    height: 680,
    marginInline: 32,
    marginBlockEnd: 40,
    borderRadius: t.radiusXl,
    backgroundColor: t.bgPage,
    boxShadow: `inset 0 0 0 1px ${t.strokeTertiary}`,
    overflow: "hidden",
    scrollMarginBlockStart: 24,
  },
  /** The shipping titlebar: 36px, the rail's colour under the traffic lights. */
  titlebar: { display: "flex", alignItems: "center", height: 36, flexShrink: 0 },
  lights: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: 220,
    height: "100%",
    paddingInline: 14,
    backgroundColor: t.bgSidebar,
    flexShrink: 0,
  },
  light: { width: 12, height: 12, borderRadius: t.radiusFull, backgroundColor: t.fillStrong },
  /** `titlebarStyles.sessionTitle`'s type; the crumbs ahead of it drop a tone. */
  crumbs: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
    paddingInline: 16,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  crumb: { display: "inline-flex", alignItems: "center", gap: 4, flexShrink: 0 },
  crumbDivider: { color: t.textQuaternary },
  crumbTitle: {
    minWidth: 0,
    overflow: "hidden",
    color: t.textSecondary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  body: { display: "flex", flex: 1, minHeight: 0 },
  main: {
    display: "flex",
    flex: 1,
    minWidth: 0,
    borderInlineStart: `1px solid ${t.strokeTertiary}`,
  },
  thread: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
  },
  transcript: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    flex: 1,
    width: "100%",
    maxWidth: 680,
    marginInline: "auto",
    paddingInline: 24,
    paddingBlock: 32,
    overflowY: "auto",
  },
  userTurn: { alignSelf: "flex-end", maxWidth: "80%" },
  reply: { color: t.textPrimary, fontSize: t.fontLg, lineHeight: t.leadingLg },
  step: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: t.textTertiary,
    fontSize: t.fontBase,
  },
  ask: { color: t.textWarning },
  failed: { color: t.textDanger },
  dock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    maxWidth: 680,
    marginInline: "auto",
    paddingInline: 24,
    paddingBlockEnd: 20,
  },
  composer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 52,
    paddingInlineStart: 14,
    paddingInlineEnd: 10,
    borderRadius: t.radius2xl,
    backgroundColor: t.composerBg,
    boxShadow: `0 0 0 1px ${t.composerRing}`,
    color: t.textTertiary,
  },
  composerDisabled: { opacity: 0.6 },
  send: {
    display: "grid",
    placeItems: "center",
    width: 28,
    height: 28,
    borderRadius: t.radiusFull,
    backgroundColor: t.fillStrong,
    color: t.iconSecondary,
  },
  notice: { paddingInline: 4, color: t.textTertiary, fontSize: t.fontSm, lineHeight: t.leadingSm },
});
