import { shape } from "@nyte-ai/ui/schema.stylex";
import { create } from "@stylexjs/stylex";
import { role, type } from "@nyte-ai/ui/vars.stylex";

export const demoStyles = create({
  window: {
    display: "flex",
    flexDirection: "column",
    height: 680,
    marginInline: 32,
    marginBlockEnd: 40,
    borderRadius: shape.card,
    backgroundColor: role.bgBase,
    boxShadow: `inset 0 0 0 1px ${role.borderSecondaryTranslucent}`,
    overflow: "hidden",
    scrollMarginBlockStart: 24,
  },
  /** The shipping titlebar: 36px, the rail's colour under the traffic lights. */
  titlebar: { display: "flex", alignItems: "center", height: 36, flexShrink: 0 },
  lights: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: 220,
    height: "100%",
    paddingInline: 14,
    backgroundColor: role.sidebarMaterial,
    flexShrink: 0,
  },
  light: {
    width: 12,
    height: 12,
    borderRadius: shape.pill,
    backgroundColor: role.bgInteractivePrimaryTranslucent,
  },
  /** `titlebarStyles.sessionTitle`'s type; the crumbs ahead of it drop a tone. */
  crumbs: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
    paddingInline: 16,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  crumb: { display: "inline-flex", alignItems: "center", gap: 4, flexShrink: 0 },
  crumbDivider: { color: role.contentDisabled },
  crumbTitle: {
    minWidth: 0,
    overflow: "hidden",
    color: role.contentSecondary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  body: { display: "flex", flex: 1, minHeight: 0 },
  main: {
    display: "flex",
    flex: 1,
    minWidth: 0,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: role.borderSecondaryTranslucent,
  },
  thread: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
  },
  transcript: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    flex: 1,
    width: "100%",
    maxWidth: 680,
    marginInline: "auto",
    paddingInline: 24,
    paddingBlock: 32,
    overflowY: "auto",
  },
  userTurn: { alignSelf: "flex-end", maxWidth: "80%" },
  reply: { color: role.contentPrimary, fontSize: type.fontLg, lineHeight: type.leadingLg },
  step: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: role.contentSecondary,
    fontSize: type.fontBase,
  },
  ask: { color: role.contentSecondary },
  failed: { color: role.contentSecondary },
  dock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    maxWidth: 680,
    marginInline: "auto",
    paddingInline: 24,
    paddingBlockEnd: 20,
  },
  composer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 52,
    paddingInlineStart: 14,
    paddingInlineEnd: 10,
    borderRadius: shape.surface,
    backgroundColor: role.bgElevated,
    boxShadow: `0 0 0 1px ${role.borderSecondaryTranslucent}`,
    color: role.contentTertiary,
  },
  composerDisabled: { opacity: 0.6 },
  send: {
    display: "grid",
    placeItems: "center",
    width: 28,
    height: 28,
    borderRadius: shape.pill,
    backgroundColor: role.bgInteractivePrimaryTranslucent,
    color: role.contentInteractiveSecondary,
  },
  notice: {
    paddingInline: 4,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
});
