import { create } from "@stylexjs/stylex";
import { input, layer, radius } from "@nyte-ai/ui/schema.stylex";
import { conversation, pane } from "../theme/schema.stylex.ts";
import { appearance, role, type } from "@nyte-ai/ui/vars.stylex";

export const threadStyles = create({
  stage: {
    display: "flex",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  panes: {
    position: "relative",
    display: "flex",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  splitRight: { flexDirection: "row" },
  splitDown: { flexDirection: "column" },
  pane: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    backgroundColor: role.bgBase,
  },
  paneSingle: { flex: 1 },
  paneLeading: (ratio: number) => ({
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: `calc((100% - ${pane.sashSize}) * ${String(ratio)})`,
  }),
  paneTrailing: { flex: 1 },
  screen: { display: "flex", flexDirection: "column", flex: 1, minHeight: 0 },
  embeddedScreen: {
    width: "100%",
    minWidth: 0,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: conversation.headerHeight,
    paddingInline: 12,
    flexShrink: 0,
  },
  title: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: type.fontBase,
    fontWeight: 600,
    color: role.contentPrimary,
  },
  headerActions: { display: "inline-flex", alignItems: "center", gap: 2, flexShrink: 0 },
  renameInput: {
    flex: 1,
    height: input.heightMd,
    borderRadius: radius.indicator,
    fontWeight: 600,
  },
  body: { position: "relative", display: "flex", flex: 1, minHeight: 0, minWidth: 0 },
  conversation: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0, minHeight: 0 },
  blank: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    minHeight: 0,
  },
  blankColumn: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "min(608px, calc(100% - 40px))",
  },
  greeting: { paddingInlineStart: 4, color: role.contentSecondary, fontSize: type.fontLg },
  blankHint: { paddingInlineStart: 4, color: role.contentSecondary, fontSize: type.fontBase },
  blankActions: { display: "flex", gap: 8, paddingInlineStart: 4 },
  error: { paddingInlineStart: 4, color: role.contentSecondary, fontSize: type.fontBase },
  sash: {
    position: "relative",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    zIndex: 4,
    touchAction: "none",
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 1,
    outlineColor: appearance.focusRing,
    outlineOffset: -1,
  },
  sashRight: { width: pane.sashSize, cursor: "col-resize" },
  sashDown: { height: pane.sashSize, cursor: "row-resize" },
  sashLine: { backgroundColor: role.borderSecondaryTranslucent, pointerEvents: "none" },
  sashLineRight: { width: 1, height: "100%" },
  sashLineDown: { width: "100%", height: 1 },
  dropPreviewLayer: {
    position: "absolute",
    inset: 2,
    zIndex: layer.dragPreview,
    overflow: "hidden",
    pointerEvents: "none",
  },
  dropPreview: {
    position: "absolute",
    borderRadius: radius.indicator,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: role.borderInteractivePrimary,
    backgroundColor: role.bgInteractiveSecondaryTranslucent,
    pointerEvents: "none",
  },
});
