// All user-facing chrome copy for the grok-bot demo. Per-agent copy (names, roles,
// descriptions, starter prompts) lives in demo-data.ts.
export const strings = {
  app: {
    name: "June",
  },
  sidebar: {
    newChat: "New chat",
    commands: "Commands",
    commandsShortcut: "⌘K",
    openCommands: "Open commands",
    resize: "Resize sidebar",
    botList: "Bots",
    noMessages: "No messages yet",
  },
  contextMenu: {
    open: "Open",
    newChat: "New chat",
    editAgent: "Edit agent",
  },
  account: {
    menuLabel: "Account",
    signedIn: "ChatGPT",
    signedOut: "Not signed in",
    signingIn: "Signing in…",
    notConnected: "ChatGPT not connected",
    signIn: "Sign in with ChatGPT",
    signInPending: "Waiting for browser…",
    appearance: "Appearance",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
  },
  onboarding: {
    welcomeTitle: "Welcome to June",
    welcomeBody: "A quiet home for small, focused agents. Connect ChatGPT to start a conversation.",
    connect: "Connect ChatGPT",
    connectPending: "Waiting for browser…",
    connectHint: "Sign-in opens in your browser and takes about a minute.",
    signInBrowserNotice: "Finish signing in in your browser.",
  },
  conversation: {
    opening: (name: string) => `Opening ${name}…`,
    conversationWith: (name: string) => `Conversation with ${name}`,
    viewDetails: (name: string) => `View ${name} details`,
    emptyHint: "Or write your own message below.",
    messagePlaceholder: (name: string) => `Message ${name}`,
    thinkingPlaceholder: (name: string) => `${name} is thinking…`,
    messageLabel: (name: string) => `Message ${name}`,
    send: "Send message",
    stop: "Stop response",
  },
  palette: {
    title: "Commands",
    description: "Open an agent, start a chat, or edit agent settings.",
    inputLabel: "Search commands",
    placeholder: "Type a command or agent",
    empty: "No commands found",
    newChat: "New chat",
    editAgent: "Edit agent",
    sectionAgents: "Agents",
    sectionActions: "Actions",
  },
  details: {
    title: "Agent settings",
    close: "Close agent settings",
    resize: "Resize agent settings",
    nameLabel: "Name",
    roleLabel: "Role",
    instructionsLabel: "Instructions",
    save: "Save changes",
    saving: "Saving…",
    saved: "Saved",
  },
} as const;
