/** Shared geometry and typography for the compact Settings surface. */
import * as stylex from "@stylexjs/stylex";
import { layer, settings } from "./schema.stylex.ts";
import { t } from "./vars.stylex.ts";

export const settingsPatterns = stylex.create({
  pageTitle: {
    margin: 0,
    color: t.textPrimary,
    fontSize: settings.pageTitleSize,
    fontWeight: 500,
    lineHeight: settings.pageTitleLineHeight,
    letterSpacing: 0,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: settings.cardGap,
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    alignSelf: "stretch",
    gap: 2,
    padding: "0 4px 0 8px",
  },
  sectionTitle: {
    margin: 0,
    color: t.textSecondary,
    fontSize: t.fontSm,
    fontWeight: 400,
    lineHeight: t.leadingSm,
  },
  sectionDescription: {
    margin: 0,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  group: {
    display: "flex",
    flexDirection: "column",
    overflow: "clip",
    borderRadius: t.radiusXl,
    backgroundColor: t.bgFaint,
  },
  row: {
    position: "relative",
    display: "flex",
    flexDirection: {
      default: "row",
      "@media (max-width: 500px)": "column",
      "@container (max-width: 500px)": "column",
    },
    flexWrap: "wrap",
    alignItems: "center",
    alignSelf: "stretch",
    gap: {
      default: 20,
      "@media (max-width: 500px)": 12,
      "@container (max-width: 500px)": 12,
    },
    minHeight: settings.rowMinHeight,
    padding: settings.rowPadding,
    "::before": {
      position: "absolute",
      insetInline: settings.rowPadding,
      insetBlockStart: 0,
      height: 1,
      backgroundColor: t.strokeQuaternary,
      content: '""',
    },
    ":first-child::before": { display: "none" },
  },
  rowSlider: { minHeight: settings.sliderRowMinHeight },
  rowDetailed: { rowGap: 8 },
  rowCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    width: {
      default: "auto",
      "@media (max-width: 500px)": "100%",
      "@container (max-width: 500px)": "100%",
    },
    minWidth: 0,
    maxWidth: "100%",
    overflow: "hidden",
    flex: {
      default: "1 1 0",
      "@media (max-width: 500px)": "0 0 auto",
      "@container (max-width: 500px)": "0 0 auto",
    },
  },
  rowTitle: {
    overflow: "hidden",
    color: t.textPrimary,
    fontSize: t.fontBase,
    fontWeight: 400,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    textOverflow: "ellipsis",
  },
  rowDescription: {
    color: t.textSecondary,
    fontSize: t.fontBase,
    fontWeight: 400,
    lineHeight: t.leadingBase,
    overflowWrap: "break-word",
  },
  rowControl: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: {
      default: "flex-end",
      "@media (max-width: 500px)": "flex-start",
      "@container (max-width: 500px)": "flex-start",
    },
    alignSelf: "stretch",
    width: {
      default: "auto",
      "@media (max-width: 500px)": "100%",
      "@container (max-width: 500px)": "100%",
    },
    minWidth: 0,
    maxWidth: {
      default: settings.controlMaxWidth,
      "@media (max-width: 500px)": "none",
      "@container (max-width: 500px)": "none",
    },
    flex: {
      default: "0 0 auto",
      "@media (max-width: 500px)": "1 1 100%",
      "@container (max-width: 500px)": "1 1 100%",
    },
  },
  rowControlWide: {
    maxWidth: {
      default: 280,
      "@media (max-width: 500px)": "none",
      "@container (max-width: 500px)": "none",
    },
  },
  rowDetail: {
    width: "100%",
    minWidth: 0,
    flex: "1 0 100%",
  },
  selectTrigger: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    boxSizing: "border-box",
    minWidth: 112,
    maxWidth: 180,
    height: settings.controlHeight,
    paddingBlock: 0,
    paddingInline: 8,
    overflow: "hidden",
    appearance: "none",
    borderRadius: t.radiusBase,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.borderDefault,
    backgroundColor: {
      default: t.fillSecondary,
      ":hover": t.fillSecondaryHover,
      "[data-popup-open]": t.fillSecondaryHover,
      "[data-disabled]": t.fillSecondary,
    },
    color: { default: t.textPrimary, "[data-disabled]": t.textDisabled },
    fontFamily: t.fontSans,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    cursor: { default: "pointer", "[data-disabled]": "default" },
    flexShrink: 0,
  },
  selectTriggerWide: { minWidth: 0, maxWidth: "100%" },
  selectValue: {
    display: "block",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    fontFamily: "inherit",
    lineHeight: t.leadingSm,
    textOverflow: "ellipsis",
    textAlign: "left",
    whiteSpace: "nowrap",
  },
  selectIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  selectPositioner: { zIndex: layer.menu, outline: "none" },
  selectPopup: {
    display: "flex",
    flexDirection: "column",
    minWidth: "var(--anchor-width)",
    maxWidth: "min(320px, var(--available-width))",
    maxHeight: "var(--available-height)",
    padding: 4,
    overflowY: "auto",
    overscrollBehavior: "contain",
    borderStyle: "none",
    borderRadius: t.radiusLg,
    outline: "none",
    backgroundColor: t.bgElevated,
    boxShadow: `${t.shadowPopover}, inset 0 0 0 1px ${t.strokeSecondary}, inset 0 0 0 1px ${t.bgElevated}`,
    color: t.textPrimary,
    transformOrigin: "var(--transform-origin)",
    opacity: { default: 1, "[data-starting-style]": 0, "[data-ending-style]": 0 },
    transform: {
      default: "none",
      "[data-starting-style][data-side='top']": "translate3d(0, 2px, 0) scale(0.98)",
      "[data-ending-style][data-side='top']": "translate3d(0, 2px, 0) scale(0.98)",
      "[data-starting-style][data-side='right']": "translate3d(-2px, 0, 0) scale(0.98)",
      "[data-ending-style][data-side='right']": "translate3d(-2px, 0, 0) scale(0.98)",
      "[data-starting-style][data-side='bottom']": "translate3d(0, -2px, 0) scale(0.98)",
      "[data-ending-style][data-side='bottom']": "translate3d(0, -2px, 0) scale(0.98)",
      "[data-starting-style][data-side='left']": "translate3d(2px, 0, 0) scale(0.98)",
      "[data-ending-style][data-side='left']": "translate3d(2px, 0, 0) scale(0.98)",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    transitionProperty: "opacity, transform",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  selectList: {
    display: "flex",
    flexDirection: "column",
    outline: "none",
  },
  selectItem: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    columnGap: 6,
    minHeight: 24,
    paddingBlock: 3,
    paddingInline: 4,
    borderRadius: t.radiusSm,
    outline: "none",
    backgroundColor: { default: "transparent", "[data-highlighted]": t.bgCard },
    color: { default: t.textPrimary, "[data-disabled]": t.textDisabled },
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    cursor: "default",
    userSelect: "none",
  },
  selectItemText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  selectItemIndicator: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 12,
    color: t.textSecondary,
  },
  fontSelectPopup: {
    width: "min(280px, var(--available-width))",
    minWidth: "min(280px, var(--available-width))",
    maxWidth: "min(280px, var(--available-width))",
    maxHeight: "min(320px, var(--available-height))",
    padding: 0,
    overflowY: "hidden",
  },
  fontSelectSearch: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    height: 36,
    paddingInline: 14,
    boxShadow: `inset 0 -1px 0 0 ${t.strokeQuaternary}`,
  },
  fontSelectSearchInput: {
    flex: 1,
    minWidth: 0,
    padding: 0,
    borderStyle: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontFamily: t.fontSans,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    "::placeholder": { color: t.textTertiary },
  },
  fontSelectList: {
    display: "flex",
    flexDirection: "column",
    flex: "0 1 auto",
    minHeight: 0,
    paddingBlock: 6,
    overflowY: "auto",
    overscrollBehavior: "contain",
    outline: "none",
  },
  fontSelectSeparator: {
    flexShrink: 0,
    height: 1,
    marginBlock: 4,
    backgroundColor: t.strokeQuaternary,
  },
  fontSelectGroupLabel: {
    paddingBlockStart: 6,
    paddingBlockEnd: 2,
    paddingInline: 14,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  fontSelectItem: {
    minHeight: 30,
    paddingBlock: 0,
    paddingInline: 14,
    borderRadius: t.radiusBase,
  },
  fontSelectEmpty: {
    flexShrink: 0,
    padding: "10px 14px",
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  switchTrack: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    width: 32,
    height: 20,
    padding: 2,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    backgroundColor: t.bgActive,
    transitionProperty: "background-color",
    transitionDuration: t.durationFast,
    transitionTimingFunction: t.easeOut,
    cursor: "pointer",
  },
  switchTrackOn: { backgroundColor: t.switchActive },
  switchTrackDisabled: { opacity: 0.5, cursor: "default" },
  switchThumb: {
    display: "block",
    width: 16,
    height: 16,
    borderRadius: t.radiusFull,
    backgroundColor: t.switchThumb,
    boxShadow: `0 1px 2px ${t.shadowControlColor}`,
    transform: "translateX(0)",
    transitionProperty: "transform",
    transitionDuration: t.durationSlow,
    transitionTimingFunction: t.easeInOutStrong,
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0s" },
  },
  switchThumbOn: { transform: "translateX(12px)" },
  stepper: {
    display: "grid",
    gridTemplateColumns: "26px 42px 26px",
    boxSizing: "border-box",
    width: "max-content",
    height: settings.controlHeight,
    overflow: "hidden",
    borderRadius: t.radiusBase,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.borderDefault,
    backgroundColor: t.fillSecondary,
    outlineStyle: { default: "none", ":focus-within": "solid" },
    outlineWidth: 2,
    outlineColor: t.focusRing,
    outlineOffset: 1,
  },
  stepperSplit: {
    boxShadow: `inset -1px 0 0 0 ${t.borderWeak}`,
  },
  stepperButton: {
    display: "grid",
    placeItems: "center",
    padding: 0,
    borderStyle: "none",
    outlineStyle: "none",
    backgroundColor: { default: "transparent", ":hover:not(:disabled)": t.fillGhostHover },
    color: t.textTertiary,
    fontSize: t.fontLg,
    lineHeight: t.leadingBase,
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { ":disabled": 0.35 },
  },
  stepperValue: {
    width: "100%",
    minWidth: 0,
    padding: 0,
    borderStyle: "none",
    borderRadius: 0,
    outlineStyle: "none",
    backgroundColor: "transparent",
    color: t.textSecondary,
    fontFamily: "inherit",
    fontSize: t.fontSm,
    fontVariantNumeric: "tabular-nums",
    lineHeight: t.leadingSm,
    textAlign: "center",
    // Global ::selection mixes --nyte-accent and would tint the value.
    "::selection": {
      backgroundColor: t.bgSelection,
      color: t.textSecondary,
    },
  },
  // Numbers inside settings copy: fixed-width digits so counts don't jitter.
  numeral: { fontVariantNumeric: "tabular-nums" },
});
