import { defineConsts } from "@stylexjs/stylex";

export const space = defineConsts({
  step1: "var(--lab-unit)",
  step2: "calc(var(--lab-unit) * 2)",
  step3: "calc(var(--lab-unit) * 3)",
  step4: "calc(var(--lab-unit) * 4)",
  step5: "calc(var(--lab-unit) * 5)",
  step6: "calc(var(--lab-unit) * 6)",
  step8: "calc(var(--lab-unit) * 8)",
  insetMenu: "var(--lab-unit)",
  insetDialog: "calc(var(--lab-unit) * 6)",
  insetShell: "var(--lab-shell-inset)",
  insetRail: "var(--lab-rail-inset)",
  insetShellRowStart: "var(--lab-row-start)",
  insetShellRowEnd: "var(--lab-row-end)",
  insetShellHeading: "var(--lab-heading-inset)",
  insetViewport: "calc(var(--lab-unit) * 2)",
  insetRow: "calc(var(--lab-unit) * 2)",
  insetButton: "calc(var(--lab-unit) * 3)",
  slotLeading: "var(--lab-menu-icon-slot)",
  slotTrailing: "var(--lab-glyph)",
  slotIcon: "var(--lab-glyph, 16px)",
  gapRow: "var(--lab-menu-gap)",
  slotShellLeading: "var(--lab-row-icon)",
  slotShellTrailing: "var(--lab-glyph)",
  gapShellRow: "var(--lab-row-gap)",
  insetLabel: "var(--lab-menu-label-start)",
  rowMenu: "max(30px, var(--lab-row-height))",
  rowButton: "max(30px, var(--lab-row-height))",
  rowShell: "var(--lab-row-height)",
  gapTight: "var(--lab-unit)",
  gapContent: "calc(var(--lab-unit) * 2)",
  gapBlock: "calc(var(--lab-unit) * 3)",
  gapShellSection: "var(--lab-section-gap)",
  submenuOffsetInline: "var(--lab-unit)",
  submenuOffsetBlock: "calc(var(--lab-unit) * -1)",
  widthMenuMin: "200px",
  widthMenuMax: "480px",
  widthDialog: "420px",
  widthRail: "var(--lab-rail-width)",
});
