/**
 * Conversation presentation has one StyleX owner. Renderers keep behavior and
 * semantics; this module keeps the shared hierarchy, geometry, and states
 * coherent across prose, tools, diffs, reasoning, and the composer.
 *
 * Based on https://github.com/b-nnett/grok-bot-0.18-reconstructed/blob/a9f633e09d49a85829b8236331b9e21f7e612634/frontend/src/recovered/features/conversation/workspace/view.css
 */
import * as stylex from "@stylexjs/stylex";
import { conversation, diffView, layer } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

const caretBlink = stylex.keyframes({
  "0%, 49%": { opacity: 1 },
  "50%, 100%": { opacity: 0 },
});

const activityShine = stylex.keyframes({
  "0%": { backgroundPosition: "200% 0" },
  "100%": { backgroundPosition: "-200% 0" },
});

const ACTIVITY_SHIMMER = `linear-gradient(90deg, ${t.shimmerBase} 0%, ${t.shimmerBase} 28%, ${t.shimmerHighlight} 58%, ${t.shimmerBase} 76%, ${t.shimmerBase} 100%)`;
const CODE_RING = `inset 0 0 0 1px ${t.conversationTechnicalRing}`;
const COMPOSER_RING_DROP = `0 0 0 2px ${t.fillAccentSubtle}`;

export const proseStyles = stylex.create({
  root: {
    display: "flow-root",
    width: "100%",
    minWidth: 0,
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  measure: { width: "100%", maxWidth: conversation.proseMeasure },
  paragraph: {
    marginInline: 0,
    marginBlockStart: {
      default: 16,
      ":is(h1 + p, h2 + p, h3 + p, h4 + p, h5 + p, h6 + p)": 4,
      ":is(li > p)": 0,
      ":first-child": 0,
    },
    marginBlockEnd: {
      default: 16,
      ":has(+ ul, + ol)": 8,
      ":has(+ figure, + blockquote, + [data-prose-table])": 12,
      ":is(li > p)": 0,
      ":last-child": 0,
    },
    whiteSpace: "normal",
  },
  heading: {
    marginInline: 0,
    marginBlockStart: { default: t.leadingLg, ":first-child": 0 },
    marginBlockEnd: { default: 4, ":last-child": 0 },
    fontWeight: 590,
    lineHeight: 1.42,
    textWrap: "balance",
  },
  h1: { fontSize: "1.214em" },
  h2: { fontSize: "1.214em" },
  h3: { fontSize: "1.133em" },
  h4: { fontSize: "1em", marginBlockStart: { default: 12, ":first-child": 0 } },
  h5: { fontSize: "0.866em", color: t.textSecondary },
  h6: { fontSize: "0.8em", color: t.textSecondary },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginInline: 0,
    marginBlockStart: { default: 8, ":is(li > ul, li > ol)": 4, ":first-child": 0 },
    marginBlockEnd: { default: 18, ":last-child": 0 },
    paddingInlineStart: "2em",
  },
  listItem: { whiteSpace: "normal" },
  strong: { color: t.textPrimary, fontWeight: 590 },
  inlineCode: {
    paddingInline: { default: 2, ":is(a code)": 0 },
    paddingBlock: { default: 1.5, ":is(a code)": 0 },
    borderRadius: { default: 5, ":is(a code)": 0 },
    backgroundColor: { default: t.bgHover, ":is(a code)": "transparent" },
    color: "inherit",
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    letterSpacing: "normal",
    lineHeight: "inherit",
    boxDecorationBreak: "clone",
  },
  link: {
    color: t.textAccent,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillAccentSubtle },
    },
    marginInline: -2,
    padding: 2,
    borderRadius: 4,
    fontWeight: 500,
    textDecorationLine: { default: "none", ":hover": "underline" },
    textDecorationThickness: "from-font",
    textUnderlineOffset: 2,
    boxDecorationBreak: "clone",
    cursor: "pointer",
  },
  blockquote: {
    marginInline: 0,
    marginBlockStart: { default: 12, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    paddingInlineStart: 12,
    borderInlineStartWidth: 2,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.borderDefault,
    color: t.textSecondary,
  },
  rule: {
    width: "100%",
    maxWidth: conversation.proseMeasure,
    height: 1,
    marginBlock: 8,
    borderStyle: "none",
    backgroundColor: t.strokeTertiary,
  },
  tableWrap: {
    marginBlockStart: { default: 12, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    width: "100%",
    maxWidth: "100%",
    overflowX: "auto",
    // Horizontal tables must not trap vertical scrolling of the conversation.
    overscrollBehaviorY: "auto",
    borderRadius: t.radiusLg,
    boxShadow: CODE_RING,
  },
  table: {
    width: "max-content",
    minWidth: "100%",
    borderCollapse: "collapse",
    fontSize: t.fontBase,
    fontVariantNumeric: "tabular-nums",
  },
  cell: {
    paddingBlock: 4,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.conversationTechnicalRing,
    textAlign: "left",
    verticalAlign: "top",
  },
  headerCell: { backgroundColor: t.conversationTechnicalBg, fontWeight: 600 },
  fallbackPre: {
    width: "100%",
    margin: 0,
    padding: "11px 12px",
    overflowX: "auto",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    whiteSpace: "pre",
  },
  imageLabel: { color: t.textTertiary },
});

export const inlineTextStyles = stylex.create({
  skill: {
    display: "inline",
    color: t.textWarning,
    fontSize: "inherit",
    fontWeight: 400,
    lineHeight: "inherit",
  },
});

export const codeBlockStyles = stylex.create({
  figure: {
    position: "relative",
    marginBlock: 10,
    marginInline: 0,
    overflow: "hidden",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
    paddingInlineStart: 11,
    paddingInlineEnd: 5,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.conversationTechnicalRing,
  },
  scroll: { maxWidth: "100%", overflowX: "auto" },
  pre: {
    margin: 0,
    padding: "11px 12px",
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    userSelect: "text",
  },
  language: {
    flex: 1,
    minWidth: 0,
    color: t.textTertiary,
    fontFamily: t.fontMono,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
    userSelect: "none",
  },
  copy: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    color: t.iconTertiary,
    cursor: "pointer",
  },
});

export const composerStyles = stylex.create({
  region: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: `min(${conversation.measure}, 100%)`,
    marginInline: "auto",
    paddingInline: conversation.gutter,
    paddingTop: 8,
    paddingBottom: conversation.composerInset,
  },
  queued: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 30,
    paddingInline: 10,
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textSecondary,
    fontSize: t.fontSm,
  },
  queuedText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  queuedState: {
    flexShrink: 0,
    color: t.textTertiary,
  },
  queuedAction: {
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textAccent,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    fontSize: t.fontSm,
    cursor: "pointer",
    flexShrink: 0,
  },
  frame: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: t.composerRing,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.composerRingActive },
      ":focus-within": t.composerRingActive,
    },
    backgroundColor: t.composerBg,
    boxShadow: "none",
    transitionProperty: "border-color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  frameNewChat: {
    gap: 6,
    minHeight: 106,
    padding: "10px 12px 8px",
    borderRadius: conversation.composerNewChatRadius,
  },
  frameFollowUpCompact: {
    gap: 6,
    minHeight: 40,
    padding: "5px 8px 5px 10px",
    borderRadius: t.radiusFull,
  },
  frameFollowUpExpanded: { borderRadius: conversation.composerExpandedRadius },
  frameDragging: {
    borderColor: t.composerRingActive,
    boxShadow: COMPOSER_RING_DROP,
  },
  dropGuard: {
    position: "absolute",
    zIndex: 10,
    inset: 0,
    borderRadius: "inherit",
  },
  fileInput: { display: "none" },
  attachments: {
    display: "flex",
    gap: 6,
    width: "100%",
    margin: 0,
    padding: 0,
    listStyle: "none",
    paddingInlineEnd: 24,
    overflowX: "auto",
    scrollPaddingInline: 24,
  },
  attachmentsInset: { width: "auto", marginBlockStart: 8, marginInline: 12 },
  attachment: {
    position: "relative",
    display: "flex",
    flexShrink: 0,
    borderRadius: t.radiusBase,
    backgroundColor: t.imageBg,
  },
  attachmentRemove: {
    position: "absolute",
    top: 3,
    right: 3,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 24,
    height: 24,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    backgroundColor: t.imageBg,
    boxShadow: `0 1px 3px rgba(0, 0, 0, 0.2), inset 0 0 0 1px ${t.imageOutline}`,
    color: { default: t.iconSecondary, ":hover:not(:disabled)": t.iconPrimary },
    cursor: { default: "pointer", ":disabled": "default" },
  },
  attachmentError: {
    color: t.textDanger,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  attachmentErrorInset: { marginBlockStart: 6, marginInline: 12 },
  input: {
    display: "block",
    boxSizing: "border-box",
    width: "100%",
    minWidth: 80,
    flex: 1,
    minHeight: t.leadingLg,
    maxHeight: 200,
    overflowY: "auto",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    caretColor: { default: t.textPrimary, "[data-custom-caret='true']": "transparent" },
    "[data-empty='true']::before": {
      content: "attr(data-placeholder)",
      position: "absolute",
      color: t.textTertiary,
      pointerEvents: "none",
    },
    margin: 0,
    padding: 0,
    resize: "none",
    borderStyle: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    "::placeholder": { color: t.textTertiary },
  },
  editorHost: { position: "relative", flex: 1, minWidth: 64 },
  editorParagraph: { margin: 0 },
  editorCaret: {
    position: "absolute",
    insetBlockStart: 0,
    insetInlineStart: 0,
    width: 1.5,
    borderRadius: 1,
    backgroundColor: t.textPrimary,
    pointerEvents: "none",
    animationName: { default: caretBlink, "@media (prefers-reduced-motion: reduce)": "none" },
    animationDuration: "1.1s",
    animationTimingFunction: "step-end",
    animationIterationCount: "infinite",
  },
  fileChip: {
    paddingInline: 4,
    paddingBlock: 1,
    borderRadius: 6,
    backgroundColor: t.fillSecondary,
    verticalAlign: "baseline",
    maxWidth: "min(240px, 100%)",
    fontSize: "inherit",
    lineHeight: "inherit",
  },
  fileChipLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  inputNewChat: { minHeight: 54, maxHeight: 340 },
  inputCompact: { minHeight: 24, minWidth: 64 },
  editor: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    columnGap: 4,
    width: "100%",
    minWidth: 0,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
  },
  editorCompact: { gridColumn: 2, gridRow: 1, minWidth: 64 },
  editorExpanded: { minHeight: 54, paddingBlock: 8, paddingInline: 12 },
  mentionChip: {
    "--_mention-leading-opacity": {
      default: "1",
      ":hover": "0",
      ":focus-within": "0",
    },
    "--_mention-remove-opacity": {
      default: "0",
      ":hover": "1",
      ":focus-within": "1",
    },
    "--_mention-remove-events": {
      default: "none",
      ":hover": "auto",
      ":focus-within": "auto",
    },
    position: "relative",
    display: "inline-flex",
    alignItems: "baseline",
    padding: 0,
    borderStyle: "none",
    borderRadius: 0,
    backgroundColor: "transparent",
    color: t.textCyan,
    fontSize: t.fontLg,
    fontWeight: 400,
    lineHeight: t.leadingLg,
    whiteSpace: "nowrap",
  },
  mentionChipLeading: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    width: 12,
    height: 14,
    marginInlineEnd: 4,
    opacity: "var(--_mention-leading-opacity)",
    transitionProperty: "opacity",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease",
  },
  mentionChipRemove: {
    position: "absolute",
    insetInlineStart: 0,
    top: "50%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 14,
    height: 14,
    padding: 0,
    transform: "translateY(-50%)",
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "inherit",
    lineHeight: 1,
    opacity: "var(--_mention-remove-opacity)",
    pointerEvents: "var(--_mention-remove-events)",
    cursor: "pointer",
    transitionProperty: "opacity",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease",
  },
  layout: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  layoutNewChat: { gap: 6 },
  layoutCompact: {
    display: "grid",
    gridTemplateColumns: "28px minmax(64px, 1fr) minmax(0, auto) 28px",
    alignItems: "center",
    gap: 8,
  },
  controls: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
  },
  controlsInset: { paddingInline: 8, paddingBlockEnd: 8 },
  controlsCompact: { display: "contents" },
  controlHitArea: {
    position: "relative",
    "::after": {
      content: '""',
      position: "absolute",
      inset: { default: -6, "@media (pointer: coarse)": -8 },
      borderRadius: "inherit",
    },
  },
  addButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    backgroundColor: {
      default: t.fillSecondary,
      ":hover:not(:disabled)": t.fillSecondaryHover,
    },
    color: t.iconSecondary,
    cursor: { default: "pointer", ":disabled": "default" },
  },
  addButtonCompact: { gridColumn: 1, gridRow: 1 },
  addMenu: { width: 260, maxWidth: "calc(100vw - 24px)" },
  modelSlot: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  modelSlotCompact: {
    gridColumn: 3,
    gridRow: 1,
    minWidth: 0,
    maxWidth: 220,
  },
  // Same line height as the model trigger so the digits share its baseline.
  gauge: {
    color: t.textTertiary,
    fontSize: t.fontXs,
    lineHeight: t.leadingBase,
    fontVariantNumeric: "tabular-nums",
  },
  spacer: { flex: 1 },
  spacerCompact: { display: "none" },
  suggestionPositioner: {
    zIndex: layer.menu,
    borderRadius: t.radiusXl,
    boxShadow: "none",
    outline: "none",
  },
  suggestionMenu: {
    display: "flex",
    flexDirection: "column",
    width: "min(var(--anchor-width), calc(100dvw - 16px))",
    maxWidth: "min(var(--anchor-width), calc(100dvw - 16px))",
    maxHeight: "min(280px, var(--available-height))",
    paddingBlock: 6,
    paddingInline: 6,
    borderStyle: "none",
    borderRadius: t.radiusXl,
    outline: "none",
    color: t.textPrimary,
    // The frame clips and carries the inset hairline; the list inside scrolls.
    // An absolutely positioned hairline on a scroll container would travel
    // with the content.
    overflow: "hidden",
    transformOrigin: "var(--transform-origin)",
  },
  suggestionList: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarWidth: "none",
    "::-webkit-scrollbar": { display: "none" },
  },
  suggestionItem: {
    "--_suggestion-icon-color": {
      default: t.iconTertiary,
      ":hover": t.iconSecondary,
      "[aria-selected='true']": t.iconSecondary,
    },
    display: "grid",
    gridTemplateColumns: "12px minmax(0, 1fr) auto",
    boxSizing: "border-box",
    alignItems: "center",
    columnGap: 8,
    minHeight: 28,
    marginBlockEnd: 1,
    paddingBlock: 4,
    paddingInline: 8,
    borderRadius: t.radiusBase,
    outline: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": t.bgSelection,
      "[aria-selected='true']": t.bgSelection,
    },
    color: {
      default: t.textSecondary,
      ":hover": t.textPrimary,
      "[aria-selected='true']": t.textPrimary,
    },
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    cursor: "pointer",
    userSelect: "none",
  },
  suggestionIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 12,
    color: "var(--_suggestion-icon-color)",
  },
  suggestionText: {
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    gap: 8,
    overflow: "hidden",
  },
  suggestionLabel: {
    minWidth: 0,
    flexShrink: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionDescription: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionMatch: { color: t.textCyan, fontWeight: "inherit" },
  suggestionShortcut: {
    minWidth: 0,
    paddingInlineStart: 8,
    overflow: "hidden",
    color: t.textTertiary,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionDivider: {
    height: 8,
    marginInline: 6,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: t.strokeTertiary,
    transform: "translateY(4px)",
  },
  suggestionEmpty: {
    minHeight: 28,
    display: "flex",
    alignItems: "center",
    paddingInline: 8,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  suggestionPreviewPositioner: {
    zIndex: layer.submenu,
    borderRadius: t.radiusXl,
    outline: "none",
  },
  suggestionPreview: {
    display: "flex",
    flexDirection: "column",
    width: 280,
    maxWidth: "min(280px, var(--available-width))",
    maxHeight: "min(300px, var(--available-height))",
    padding: 10,
    borderStyle: "none",
    borderRadius: t.radiusXl,
    outline: "none",
    color: t.textPrimary,
    overflowY: "auto",
  },
  suggestionPreviewTitle: {
    color: t.textPrimary,
    fontSize: t.fontBase,
    fontWeight: 500,
    lineHeight: t.leadingBase,
  },
  suggestionPreviewAttribution: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    marginBlockStart: 6,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  suggestionPreviewIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 14,
    height: 14,
    color: t.iconTertiary,
  },
  suggestionPreviewDescription: {
    marginBlockStart: 8,
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  send: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    flexShrink: 0,
    cursor: { default: "pointer", ":disabled": "default" },
    color: t.textOnPrimary,
    backgroundColor: {
      default: t.fillPrimary,
      ":hover:not(:disabled)": t.fillPrimaryHover,
      ":disabled": t.fillPrimaryDisabled,
    },
    transitionProperty: "background-color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  sendCompact: { gridColumn: 4, gridRow: 1 },
  stop: {
    color: t.textPrimary,
    backgroundColor: {
      default: t.fillSecondary,
      ":hover:not(:disabled)": t.fillSecondaryHover,
    },
  },
  quickActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    paddingInlineStart: 4,
  },
  quickAction: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    height: 26,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.borderWeak,
    borderRadius: t.radiusFull,
    backgroundColor: {
      default: "transparent",
      ":hover:not(:disabled)": {
        "@media (hover: hover) and (pointer: fine)": t.fillGhostHover,
      },
    },
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { ":disabled": 0.5 },
    whiteSpace: "nowrap",
  },
  quickActionMeta: { color: t.textTertiary, fontSize: t.fontXs },
});

export const diffStyles = stylex.create({
  surface: {
    boxSizing: "border-box",
    minWidth: 0,
    overflow: "hidden",
    borderRadius: t.radiusBase,
    backgroundColor: t.conversationTechnicalBg,
  },
  inline: {
    marginTop: 4,
    marginBottom: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
  },
  workbench: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100%",
    margin: 0,
    borderRadius: t.radiusLg,
    boxShadow: CODE_RING,
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 30,
    paddingInline: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.conversationTechnicalRing,
    flexShrink: 0,
  },
  path: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: t.fontCode,
    fontVariantNumeric: "tabular-nums",
  },
  added: { color: t.textSuccess },
  removed: { color: t.textDanger },
  body: { minWidth: 0, overflow: "auto" },
  bodyInline: { maxHeight: diffView.previewMaxHeight },
  bodyWorkbench: { flex: 1, minHeight: 0, maxHeight: "none" },
});

export const pierrePatchStyles = stylex.create({
  host: { display: "block", width: "100%", minWidth: 0, maxWidth: "100%" },
});

export const activityStyles = stylex.create({
  shimmer: {
    animationName: {
      default: activityShine,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: {
      default: "2.4s",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    backgroundImage: {
      default: ACTIVITY_SHIMMER,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundSize: "200% 100%",
    backgroundClip: "text",
    color: {
      default: "transparent",
      "@media (prefers-reduced-motion: reduce)": t.textTertiary,
    },
  },
});

export const toolCallStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", minWidth: 0 },
  line: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    width: "fit-content",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: 24,
    paddingInline: 0,
    overflow: "hidden",
    borderStyle: "none",
    backgroundColor: "transparent",
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    textAlign: "left",
    whiteSpace: "nowrap",
    cursor: "pointer",
    userSelect: "none",
    "--_verb-color": {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    "--_detail-color": {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
  },
  editLine: { minHeight: 30 },
  lineStatic: { cursor: "default" },
  lineDetailed: {
    width: "100%",
    minHeight: 32,
    paddingInline: 9,
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
  },
  failed: { "--_verb-color": t.textDanger, "--_detail-color": t.textDanger },
  verb: {
    flexShrink: 0,
    color: "var(--_verb-color)",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  detail: {
    minWidth: 0,
    overflow: "hidden",
    color: "var(--_detail-color)",
    fontFamily: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: "inherit",
    lineHeight: "inherit",
    fontVariantNumeric: "tabular-nums",
  },
  editStats: { marginInlineStart: 4 },
  added: { color: t.textSuccess },
  removed: { color: t.textDanger },
  chevron: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 16,
    height: 16,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease-in-out",
  },
  chevronOpen: { transform: "rotate(90deg)" },
  output: {
    maxHeight: 260,
    marginTop: 6,
    marginBottom: 4,
    padding: "8px 12px",
    overflowY: "auto",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
});

export const toolGroupStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", minWidth: 0 },
  toggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    width: "fit-content",
    maxWidth: "100%",
    minHeight: conversation.rowMinHeight,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    textAlign: "left",
    cursor: "pointer",
    userSelect: "none",
  },
  failed: { color: t.textDanger },
  verb: { flexShrink: 0 },
  summary: {
    minWidth: 0,
    overflow: "hidden",
    color: t.textTertiary,
    fontSize: "inherit",
    lineHeight: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: "inherit",
    lineHeight: "inherit",
    fontVariantNumeric: "tabular-nums",
  },
  added: { color: t.textSuccess },
  removed: { color: t.textDanger },
  chevron: {
    display: "inline-flex",
    flexShrink: 0,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  chevronOpen: { transform: "rotate(90deg)" },
  calls: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
    marginBlockStart: 4,
    paddingBlock: 2,
    paddingInlineStart: 16,
  },
  // Cursor's compact streaming window: about six conversation rows.
  preview: {
    boxSizing: "border-box",
    maxHeight: 144,
    marginBlockStart: 4,
    paddingBlockStart: 6,
    overflowX: "hidden",
    overflowY: "auto",
    cursor: "pointer",
    overscrollBehavior: "auto",
  },
  previewFade: {
    maskImage: "linear-gradient(to bottom, rgba(0, 0, 0, 0.15) 0px, black 32px)",
  },
  previewCalls: { marginBlockStart: 0 },
  commentary: { minWidth: 0 },
  commentaryDim: { color: t.textTertiary },
  thinking: { minWidth: 0, opacity: 0.68 },
});

export const turnStyles = stylex.create({
  turn: {
    display: "flex",
    flexDirection: "column",
    gap: conversation.rowGap,
    width: "100%",
    minWidth: 0,
  },
  userRow: {
    position: { default: "sticky", "[data-sticky-disabled='true']": "relative" },
    zIndex: { default: layer.stickyContent, "[data-sticky-disabled='true']": "auto" },
    top: 0,
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    paddingTop: 10,
    marginBottom: 4,
    backgroundColor: t.bgBase,
  },
  userPromptShell: {
    position: "relative",
    width: "100%",
    minWidth: 0,
    borderRadius: t.radiusXl,
    backgroundColor: t.conversationUserShellBg,
  },
  userFade: {
    position: "absolute",
    top: "100%",
    insetInline: 0,
    height: 20,
    opacity: { default: 0, "[data-sticky-visible='true']": 1 },
    backgroundColor: t.bgBase,
    maskImage: "linear-gradient(to bottom, black, transparent)",
    pointerEvents: "none",
    transitionProperty: "opacity",
    transitionDuration: {
      default: t.durationSlow,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease-in-out",
  },
  userPrompt: {
    boxSizing: "border-box",
    display: "block",
    width: "100%",
    minWidth: 0,
    paddingBlock: 8,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.conversationUserRing,
    borderRadius: t.radiusXl,
    backgroundColor: t.conversationUserBg,
    boxShadow: "none",
    color: t.textPrimary,
    fontFamily: "inherit",
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
    textAlign: "start",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
    transitionProperty: "background-color, border-color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  userImages: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    padding: 10,
  },
  userPromptEditable: {
    backgroundColor: {
      default: t.conversationUserBg,
      ":hover": {
        "@media (hover: hover) and (pointer: fine)": t.conversationUserBgHover,
      },
    },
    borderColor: {
      default: t.conversationUserRing,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.strokePrimary },
    },
    cursor: "text",
    outlineStyle: "none",
  },
  userEdit: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 5,
    width: "100%",
    minWidth: 0,
    minHeight: 40,
    paddingBlock: 8,
    paddingInlineStart: 10,
    paddingInlineEnd: 7,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.composerRingActive,
    borderRadius: t.radiusXl,
    backgroundColor: t.conversationUserBg,
    boxShadow: "none",
  },
  userEditInput: {
    boxSizing: "border-box",
    width: "100%",
    height: t.leadingLg,
    minWidth: 0,
    minHeight: t.leadingLg,
    maxHeight: 180,
    margin: 0,
    padding: 0,
    resize: "none",
    borderStyle: "none",
    outlineStyle: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontFamily: "inherit",
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
    overflowY: "auto",
    overflowWrap: "anywhere",
  },
  userEditFooter: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    minWidth: 0,
    minHeight: 24,
  },
  userEditActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 5,
    minWidth: 0,
    minHeight: 22,
    marginInlineStart: "auto",
    padding: 0,
  },
  userEditError: {
    minWidth: 0,
    maxWidth: 260,
    paddingInlineStart: 4,
    overflow: "hidden",
    color: t.textDanger,
    fontSize: t.fontXs,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userEditCancel: {
    minHeight: 22,
    paddingInline: 6,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    backgroundColor: { default: "transparent", ":hover:not(:disabled)": t.fillGhostHover },
    color: t.textSecondary,
    cursor: { default: "pointer", ":disabled": "default" },
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
  },
  userEditSubmit: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 24,
    height: 24,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    backgroundColor: {
      default: t.fillPrimary,
      ":hover:not(:disabled)": t.fillPrimaryHover,
      ":disabled": t.fillPrimaryDisabled,
    },
    color: t.textOnPrimary,
    cursor: { default: "pointer", ":disabled": "default" },
  },
  reasoning: { display: "flex", flexDirection: "column", width: "100%", minWidth: 0 },
  reasoningToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    width: "fit-content",
    minHeight: conversation.rowMinHeight,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    cursor: "pointer",
    userSelect: "none",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  reasoningChevron: {
    display: "inline-flex",
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  reasoningChevronOpen: { transform: "rotate(90deg)" },
  reasoningBody: {
    boxSizing: "border-box",
    width: "100%",
    maxWidth: conversation.proseMeasure,
    marginTop: 4,
    paddingBlock: 2,
    paddingInlineStart: 16,
    opacity: 0.68,
  },
  notice: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: conversation.rowMinHeight,
    paddingBlock: 2,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  noticeError: {
    color: t.textDanger,
  },
  event: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    width: "fit-content",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: conversation.rowMinHeight,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    userSelect: "text",
  },
  history: { display: "flex", flexDirection: "column", minWidth: 0 },
  historyToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    width: "fit-content",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: conversation.rowMinHeight,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    cursor: "pointer",
    userSelect: "none",
  },
  historyChevron: {
    display: "inline-flex",
    flexShrink: 0,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  historyChevronOpen: { transform: "rotate(90deg)" },
  historyBody: {
    boxSizing: "border-box",
    width: "100%",
    marginTop: 4,
    paddingBlock: 2,
    paddingInlineStart: 14,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.conversationGuide,
    opacity: 0.68,
  },
});
