/**
 * Conversation presentation has one StyleX owner. Renderers keep behavior and
 * semantics; this module keeps the shared hierarchy, geometry, and states
 * coherent across prose, tools, diffs, reasoning, and the composer.
 *
 * Based on https://github.com/b-nnett/grok-bot-0.18-reconstructed/blob/a9f633e09d49a85829b8236331b9e21f7e612634/frontend/src/recovered/features/conversation/workspace/view.css
 */
import * as stylex from "@stylexjs/stylex";
import { conversation, diffView, layer, pane, tray } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

const caretBlink = stylex.keyframes({
  "0%, 49%": { opacity: 1 },
  "50%, 100%": { opacity: 0 },
});

const activityShine = stylex.keyframes({
  "0%": { backgroundPosition: "200% 0" },
  "100%": { backgroundPosition: "-200% 0" },
});

const ACTIVITY_SHIMMER = `linear-gradient(90deg, ${t.shimmerBase} 0%, ${t.shimmerBase} 28%, ${t.shimmerHighlight} 58%, ${t.shimmerBase} 76%, ${t.shimmerBase} 100%)`;
const CODE_RING = `inset 0 0 0 1px ${t.conversationTechnicalRing}`;
// Full-bleed preview covers an inset ring on the tile; ::after paints it above.
const ATTACHMENT_RING = `inset 0 0 0 1px ${t.strokeSecondary}, inset 0 0 0 1px ${t.bgElevated}`;
const COMPOSER_RING_DROP = `0 0 0 2px ${t.fillAccentSubtle}`;

export const proseStyles = stylex.create({
  root: {
    display: "flow-root",
    width: "100%",
    minWidth: 0,
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  measure: { width: "100%", maxWidth: conversation.proseMeasure },
  paragraph: {
    marginInline: 0,
    marginBlockStart: {
      default: 16,
      ":is(h1 + p, h2 + p, h3 + p, h4 + p, h5 + p, h6 + p)": 4,
      ":is(li > p)": 0,
      ":first-child": 0,
    },
    marginBlockEnd: {
      default: 16,
      ":has(+ ul, + ol)": 8,
      ":has(+ figure, + blockquote, + [data-prose-table])": 12,
      ":is(li > p)": 0,
      ":last-child": 0,
    },
    whiteSpace: "normal",
  },
  heading: {
    marginInline: 0,
    marginBlockStart: { default: t.leadingLg, ":first-child": 0 },
    marginBlockEnd: { default: 4, ":last-child": 0 },
    fontWeight: 590,
    lineHeight: 1.42,
    textWrap: "balance",
  },
  h1: { fontSize: "1.214em" },
  h2: { fontSize: "1.214em" },
  h3: { fontSize: "1.133em" },
  h4: { fontSize: "1em", marginBlockStart: { default: 12, ":first-child": 0 } },
  h5: { fontSize: "0.866em", color: t.textSecondary },
  h6: { fontSize: "0.8em", color: t.textSecondary },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginInline: 0,
    marginBlockStart: { default: 8, ":is(li > ul, li > ol)": 4, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    paddingInlineStart: "2em",
  },
  listItem: { whiteSpace: "normal" },
  strong: { color: t.textPrimary, fontWeight: 590 },
  inlineCode: {
    paddingInline: { default: "0.3em", ":is(a code)": 0 },
    paddingBlock: { default: "0.08em", ":is(a code)": 0 },
    borderRadius: { default: t.radiusSm, ":is(a code)": 0 },
    borderWidth: { default: 1, ":is(a code)": 0 },
    borderStyle: { default: "solid", ":is(a code)": "none" },
    borderColor: { default: t.strokeTertiary, ":is(a code)": "transparent" },
    backgroundColor: { default: t.fillGhostHover, ":is(a code)": "transparent" },
    color: "inherit",
    fontFamily: t.fontMono,
    fontSize: t.fontSm,
    letterSpacing: "normal",
    lineHeight: "inherit",
    whiteSpace: "break-spaces",
    boxDecorationBreak: "clone",
  },
  link: {
    color: t.textAccent,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillAccentSubtle },
    },
    marginInline: -2,
    padding: 2,
    borderRadius: 4,
    fontWeight: 500,
    textDecorationLine: { default: "none", ":hover": "underline" },
    textDecorationThickness: "from-font",
    textUnderlineOffset: 2,
    boxDecorationBreak: "clone",
    cursor: "pointer",
  },
  blockquote: {
    marginInline: 0,
    marginBlockStart: { default: 12, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    paddingInlineStart: 12,
    borderInlineStartWidth: 2,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.strokePrimary,
    color: t.textSecondary,
  },
  rule: {
    width: "100%",
    maxWidth: conversation.proseMeasure,
    height: 1,
    marginBlock: 8,
    borderStyle: "none",
    backgroundColor: t.strokeTertiary,
  },
  tableWrap: {
    marginBlockStart: { default: 12, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    width: "100%",
    maxWidth: "100%",
    overflowX: "auto",
    // A horizontal scroller must not become a vertical one: `overflow-x: auto`
    // alone computes `overflow-y` to `auto`, which latches the wheel and stops
    // the conversation under the reader. The transcript owns vertical scroll.
    overflowY: "hidden",
    borderRadius: t.radiusLg,
    boxShadow: CODE_RING,
  },
  table: {
    width: "max-content",
    minWidth: "100%",
    borderCollapse: "collapse",
    fontSize: t.fontBase,
  },
  cell: {
    paddingBlock: 4,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.conversationTechnicalRing,
    textAlign: "left",
    verticalAlign: "top",
  },
  headerCell: { backgroundColor: t.conversationTechnicalBg, fontWeight: 600 },
  fallbackPre: {
    width: "100%",
    margin: 0,
    padding: 12,
    overflowX: "auto",
    overflowY: "hidden",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    whiteSpace: "pre",
  },
  imageLabel: { color: t.textTertiary },
});

export const codeBlockStyles = stylex.create({
  figure: {
    position: "relative",
    marginBlock: 10,
    marginInline: 0,
    overflow: "hidden",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    // Hover lives on the figure so the copy control can stay out of the way.
    "--nyte-code-copy-opacity": {
      default: "0",
      ":hover": "1",
      ":focus-within": "1",
      "@media (hover: none)": "1",
    },
  },
  scroll: { maxWidth: "100%", overflowX: "auto", overflowY: "hidden" },
  pre: {
    margin: 0,
    padding: 12,
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    userSelect: "text",
  },
  copy: {
    position: "absolute",
    top: 6,
    right: 6,
    zIndex: 1,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    opacity: "var(--nyte-code-copy-opacity)",
    backgroundColor: {
      default: t.conversationTechnicalBg,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    color: t.iconTertiary,
    cursor: "pointer",
  },
});

export const composerStyles = stylex.create({
  // The dock is an opaque base layer. Transcript content never shows through
  // the composer or its queue controls.
  //
  // Rows dissolve into the dock instead of being cut at its edge. Cursor's
  // glass build masks the scroller itself, which needs the composer to sit
  // outside it; ours is sticky inside, so this is Cursor's overlay recipe for
  // that case (`.composer-fade-overlay`): one solid block of the dock's own
  // colour, masked away upward. A painted gradient would interpolate toward
  // transparent black and cast grey over the rows it is meant to fade.
  dock: {
    position: "sticky",
    bottom: 0,
    zIndex: layer.stickyContent,
    flexShrink: 0,
    width: "100%",
    paddingTop: 12,
    backgroundColor: t.bgBase,
    "::before": {
      content: "''",
      position: "absolute",
      insetInline: 0,
      bottom: "100%",
      height: conversation.edgeFade,
      backgroundColor: t.bgBase,
      maskImage: "linear-gradient(to top, black, transparent)",
      pointerEvents: "none",
    },
  },
  region: {
    display: "flex",
    flexDirection: "column",
    gap: tray.gap,
    width: `min(${conversation.measure}, 100%)`,
    marginInline: "auto",
    paddingInline: conversation.gutter,
    paddingTop: 8,
    paddingBottom: conversation.composerInset,
  },
  queueList: { maxHeight: 200 },
  queueRow: {
    "--_queue-actions-opacity": {
      default: "0",
      ":hover": "1",
      ":focus-within": "1",
      "[data-editing='true']": "1",
      "[data-error='true']": "1",
      "@media (hover: none)": "1",
    },
    "--_queue-actions-events": {
      default: "none",
      ":hover": "auto",
      ":focus-within": "auto",
      "[data-editing='true']": "auto",
      "[data-error='true']": "auto",
      "@media (hover: none)": "auto",
    },
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    minWidth: 0,
    minHeight: tray.rowHeight,
    paddingBlock: 0,
    paddingInlineStart: tray.rowInset,
    paddingInlineEnd: 4,
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
      ":focus-within": t.fillGhostHover,
      "[data-editing='true']": t.fillAccentSubtle,
    },
    boxShadow: {
      default: "none",
      "[data-editing='true']": `inset 0 0 0 1px ${t.composerRingActive}`,
    },
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: tray.lineHeight,
    transitionProperty: "background-color",
    transitionDuration: {
      default: "100ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease-in-out",
  },
  queueMessage: { flex: 1, minWidth: 0 },
  queuePreview: {
    display: "-webkit-box",
    paddingBlock: 4,
    overflow: "hidden",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  queueActions: {
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
    gap: 2,
    marginInlineStart: "auto",
    opacity: "var(--_queue-actions-opacity)",
    pointerEvents: "var(--_queue-actions-events)",
    transitionProperty: "opacity",
    transitionDuration: {
      default: "100ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease-in-out",
  },
  queued: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 30,
    paddingInline: 10,
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textSecondary,
    fontSize: t.fontSm,
  },
  queuedText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  queuedState: {
    display: "block",
    paddingBlockEnd: 4,
    color: t.textTertiary,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
    overflowWrap: "anywhere",
  },
  queuedError: { color: t.textDanger },
  queueHint: {
    color: t.textTertiary,
    fontSize: t.fontSm,
  },
  queuedAction: {
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textAccent,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    fontSize: t.fontSm,
    cursor: "pointer",
    flexShrink: 0,
  },
  scrollToBottom: {
    position: "absolute",
    zIndex: 1,
    top: -22,
    left: "50%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    padding: 0,
    transform: "translateX(-50%)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.composerRing,
    borderRadius: t.radiusFull,
    backgroundColor: {
      default: t.composerBg,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    boxShadow: `0 1px 3px ${t.shadowControlColor}`,
    color: t.iconSecondary,
    cursor: "pointer",
  },
  frame: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: t.composerRing,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.composerRingActive },
      ":focus-within": t.composerRingActive,
    },
    backgroundColor: t.composerBg,
    boxShadow: "none",
    transitionProperty: "border-color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  frameNewChat: {
    gap: 6,
    minHeight: 106,
    padding: "10px 12px 8px",
    borderRadius: conversation.composerNewChatRadius,
  },
  frameFollowUpCompact: {
    gap: 6,
    minHeight: 40,
    padding: "4px 8px 4px 10px",
    borderRadius: t.radiusFull,
  },
  frameFollowUpExpanded: { borderRadius: conversation.composerExpandedRadius },
  frameDragging: {
    borderColor: t.composerRingActive,
    boxShadow: COMPOSER_RING_DROP,
  },
  dropGuard: {
    position: "absolute",
    zIndex: 10,
    inset: 0,
    borderRadius: "inherit",
  },
  fileInput: { display: "none" },
  attachments: {
    display: "flex",
    gap: 6,
    width: "100%",
    margin: 0,
    padding: 0,
    listStyle: "none",
    paddingBlockStart: 6,
    paddingInlineEnd: 24,
    overflowX: "auto",
    scrollPaddingInline: 24,
  },
  attachmentsInset: { width: "auto", marginInline: 12 },
  attachmentsInsetCompact: { marginInline: 2 },
  attachment: {
    position: "relative",
    display: "flex",
    flexShrink: 0,
    borderRadius: t.radiusBase,
    backgroundColor: t.imageBg,
    "::after": {
      content: '""',
      position: "absolute",
      inset: 0,
      borderRadius: "inherit",
      boxShadow: ATTACHMENT_RING,
      pointerEvents: "none",
    },
  },
  attachmentRemove: {
    appearance: "none",
    position: "absolute",
    top: -5,
    right: -5,
    zIndex: 1,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 16,
    height: 16,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    backgroundColor: {
      default: t.fillPrimary,
      ":hover:not(:disabled)": t.fillPrimaryHover,
      ":disabled": t.fillPrimaryDisabled,
    },
    boxShadow: `0 1px 2px ${t.shadowControlColor}`,
    color: t.textOnPrimary,
    cursor: { default: "pointer", ":disabled": "default" },
  },
  attachmentError: {
    color: t.textDanger,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  attachmentErrorInset: { marginInline: 12 },
  attachmentErrorInsetCompact: { marginInline: 2 },
  input: {
    display: "block",
    boxSizing: "border-box",
    width: "100%",
    minWidth: 80,
    flex: 1,
    minHeight: t.leadingLg,
    maxHeight: 200,
    overflowY: "auto",
    overscrollBehavior: "contain",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    caretColor: { default: t.textPrimary, "[data-custom-caret='true']": "transparent" },
    "[data-empty='true']::before": {
      content: "attr(data-placeholder)",
      position: "absolute",
      color: t.textTertiary,
      pointerEvents: "none",
    },
    margin: 0,
    padding: 0,
    resize: "none",
    borderStyle: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    "::placeholder": { color: t.textTertiary },
  },
  editorHost: { position: "relative", flex: 1, minWidth: 64 },
  editorParagraph: { margin: 0 },
  messageLink: {
    color: "inherit",
    textDecorationLine: { default: "none", ":hover": "underline" },
    cursor: "pointer",
  },
  composerUrlPill: {
    color: t.textCyan,
    backgroundColor: t.bgSubtle,
    borderRadius: t.radiusLg,
    paddingInline: 4,
    paddingBlock: 0,
    textDecorationLine: "none",
  },
  readOnly: {
    outlineStyle: "none",
    minWidth: 0,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  editorCaret: {
    position: "absolute",
    insetBlockStart: 0,
    insetInlineStart: 0,
    width: 1.5,
    borderRadius: 1,
    backgroundColor: t.textPrimary,
    color: "transparent",
    userSelect: "none",
    pointerEvents: "none",
    animationName: { default: caretBlink, "@media (prefers-reduced-motion: reduce)": "none" },
    animationDuration: "1.1s",
    animationTimingFunction: "step-end",
    animationIterationCount: "infinite",
  },
  inputNewChat: { minHeight: 54, maxHeight: 340 },
  inputCompact: {
    minHeight: 24,
    minWidth: 0,
    overflowX: "auto",
    overflowY: "hidden",
    overflowWrap: "normal",
    whiteSpace: "nowrap",
    wordBreak: "normal",
    "[data-empty='true']::before": {
      width: "100%",
      overflow: "hidden",
      textOverflow: "clip",
      whiteSpace: "nowrap",
    },
  },
  editor: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    columnGap: 4,
    width: "100%",
    minWidth: 0,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
  },
  editorCompact: {
    gridColumn: 2,
    gridRow: 1,
    minWidth: 64,
    overflow: "hidden",
    flexWrap: "nowrap",
  },
  editorExpanded: { minHeight: 54, paddingBlock: 8, paddingInline: 12 },
  mentionChip: {
    "--_mention-leading-opacity": {
      default: "1",
      "[data-has-remove-button='true']:hover": "0",
      "[data-has-remove-button='true']:focus-within": "0",
    },
    "--_mention-remove-opacity": {
      default: "0",
      "[data-has-remove-button='true']:hover": "1",
      "[data-has-remove-button='true']:focus-within": "1",
    },
    "--_mention-remove-events": {
      default: "none",
      "[data-has-remove-button='true']:hover": "auto",
      "[data-has-remove-button='true']:focus-within": "auto",
    },
    position: "relative",
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "baseline",
    verticalAlign: "baseline",
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: t.textCyan,
    fontSize: "inherit",
    fontWeight: 400,
    lineHeight: "inherit",
    whiteSpace: "nowrap",
    cursor: { default: null, "[data-openable='true']": "pointer" },
    opacity: { default: null, "[data-openable='true']:active": 0.7 },
    transitionProperty: "opacity",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease",
  },
  mentionChipSkill: { color: t.textWarning },
  mentionChipLeading: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    width: 12,
    height: 14,
    marginInlineEnd: 4,
    opacity: "var(--_mention-leading-opacity)",
    transitionProperty: "opacity",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease",
  },
  mentionChipRemove: {
    position: "absolute",
    insetInlineStart: 0,
    top: "50%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 14,
    height: 14,
    padding: 0,
    transform: "translateY(-50%)",
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "inherit",
    lineHeight: 1,
    opacity: "var(--_mention-remove-opacity)",
    pointerEvents: "var(--_mention-remove-events)",
    cursor: "pointer",
    transitionProperty: "opacity",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease",
  },
  layout: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  layoutNewChat: { gap: 6 },
  layoutCompact: {
    display: "grid",
    gridTemplateColumns: "28px minmax(64px, 1fr) minmax(0, auto) 28px",
    alignItems: "center",
    gap: 8,
  },
  controls: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
  },
  controlsInset: { paddingInline: 8, paddingBlockEnd: 8 },
  controlsCompact: { display: "contents" },
  controlHitArea: {
    position: "relative",
    "::after": {
      content: '""',
      position: "absolute",
      inset: { default: -6, "@media (pointer: coarse)": -8 },
      borderRadius: "inherit",
    },
  },
  addButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    backgroundColor: {
      default: t.fillSecondary,
      ":hover:not(:disabled)": t.fillGhostHover,
    },
    color: t.iconSecondary,
    cursor: { default: "pointer", ":disabled": "default" },
  },
  addButtonCompact: { gridColumn: 1, gridRow: 1 },
  addMenu: { width: 260, maxWidth: "calc(100vw - 24px)" },
  modelSlot: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  modelSlotCompact: {
    gridColumn: 3,
    gridRow: 1,
    minWidth: 0,
    maxWidth: 220,
  },
  // Same line height as the model trigger so the digits share its baseline.
  gauge: {
    color: t.textTertiary,
    fontSize: t.fontXs,
    lineHeight: t.leadingBase,
  },
  spacer: { flex: 1 },
  spacerCompact: { display: "none" },
  suggestionPositioner: {
    zIndex: layer.menu,
    borderRadius: t.radiusXl,
    boxShadow: "none",
    outline: "none",
  },
  suggestionMenu: {
    display: "flex",
    flexDirection: "column",
    width: "min(var(--anchor-width), calc(100dvw - 16px))",
    maxWidth: "min(var(--anchor-width), calc(100dvw - 16px))",
    maxHeight: "min(280px, var(--available-height))",
    paddingBlock: 6,
    paddingInline: 6,
    borderStyle: "none",
    borderRadius: t.radiusXl,
    outline: "none",
    color: t.textPrimary,
    // The frame clips and carries the inset hairline; the list inside scrolls.
    // An absolutely positioned hairline on a scroll container would travel
    // with the content.
    overflow: "hidden",
    transformOrigin: "var(--transform-origin)",
  },
  suggestionList: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarWidth: "none",
    "::-webkit-scrollbar": { display: "none" },
  },
  suggestionItem: {
    "--_suggestion-icon-color": {
      default: t.iconTertiary,
      ":hover": t.iconSecondary,
      "[aria-selected='true']": t.iconSecondary,
    },
    position: "relative",
    display: "grid",
    gridTemplateColumns: "12px minmax(0, 1fr) auto",
    boxSizing: "border-box",
    alignItems: "center",
    columnGap: 8,
    minHeight: 28,
    marginBlockEnd: 1,
    paddingBlock: 4,
    paddingInline: 8,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    outline: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": t.bgSelection,
      "[aria-selected='true']": t.bgSelection,
    },
    color: {
      default: t.textSecondary,
      ":hover": t.textPrimary,
      "[aria-selected='true']": t.textPrimary,
    },
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
    cursor: "pointer",
    userSelect: "none",
  },
  suggestionIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 12,
    color: "var(--_suggestion-icon-color)",
  },
  suggestionText: {
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    gap: 8,
    overflow: "hidden",
  },
  suggestionLabel: {
    minWidth: 0,
    flexShrink: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionDescription: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionMatch: { color: t.textCyan, fontWeight: "inherit" },
  suggestionShortcut: {
    minWidth: 0,
    paddingInlineStart: 8,
    overflow: "hidden",
    color: t.textTertiary,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionGroupStart: {
    marginBlockStart: pane.dividerGap,
    // A section divider sits in the gap, independent of the rounded row highlight.
    "::before": {
      content: '""',
      position: "absolute",
      insetInline: 0,
      top: -3,
      height: 1,
      backgroundColor: t.strokeTertiary,
      pointerEvents: "none",
    },
  },
  suggestionEmpty: {
    minHeight: 28,
    display: "flex",
    alignItems: "center",
    paddingInline: 8,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  suggestionPreviewPositioner: {
    zIndex: layer.submenu,
    borderRadius: t.radiusXl,
    outline: "none",
  },
  suggestionPreview: {
    display: "flex",
    flexDirection: "column",
    width: 280,
    maxWidth: "min(280px, var(--available-width))",
    maxHeight: "min(300px, var(--available-height))",
    padding: 10,
    borderStyle: "none",
    borderRadius: t.radiusXl,
    outline: "none",
    color: t.textPrimary,
    overflowY: "auto",
  },
  suggestionPreviewTitle: {
    color: t.textPrimary,
    fontSize: t.fontBase,
    fontWeight: 500,
    lineHeight: t.leadingBase,
  },
  suggestionPreviewAttribution: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginBlockStart: 6,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  suggestionPreviewIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 14,
    height: 14,
    color: t.iconTertiary,
  },
  suggestionPreviewDescription: {
    marginBlockStart: 8,
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  // One row per folder on the way to the mention, each stepped in from the one
  // above it, so the path reads as the walk down to what was mentioned.
  suggestionPreviewPath: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    marginBlockStart: 8,
  },
  suggestionPreviewPathRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  // The same box Pierre's file-type glyph occupies, so folder and file rows
  // hang their labels on one line.
  suggestionPreviewPathIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 16,
    height: 16,
    color: t.iconTertiary,
  },
  suggestionPreviewPathIndent: (depth: number) => ({ paddingInlineStart: depth * 12 }),
  suggestionPreviewPathLeaf: { color: t.textPrimary },
  suggestionPreviewPathLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  send: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    flexShrink: 0,
    cursor: { default: "pointer", ":disabled": "default" },
    color: t.textOnPrimary,
    backgroundColor: {
      default: t.fillPrimary,
      ":hover:not(:disabled)": t.fillPrimaryHover,
      ":disabled": t.fillPrimaryDisabled,
    },
    transitionProperty: "background-color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  sendCompact: { gridColumn: 4, gridRow: 1 },
});

export const diffStyles = stylex.create({
  surface: {
    boxSizing: "border-box",
    minWidth: 0,
    overflow: "hidden",
    borderRadius: t.radiusBase,
    backgroundColor: t.conversationTechnicalBg,
  },
  inline: {
    marginTop: 4,
    marginBottom: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
  },
  workbench: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100%",
    margin: 0,
    borderRadius: t.radiusLg,
    boxShadow: CODE_RING,
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    margin: 0,
    borderRadius: 0,
    boxShadow: "none",
    backgroundColor: t.bgEditor,
  },
  stackSection: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.strokeTertiary,
    backgroundColor: t.bgEditor,
  },
  stackHeader: {
    "--_stack-icon-display": {
      default: "flex",
      ":hover": "none",
      "[aria-expanded='false']": "none",
    },
    "--_stack-chevron-display": {
      default: "none",
      ":hover": "flex",
      "[aria-expanded='false']": "flex",
    },
    appearance: "none",
    position: "sticky",
    top: 0,
    zIndex: 5,
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    minHeight: 36,
    margin: 0,
    paddingLeft: 12,
    paddingRight: 8,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.strokeTertiary,
    backgroundColor: t.bgBase,
    color: "inherit",
    font: "inherit",
    textAlign: "start",
    cursor: "pointer",
    flexShrink: 0,
  },
  stackHeaderGlyph: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 16,
    height: 16,
    flexShrink: 0,
    color: t.iconTertiary,
  },
  stackHeaderIcon: { display: "var(--_stack-icon-display)" },
  stackHeaderChevron: { display: "var(--_stack-chevron-display)" },
  stackPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    color: t.textSecondary,
    fontFamily: t.fontSans,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    whiteSpace: "nowrap",
  },
  stackStats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: t.fontBase,
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 30,
    paddingInline: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.conversationTechnicalRing,
    flexShrink: 0,
  },
  path: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: t.fontCode,
  },
  added: { color: t.textSuccess },
  removed: { color: t.textDanger },
  body: { minWidth: 0, overflow: "auto" },
  bodyInline: { maxHeight: diffView.previewMaxHeight },
  bodyWorkbench: { flex: 1, minHeight: 0, maxHeight: "none" },
  bodyStack: { overflow: "visible", maxHeight: "none" },
  // Pierre's :host remaps these through *-override / light-dark tokens.
  patch: {
    display: "block",
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    "--diffs-light-bg": t.bgEditor,
    "--diffs-dark-bg": t.bgEditor,
    "--diffs-light": t.textPrimary,
    "--diffs-dark": t.textPrimary,
    "--diffs-bg-buffer-override": t.bgEditor,
    "--diffs-bg-context-override": t.bgEditor,
    "--diffs-bg-context-gutter-override": t.bgEditor,
    "--diffs-bg-addition-override": t.diffAddedLineBg,
    "--diffs-bg-deletion-override": t.diffRemovedLineBg,
    "--diffs-bg-addition-emphasis-override": t.diffAddedTextBg,
    "--diffs-bg-deletion-emphasis-override": t.diffRemovedTextBg,
    "--diffs-fg-number-override": t.textTertiary,
    "--diffs-addition-color-override": t.added,
    "--diffs-deletion-color-override": t.removed,
    "--diffs-gap-style": "none",
    // Pierre pads the code grid top and bottom. The section header already
    // spaces the patch, and the stack's height arithmetic counts rows alone.
    "--diffs-gap-block": "0px",
    "--diffs-min-number-column-width": "calc(4ch + 8px)",
    "--diffs-font-family": t.fontMono,
    "--diffs-header-font-family": t.fontSans,
    "--diffs-font-size": t.fontCode,
    "--diffs-line-height": "var(--nyte-diff-line-height)",
    "--diffs-tab-size": 4,
  },
});

export const activityStyles = stylex.create({
  shimmer: {
    animationName: {
      default: activityShine,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: {
      default: "2.4s",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    backgroundImage: {
      default: ACTIVITY_SHIMMER,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundSize: "200% 100%",
    backgroundClip: "text",
    color: {
      default: "transparent",
      "@media (prefers-reduced-motion: reduce)": t.textTertiary,
    },
  },
});

export const toolCallStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", minWidth: 0 },
  line: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    width: "fit-content",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: 24,
    paddingInline: 0,
    overflow: "hidden",
    borderStyle: "none",
    backgroundColor: "transparent",
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    textAlign: "left",
    whiteSpace: "nowrap",
    cursor: "pointer",
    userSelect: "none",
    "--_verb-color": {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    "--_detail-color": {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
  },
  editLine: { minHeight: 30 },
  lineStatic: { cursor: "default" },
  lineDetailed: {
    width: "100%",
    minHeight: 32,
    paddingInline: 8,
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
  },
  failed: { "--_verb-color": t.textDanger, "--_detail-color": t.textDanger },
  verb: {
    flexShrink: 0,
    color: "var(--_verb-color)",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  detail: {
    minWidth: 0,
    overflow: "hidden",
    color: "var(--_detail-color)",
    fontFamily: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: "inherit",
    lineHeight: "inherit",
  },
  editStats: { marginInlineStart: 4 },
  added: { color: t.textSuccess },
  removed: { color: t.textDanger },
  row: { display: "flex", alignItems: "center", gap: 2, minWidth: 0, maxWidth: "100%" },
  // The line stays the collapsible trigger; the agent opener is its sibling so buttons never nest.
  openAgent: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 20,
    height: 20,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusSm,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    color: {
      default: t.iconTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.iconPrimary },
    },
    cursor: "pointer",
  },
  chevron: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 16,
    height: 16,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease-in-out",
  },
  chevronOpen: { transform: "rotate(90deg)" },
  output: {
    maxHeight: 260,
    marginTop: 6,
    marginBottom: 4,
    padding: "8px 12px",
    overflowY: "auto",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  // column-reverse keeps the newest lines in view; the top fades when clipped.
  outputPreview: {
    appearance: "none",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column-reverse",
    width: "100%",
    maxHeight: 200,
    marginTop: 6,
    marginBottom: 4,
    padding: "8px 12px",
    overflow: "hidden",
    borderStyle: "none",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    textAlign: "start",
    cursor: "pointer",
    maskImage: {
      default: null,
      "[data-overflow]": "linear-gradient(to bottom, rgba(0, 0, 0, 0.15) 0px, black 32px)",
    },
  },
  outputPreviewText: {
    display: "block",
    width: "100%",
    minWidth: 0,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
});

/**
 * A task call stacks a status line under its title, so its trigger is a
 * column where other tools are one line. Title and model reuse the verb and
 * detail colours; the shimmer moves to the status.
 */
export const subagentCallStyles = stylex.create({
  line: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 0,
    paddingBlock: 2,
  },
  lineDetailed: { paddingBlock: 6 },
  head: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    maxWidth: "100%",
    minWidth: 0,
  },
  status: {
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
});

/** The compact streaming window: about six conversation rows. */
export const WORK_PREVIEW_HEIGHT = 144;

export const toolGroupStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", minWidth: 0, contain: "layout" },
  status: {
    display: "inline-flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    width: "fit-content",
    maxWidth: "100%",
    minHeight: conversation.rowMinHeight,
    color: t.textSecondary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
  },
  toggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    width: "fit-content",
    maxWidth: "100%",
    minHeight: conversation.rowMinHeight,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    textAlign: "left",
    cursor: "pointer",
    userSelect: "none",
  },
  verb: { flexShrink: 0 },
  summary: {
    minWidth: 0,
    overflow: "hidden",
    color: t.textTertiary,
    fontSize: "inherit",
    lineHeight: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: "inherit",
    lineHeight: "inherit",
  },
  added: { color: t.textSuccess },
  removed: { color: t.textDanger },
  chevron: {
    display: "inline-flex",
    flexShrink: 0,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  chevronOpen: { transform: "rotate(90deg)" },
  calls: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBlockStart: 4,
    paddingBlock: 2,
    paddingInlineStart: 16,
  },
  preview: {
    boxSizing: "border-box",
    maxHeight: WORK_PREVIEW_HEIGHT,
    paddingBlockStart: 6,
    overflowX: "hidden",
    overflowY: "auto",
    cursor: "pointer",
    overscrollBehavior: "auto",
    maskImage: {
      default: null,
      "[data-overflow]": "linear-gradient(to bottom, rgba(0, 0, 0, 0.15) 0px, black 32px)",
    },
  },
  // Virtual rows sit on a plane sized to the whole episode; each row carries
  // the list gap so measured heights include it.
  previewPlane: {
    position: "relative",
    width: "100%",
    minWidth: 0,
    contain: "layout paint",
  },
  previewRow: {
    boxSizing: "border-box",
    position: "absolute",
    top: 0,
    insetInlineStart: 0,
    width: "100%",
    minWidth: 0,
    paddingBlockEnd: 6,
  },
  thinking: { minWidth: 0, opacity: 0.68 },
});

export const USER_MESSAGE_PREVIEW_LINES = 3.5;

/** The prompt's own block padding, which the collapsed preview fades through. */
const USER_PROMPT_PADDING_BLOCK = 8;

/** Room for a chip's background above the first line, which the clip would cut. */
const USER_PREVIEW_BLEED_TOP = 2;

/**
 * Cursor's collapsed-message fade (`UMs`): it spans the clipped fractional line
 * plus the whole line above it, and runs out through the prompt's bottom
 * padding. The half line is gone before the clip, so nothing reads as sliced
 * text against the prompt's edge.
 */
const USER_PREVIEW_FADE = `calc(${t.leadingLg} * ${(USER_MESSAGE_PREVIEW_LINES % 1) + 1} + ${USER_PROMPT_PADDING_BLOCK}px)`;

export const turnStyles = stylex.create({
  turn: {
    display: "flex",
    flexDirection: "column",
    gap: conversation.rowGap,
    width: "100%",
    minWidth: 0,
    // The sticky prompt sticks against the outer scrollport, not its turn;
    // layout containment leaves that alone (no overflow clip, no scroller).
    contain: "layout",
  },
  // The row's inset is the transcript's top edge while the prompt is stuck:
  // it paints the pane colour, so rows scrolling past vanish behind it instead
  // of surfacing above the prompt. The scrollport drops its own fade then,
  // which would otherwise make this strip translucent.
  userRow: {
    position: { default: "sticky", "[data-sticky-disabled='true']": "relative" },
    zIndex: { default: layer.stickyContent, "[data-sticky-disabled='true']": "auto" },
    top: 0,
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    paddingTop: 10,
    marginBottom: 4,
    backgroundColor: { default: null, "[data-sticky-active='true']": t.bgBase },
    "--_user-prompt-shadow": {
      default: "none",
      "[data-sticky-active='true']": t.conversationUserShadow,
    },
  },
  userPromptShell: {
    position: "relative",
    width: "100%",
    minWidth: 0,
    borderRadius: t.radiusXl,
    backgroundColor: t.conversationUserShellBg,
  },
  userPrompt: {
    boxSizing: "border-box",
    display: "block",
    width: "100%",
    minWidth: 0,
    paddingBlock: USER_PROMPT_PADDING_BLOCK,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.conversationUserRing,
    borderRadius: t.radiusXl,
    backgroundColor: t.conversationUserBg,
    boxShadow: "var(--_user-prompt-shadow, none)",
    color: t.textPrimary,
    fontFamily: "inherit",
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
    textAlign: "start",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
    transitionProperty: "background-color, border-color, box-shadow",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  userPreview: { overflow: "hidden" },
  userPreviewCollapsed: { maxHeight: `calc(${t.leadingLg} * ${USER_MESSAGE_PREVIEW_LINES})` },
  // The preview bleeds into the prompt's padding so the fade has somewhere to
  // finish; negative margins give the bleed back, leaving the row's height and
  // the toggle's place unchanged.
  userPreviewFade: {
    maxHeight: `calc(${t.leadingLg} * ${USER_MESSAGE_PREVIEW_LINES} + ${USER_PREVIEW_BLEED_TOP + USER_PROMPT_PADDING_BLOCK}px)`,
    paddingTop: USER_PREVIEW_BLEED_TOP,
    marginTop: -USER_PREVIEW_BLEED_TOP,
    paddingBottom: USER_PROMPT_PADDING_BLOCK,
    marginBottom: -USER_PROMPT_PADDING_BLOCK,
    maskImage: `linear-gradient(to bottom, #000 calc(100% - ${USER_PREVIEW_FADE}), transparent 100%)`,
  },
  userPreviewToggle: {
    display: "block",
    minHeight: 28,
    marginBlockStart: 4,
    paddingInline: 4,
    paddingBlock: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: "transparent",
    color: { default: t.textTertiary, ":hover": t.textPrimary },
    fontSize: t.fontSm,
    cursor: "pointer",
  },
  userImages: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    paddingBlockEnd: 8,
  },
  userPromptHit: {
    outlineStyle: "none",
    appearance: "none",
    display: "block",
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    margin: 0,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    letterSpacing: "inherit",
    textAlign: "start",
    whiteSpace: "inherit",
    overflowWrap: "anywhere",
    cursor: "text",
  },
  userPromptEditable: {
    backgroundColor: {
      default: t.conversationUserBg,
      ":hover": {
        "@media (hover: hover) and (pointer: fine)": t.conversationUserBgHover,
      },
    },
    borderColor: {
      default: t.conversationUserRing,
      ":has(:focus-visible)": t.conversationUserRingActive,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.conversationUserRingActive },
    },
    cursor: "text",
    outlineStyle: "none",
  },
  changesCard: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 2,
    width: "100%",
    paddingBlock: 8,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    borderRadius: t.radiusXl,
    backgroundColor: t.bgElevated,
    color: t.textPrimary,
  },
  changesHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minHeight: 24,
  },
  changesTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
  },
  changesReview: {
    appearance: "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 28,
    marginBlock: -2,
    paddingInline: 4,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    color: {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    cursor: "pointer",
  },
  changesList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    maxHeight: 132,
    margin: 0,
    padding: 0,
    overflowY: "auto",
    listStyle: "none",
  },
  changesFile: {
    appearance: "none",
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    minWidth: 0,
    minHeight: 24,
    paddingBlock: 0,
    paddingInline: 4,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
      ":active": t.fillGhostSelected,
    },
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    textAlign: "start",
    cursor: "pointer",
  },
  changesFileIcon: {
    display: "inline-flex",
    transform: "translateY(1px)",
  },
  changesPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  changesStats: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  changesAdded: { color: t.textSuccess },
  changesRemoved: { color: t.textDanger },
  // The edit is the composer frame itself; this only stacks an error line above it.
  userEdit: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    minWidth: 0,
  },
  userEditError: {
    minWidth: 0,
    paddingInlineStart: 4,
    overflow: "hidden",
    color: t.textDanger,
    fontSize: t.fontXs,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  reasoning: { display: "flex", flexDirection: "column", width: "100%", minWidth: 0 },
  reasoningToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    width: "fit-content",
    minHeight: conversation.rowMinHeight,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    cursor: "pointer",
    userSelect: "none",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOut,
  },
  reasoningChevron: {
    display: "inline-flex",
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  reasoningChevronOpen: { transform: "rotate(90deg)" },
  reasoningBody: {
    boxSizing: "border-box",
    width: "100%",
    maxWidth: conversation.proseMeasure,
    marginTop: 4,
    paddingBlock: 2,
    paddingInlineStart: 16,
    opacity: 0.68,
  },
  notice: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: conversation.rowMinHeight,
    paddingBlock: 2,
    color: t.textTertiary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  noticeError: {
    color: t.textDanger,
  },
  history: { display: "flex", flexDirection: "column", minWidth: 0 },
  historyToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    width: "fit-content",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: conversation.rowMinHeight,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    cursor: "pointer",
    userSelect: "none",
  },
  historyChevron: {
    display: "inline-flex",
    flexShrink: 0,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  historyChevronOpen: { transform: "rotate(90deg)" },
  historyBody: {
    boxSizing: "border-box",
    width: "100%",
    marginTop: 4,
    paddingBlock: 2,
    paddingInlineStart: 12,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.conversationGuide,
    opacity: 0.68,
  },
});
