/**
 * Conversation presentation has one StyleX owner. Renderers keep behavior and
 * semantics; this module keeps the shared hierarchy, geometry, and states
 * coherent across prose, tools, diffs, reasoning, and the composer.
 *
 * Based on https://github.com/b-nnett/grok-bot-0.18-reconstructed/blob/a9f633e09d49a85829b8236331b9e21f7e612634/frontend/src/recovered/features/conversation/workspace/view.css
 */
import * as stylex from "@stylexjs/stylex";
import { conversation, diffView } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

const activityShine = stylex.keyframes({
  "0%": { backgroundPosition: "200% 0" },
  "100%": { backgroundPosition: "-200% 0" },
});

const ACTIVITY_SHIMMER = `linear-gradient(90deg, ${t.shimmerBase} 0%, ${t.shimmerBase} 28%, ${t.shimmerHighlight} 58%, ${t.shimmerBase} 76%, ${t.shimmerBase} 100%)`;
const CODE_RING = `inset 0 0 0 1px ${t.conversationTechnicalRing}`;
const COMPOSER_RING = `inset 0 0 0 1px ${t.composerRing}, ${t.composerShadow}`;
const COMPOSER_RING_ACTIVE = `inset 0 0 0 1px ${t.composerRingActive}, ${t.composerShadow}`;
const ERROR_RING = `inset 0 0 0 1px ${t.conversationErrorRing}`;
const USER_RING = `inset 0 0 0 1px ${t.conversationUserRing}`;

export const proseStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    minWidth: 0,
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: 1.57,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  measure: { width: "100%", maxWidth: conversation.proseMeasure },
  paragraph: { margin: 0, whiteSpace: "pre-wrap", textWrap: "pretty" },
  heading: {
    margin: 0,
    fontWeight: 600,
    lineHeight: 1.35,
    textWrap: "balance",
  },
  h1: { fontSize: 19 },
  h2: { fontSize: 17 },
  h3: { fontSize: 15 },
  h4: { fontSize: t.fontLg },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    margin: 0,
    paddingInlineStart: 22,
  },
  listItem: { whiteSpace: "pre-wrap" },
  strong: { color: t.textPrimary, fontWeight: 600 },
  inlineCode: {
    paddingInline: 4,
    paddingBlock: 1,
    borderRadius: t.radiusSm,
    backgroundColor: t.fillSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
  },
  link: {
    color: t.textAccent,
    textDecorationLine: "underline",
    textUnderlineOffset: 2,
    cursor: "pointer",
  },
  blockquote: {
    margin: 0,
    paddingInlineStart: 12,
    borderInlineStartWidth: 2,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.borderDefault,
    color: t.textSecondary,
  },
  rule: {
    width: "100%",
    maxWidth: conversation.proseMeasure,
    height: 1,
    marginBlock: 8,
    borderStyle: "none",
    backgroundColor: t.strokeTertiary,
  },
  tableWrap: {
    width: "100%",
    maxWidth: "100%",
    overflowX: "auto",
    borderRadius: t.radiusLg,
    boxShadow: CODE_RING,
  },
  table: {
    width: "max-content",
    minWidth: "100%",
    borderCollapse: "collapse",
    fontSize: t.fontLg,
    fontVariantNumeric: "tabular-nums",
  },
  cell: {
    paddingBlock: 4,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.conversationTechnicalRing,
    textAlign: "left",
    verticalAlign: "top",
  },
  headerCell: { backgroundColor: t.conversationTechnicalBg, fontWeight: 600 },
  fallbackPre: {
    width: "100%",
    margin: 0,
    padding: "11px 12px",
    overflowX: "auto",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    whiteSpace: "pre",
  },
  imageLabel: { color: t.textTertiary },
});

export const codeBlockStyles = stylex.create({
  figure: {
    position: "relative",
    marginBlock: 10,
    marginInline: 0,
    overflow: "hidden",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
    paddingInlineStart: 11,
    paddingInlineEnd: 5,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.conversationTechnicalRing,
  },
  scroll: { maxWidth: "100%", overflowX: "auto" },
  pre: {
    margin: 0,
    padding: "11px 12px",
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    userSelect: "text",
  },
  language: {
    flex: 1,
    minWidth: 0,
    color: t.textQuaternary,
    fontFamily: t.fontMono,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
    userSelect: "none",
  },
  copy: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
    },
    color: t.iconTertiary,
    cursor: "pointer",
  },
});

export const composerStyles = stylex.create({
  region: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: `min(${conversation.measure}, 100%)`,
    marginInline: "auto",
    paddingInline: conversation.gutter,
    paddingTop: 8,
    paddingBottom: conversation.composerInset,
  },
  queued: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 30,
    paddingInline: 10,
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textSecondary,
    fontSize: t.fontSm,
  },
  queuedText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  queuedAction: {
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textAccent,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    fontSize: t.fontSm,
    cursor: "pointer",
    flexShrink: 0,
  },
  frame: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minHeight: 82,
    padding: "11px 9px 8px 12px",
    borderStyle: "none",
    borderRadius: t.radiusXl,
    backgroundColor: t.composerBg,
    boxShadow: {
      default: COMPOSER_RING,
      ":hover": { "@media (hover: hover) and (pointer: fine)": COMPOSER_RING_ACTIVE },
      ":focus-within": COMPOSER_RING_ACTIVE,
    },
    transitionProperty: "box-shadow",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  input: {
    display: "block",
    boxSizing: "border-box",
    width: "100%",
    minHeight: 24,
    maxHeight: 180,
    resize: "none",
    borderStyle: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: 1.57,
    "::placeholder": { color: t.textTertiary },
  },
  controls: { display: "flex", alignItems: "center", gap: 8, minHeight: 28 },
  gauge: { color: t.textTertiary, fontSize: t.fontXs, fontVariantNumeric: "tabular-nums" },
  spacer: { flex: 1 },
  send: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderStyle: "none",
    borderRadius: t.radiusFull,
    flexShrink: 0,
    cursor: { default: "pointer", ":disabled": "default" },
    color: t.textOnPrimary,
    backgroundColor: {
      default: t.fillPrimary,
      ":hover:not(:disabled)": t.fillPrimaryHover,
      ":disabled": t.fillPrimaryDisabled,
    },
    transitionProperty: "background-color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  stop: {
    color: t.textPrimary,
    backgroundColor: {
      default: t.fillSecondary,
      ":hover:not(:disabled)": t.fillSecondaryHover,
    },
  },
});

export const diffStyles = stylex.create({
  card: {
    marginTop: 6,
    marginBottom: 4,
    overflow: "hidden",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
  },
  cardFill: { display: "flex", flexDirection: "column", minHeight: "100%", margin: 0 },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 30,
    paddingInline: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.conversationTechnicalRing,
    flexShrink: 0,
  },
  path: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: t.fontCode,
    fontVariantNumeric: "tabular-nums",
  },
  added: { color: t.added },
  removed: { color: t.removed },
  body: { maxHeight: diffView.previewMaxHeight, minWidth: 0, overflow: "auto" },
  bodyFill: { flex: 1, minHeight: 0, maxHeight: "none" },
  fallback: {
    boxSizing: "border-box",
    width: "max-content",
    minWidth: "100%",
    margin: 0,
    paddingBlock: 8,
    paddingInline: 12,
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: diffView.lineHeight,
    whiteSpace: "pre",
    userSelect: "text",
  },
});

export const pierrePatchStyles = stylex.create({
  host: { display: "block", width: "100%", minWidth: 0, maxWidth: "100%" },
});

export const activityStyles = stylex.create({
  shimmer: {
    animationName: {
      default: activityShine,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: {
      default: "2.4s",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    backgroundImage: {
      default: ACTIVITY_SHIMMER,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundSize: "200% 100%",
    backgroundClip: "text",
    color: {
      default: "transparent",
      "@media (prefers-reduced-motion: reduce)": t.textTertiary,
    },
  },
});

export const toolCallStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", minWidth: 0 },
  line: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    width: "fit-content",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: 24,
    paddingInline: 0,
    overflow: "hidden",
    borderStyle: "none",
    backgroundColor: "transparent",
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textAlign: "left",
    whiteSpace: "nowrap",
    cursor: "pointer",
    userSelect: "none",
    "--_verb-color": {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    "--_detail-color": {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
  },
  lineStatic: { cursor: "default" },
  failed: { "--_verb-color": t.textDanger, "--_detail-color": t.textDanger },
  verb: {
    flexShrink: 0,
    color: "var(--_verb-color)",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  detail: {
    minWidth: 0,
    overflow: "hidden",
    color: "var(--_detail-color)",
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: t.fontCode,
    fontVariantNumeric: "tabular-nums",
  },
  added: { color: t.added },
  removed: { color: t.removed },
  chevron: {
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  chevronOpen: { transform: "rotate(90deg)" },
  output: {
    maxHeight: 260,
    marginTop: 6,
    marginBottom: 4,
    padding: "8px 12px",
    overflowY: "auto",
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationTechnicalBg,
    boxShadow: CODE_RING,
    color: t.textSecondary,
    fontFamily: t.fontMono,
    fontSize: t.fontCode,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
});

export const toolGroupStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", minWidth: 0 },
  toggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 24,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textPrimary },
    },
    fontSize: t.fontBase,
    textAlign: "left",
    cursor: "pointer",
  },
  failed: { color: t.textDanger },
  verb: { flexShrink: 0 },
  summary: {
    minWidth: 0,
    overflow: "hidden",
    color: t.textTertiary,
    fontSize: t.fontSm,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 5,
    flexShrink: 0,
    fontSize: t.fontSm,
    fontVariantNumeric: "tabular-nums",
  },
  added: { color: t.added },
  removed: { color: t.removed },
  chevron: {
    display: "inline-flex",
    flexShrink: 0,
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  chevronOpen: { transform: "rotate(90deg)" },
  calls: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    marginBlock: 3,
    marginInlineStart: 4,
    paddingInlineStart: 12,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.borderWeak,
  },
});

export const turnStyles = stylex.create({
  turn: {
    display: "flex",
    flexDirection: "column",
    gap: conversation.rowGap,
    width: "100%",
    minWidth: 0,
  },
  userRow: { display: "flex", width: "100%", minWidth: 0 },
  userPrompt: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    paddingBlock: 11,
    paddingInline: 14,
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationUserBg,
    boxShadow: USER_RING,
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: 1.57,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  reasoning: { display: "flex", flexDirection: "column", width: "100%", minWidth: 0 },
  reasoningToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    width: "fit-content",
    minHeight: conversation.rowMinHeight,
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: {
      default: t.textTertiary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.textSecondary },
    },
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    cursor: "pointer",
    userSelect: "none",
    transitionProperty: "color",
    transitionDuration: {
      default: t.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  reasoningChevron: {
    display: "inline-flex",
    color: t.iconTertiary,
    transform: "rotate(0deg)",
    transitionProperty: "transform",
    transitionDuration: {
      default: t.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: t.easeOutQuint,
  },
  reasoningChevronOpen: { transform: "rotate(90deg)" },
  reasoningBody: {
    boxSizing: "border-box",
    width: "100%",
    maxWidth: conversation.proseMeasure,
    marginTop: 3,
    paddingBlock: 2,
    paddingInlineStart: 12,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.conversationGuide,
    color: t.textTertiary,
    fontSize: t.fontLg,
    lineHeight: 1.57,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  notice: {
    boxSizing: "border-box",
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    width: "100%",
    maxWidth: conversation.proseMeasure,
    minHeight: conversation.rowMinHeight,
    paddingBlock: 3,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  noticeError: {
    paddingBlock: 8,
    paddingInline: 10,
    borderRadius: t.radiusLg,
    backgroundColor: t.conversationErrorBg,
    boxShadow: ERROR_RING,
    color: t.textDanger,
  },
  marker: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    width: "100%",
    minWidth: 0,
    minHeight: conversation.rowMinHeight,
    color: t.textQuaternary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  markerRule: {
    flex: 1,
    height: 1,
    backgroundColor: t.strokeTertiary,
    pointerEvents: "none",
    userSelect: "none",
  },
  markerLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
    flexShrink: 1,
    color: t.textTertiary,
    userSelect: "text",
  },
  summary: {
    boxSizing: "border-box",
    width: "100%",
    maxWidth: conversation.proseMeasure,
    paddingBlock: 2,
    paddingInlineStart: 12,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.conversationGuide,
  },
  summaryLabel: {
    display: "block",
    marginBottom: 4,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    userSelect: "text",
  },
  summaryText: {
    color: t.textSecondary,
    fontSize: t.fontLg,
    lineHeight: 1.57,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
});
