export {
  avatarDefaults,
  avatarVars,
  borderDefaults,
  borderVars,
  colorDefaults,
  colorVars,
  controlDefaults,
  controlVars,
  elevationDefaults,
  elevationVars,
  fontDefaults,
  fontVars,
  motionDefaults,
  motionVars,
  overlayDefaults,
  overlayVars,
  radiusDefaults,
  radiusVars,
  spaceDefaults,
  spaceVars,
} from "./platform-tokens.stylex";
export type {
  AvatarVarName,
  BorderVarName,
  ColorVarName,
  ControlVarName,
  ElevationVarName,
  FontVarName,
  MotionVarName,
  OverlayVarName,
  RadiusVarName,
  SpaceVarName,
} from "./platform-tokens.stylex";
