import { defineConsts } from "@stylexjs/stylex";
import "./tokens.stylex.ts";

export const role = defineConsts({
  contentPrimary: "var(--nyte-content-primary)",
  contentSecondary: "var(--nyte-content-secondary)",
  contentTertiary: "var(--nyte-content-tertiary)",
  contentDisabled: "var(--nyte-content-disabled)",
  contentChrome: "var(--nyte-content-chrome)",
  contentInteractivePrimary: "var(--nyte-content-interactive-primary)",
  contentDisabledTranslucent: "var(--nyte-content-disabled-translucent)",
  contentInteractiveSecondary: "var(--nyte-content-interactive-secondary)",
  contentInteractiveTertiary: "var(--nyte-content-interactive-tertiary)",
  contentOnInteractiveStrong: "var(--nyte-content-on-interactive-strong)",
  contentOnControl: "var(--nyte-content-on-control)",
  borderPrimary: "var(--nyte-border-primary)",
  borderSecondary: "var(--nyte-border-secondary)",
  borderStrong: "var(--nyte-border-strong)",
  borderInteractivePrimary: "var(--nyte-border-interactive-primary)",
  borderPrimaryTranslucent: "var(--nyte-border-primary-translucent)",
  borderSecondaryTranslucent: "var(--nyte-border-secondary-translucent)",
  borderStrongTranslucent: "var(--nyte-border-strong-translucent)",
  borderControl: "var(--nyte-border-control)",
  borderInteractivePrimaryTranslucent: "var(--nyte-border-interactive-primary-translucent)",
  borderControlTranslucent: "var(--nyte-border-control-translucent)",
  bgBase: "var(--nyte-bg-base)",
  bgMuted: "var(--nyte-bg-muted)",
  bgElevated: "var(--nyte-bg-elevated)",
  bgInteractivePrimary: "var(--nyte-bg-interactive-primary)",
  bgInteractivePrimaryHover: "var(--nyte-bg-interactive-primary-hover)",
  bgInteractivePrimaryPressed: "var(--nyte-bg-interactive-primary-pressed)",
  bgInteractiveSecondary: "var(--nyte-bg-interactive-secondary)",
  bgInteractiveSecondaryHover: "var(--nyte-bg-interactive-secondary-hover)",
  bgInteractiveSecondaryPressed: "var(--nyte-bg-interactive-secondary-pressed)",
  bgInteractiveStrong: "var(--nyte-bg-interactive-strong)",
  bgInteractiveStrongHover: "var(--nyte-bg-interactive-strong-hover)",
  bgInteractiveStrongPressed: "var(--nyte-bg-interactive-strong-pressed)",
  bgInverse: "var(--nyte-bg-inverse)",
  bgControlSelected: "var(--nyte-bg-control-selected)",
  bgControlSelectedHover: "var(--nyte-bg-control-selected-hover)",
  bgControlSelectedPressed: "var(--nyte-bg-control-selected-pressed)",
  bgControl: "var(--nyte-bg-control)",
  bgControlHover: "var(--nyte-bg-control-hover)",
  bgControlPressed: "var(--nyte-bg-control-pressed)",
  bgChrome: "var(--nyte-bg-chrome)",
  bgBaseTranslucent: "var(--nyte-bg-base-translucent)",
  bgChromeTranslucent: "var(--nyte-bg-chrome-translucent)",
  bgMutedTranslucent: "var(--nyte-bg-muted-translucent)",
  bgInteractivePrimaryTranslucent: "var(--nyte-bg-interactive-primary-translucent)",
  bgInteractivePrimaryTranslucentHover: "var(--nyte-bg-interactive-primary-translucent-hover)",
  bgInteractivePrimaryTranslucentPressed: "var(--nyte-bg-interactive-primary-translucent-pressed)",
  bgInteractiveSecondaryTranslucent: "var(--nyte-bg-interactive-secondary-translucent)",
  bgInteractiveSecondaryTranslucentHover: "var(--nyte-bg-interactive-secondary-translucent-hover)",
  bgInteractiveSecondaryTranslucentPressed:
    "var(--nyte-bg-interactive-secondary-translucent-pressed)",
  bgScrimTranslucent: "var(--nyte-bg-scrim-translucent)",
  bgScrim: "var(--nyte-bg-scrim)",
  bgHover: "var(--nyte-bg-hover)",
  bgPressed: "var(--nyte-bg-pressed)",
  sidebarMaterial: "var(--nyte-sidebar-material)",
  popupMaterial: "var(--nyte-popup-material)",
  layerHover: "var(--nyte-layer-hover)",
  layerPressed: "var(--nyte-layer-pressed)",
  scrollbarThumb: "var(--nyte-scrollbar-thumb)",
  buttonFill: "var(--nyte-button-fill)",
  buttonFillHover: "var(--nyte-button-fill-hover)",
  buttonFillPressed: "var(--nyte-button-fill-pressed)",
  conversationUserShellBg: "var(--nyte-conversation-user-shell-bg)",
});

export const type = defineConsts({
  fontSans: "var(--nyte-font-family-sans)",
  fontMono: "var(--nyte-font-family-mono)",
  fontXs: "var(--nyte-font-size-xs)",
  fontSm: "var(--nyte-font-size-sm)",
  fontBase: "var(--nyte-font-size-base)",
  fontLg: "var(--nyte-font-size-lg)",
  font2xl: "var(--nyte-font-size-2xl)",
  fontCode: "var(--nyte-font-size-code)",
  leadingXs: "var(--nyte-line-height-xs)",
  leadingSm: "var(--nyte-line-height-sm)",
  leadingBase: "var(--nyte-line-height-base)",
  leadingLg: "var(--nyte-line-height-lg)",
  letterBase: "var(--nyte-letter-spacing-base)",
  letterLg: "var(--nyte-letter-spacing-lg)",
  uiFontInter: "var(--nyte-ui-font-inter)",
  uiFontSystem: "var(--nyte-ui-font-system)",
  codeFontJetbrainsMono: "var(--nyte-code-font-jetbrains-mono)",
  codeFontSystem: "var(--nyte-code-font-system)",
});

export const motion = defineConsts({
  durationInstant: "var(--nyte-duration-instant)",
  durationFast: "var(--nyte-duration-fast)",
  durationNormal: "var(--nyte-duration-normal)",
  durationSlow: "var(--nyte-duration-slow)",
  easeOut: "var(--nyte-easing-out)",
  easeOutQuint: "var(--nyte-easing-out-quint)",
  easeInOutStrong: "var(--nyte-easing-in-out-strong)",
});

export const shadow = defineConsts({
  shadowSm: "var(--nyte-shadow-sm)",
  shadowMd: "var(--nyte-shadow-md)",
  shadowMdOutline: "var(--nyte-shadow-md-outline)",
  shadowLg: "var(--nyte-shadow-lg)",
  shadowXl: "var(--nyte-shadow-xl)",
  shadowWorkbench: "var(--nyte-shadow-workbench)",
});

export const appearance = defineConsts({
  popupMaterialFilter: "var(--nyte-popup-material-filter)",
  cursorInteractive: "var(--nyte-cursor-interactive)",
  focusRing: "var(--nyte-focus-ring)",
  focusColor: "var(--nyte-focus-color)",
});
