import { create } from "@stylexjs/stylex";
import { glyph, layer, workbench } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const workbenchStyles = create({
  root: {
    position: "relative",
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    flexShrink: 0,
    backgroundColor: t.bgBase,
  },
  panel: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    backgroundColor: t.bgBase,
  },
  panelOpen: {
    minWidth: workbench.panelWidth,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.strokeTertiary,
  },
  railHost: { width: workbench.railWidth, minWidth: workbench.railWidth },
  railHostCompact: { width: 46, minWidth: 46 },
  panelOverlay: {
    position: "absolute",
    zIndex: layer.workbench,
    insetBlock: 0,
    insetInlineEnd: 0,
    minWidth: 0,
    maxWidth: "100vw",
    boxShadow: t.shadowWorkbench,
  },
  panelHidden: { display: "none" },
  panelBody: { display: "flex", flex: 1, minWidth: 0, minHeight: 0, flexDirection: "column" },
  rail: {
    display: "flex",
    flexDirection: "column",
    gap: workbench.railGap,
    width: "100%",
    minWidth: 0,
    paddingBlock: 4,
    paddingInline: 8,
    color: t.textSecondary,
  },
  railSection: { display: "flex", flexDirection: "column", gap: 1, minWidth: 0 },
  railHeading: {
    display: "flex",
    alignItems: "center",
    minHeight: workbench.headingHeight,
    paddingInline: workbench.rowPaddingInline,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  railHeadingText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chevron: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 24,
    height: 24,
    marginInlineEnd: -4,
    padding: 0,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: { default: "transparent", ":hover": t.fillGhostHover },
    color: t.iconTertiary,
    cursor: "pointer",
  },
  doubleChevron: { display: "inline-flex", alignItems: "center" },
  doubleChevronBack: { transform: "scaleX(-1)" },
  doubleChevronTrail: { display: "inline-flex", marginInlineStart: -4 },
  railRow: {
    display: "flex",
    alignItems: "center",
    gap: workbench.rowGap,
    width: "100%",
    minWidth: 0,
    minHeight: workbench.rowHeight,
    paddingBlock: 2,
    paddingInline: workbench.rowPaddingInline,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
      ":active": t.fillGhostSelected,
    },
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textAlign: "start",
    cursor: "pointer",
  },
  railIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: glyph.box,
    flexShrink: 0,
    color: t.iconSecondary,
  },
  railLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  railStats: {
    display: "inline-flex",
    gap: workbench.rowGap,
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  },
  railAdded: { color: t.textSuccess },
  railRemoved: { color: t.textDanger },
  iconRail: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    boxSizing: "border-box",
    width: 34,
    marginBlockStart: 4,
    marginInline: 6,
    padding: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeTertiary,
    borderRadius: 10,
    backgroundColor: t.bgElevated,
    color: t.textSecondary,
    boxShadow: `0 1px 2px ${t.shadowControlColor}`,
  },
  iconRailDivider: { height: 1, marginInline: 2, backgroundColor: t.strokeTertiary },
  panelSlot: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  panelSlotHidden: { display: "none" },
  sash: {
    position: "absolute",
    zIndex: 2,
    insetBlock: 0,
    insetInlineStart: -6,
    width: 12,
    borderStyle: "none",
    outlineStyle: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": t.fillGhostHover,
      ":focus-visible": t.fillGhostSelected,
    },
    cursor: "col-resize",
    touchAction: "none",
    WebkitAppRegion: "no-drag",
  },
  sashActive: { backgroundColor: t.fillPrimary, opacity: 0.25 },
});
