import { button, glyph } from "@nyte-ai/ui/schema.stylex";
import { create } from "@stylexjs/stylex";
import { motion, role, type } from "@nyte-ai/ui/vars.stylex";

export const stripStyles = create({
  strip: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    flex: 1,
    minWidth: 0,
    height: "100%",
    WebkitAppRegion: "drag",
  },
  list: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    flex: "0 1 auto",
    minWidth: 0,
    height: "100%",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
  },
  /** Tabs share the row up to 240px each and shrink to 72px before the list scrolls. */
  slot: { display: "flex", flex: "0 1 240px", minWidth: 72, WebkitAppRegion: "no-drag" },
  slotPinned: { flex: "none", minWidth: 0 },
  tab: {
    "--_close-opacity": { default: "0", ":hover": "1", ":focus-within": "1" },
    position: "relative",
    display: "flex",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
    height: button.heightMd,
    borderRadius: button.radiusMd,
    backgroundColor: { default: "transparent", ":hover": role.bgHover },
    color: { default: role.contentSecondary, ":hover": role.contentPrimary },
  },
  tabClosable: { paddingInlineEnd: 4 },
  tabPinned: { flex: "none", width: button.heightMd },
  /** The main area is a card set into the chrome; the active tab wears the card. */
  tabActive: {
    backgroundColor: { default: role.bgBase, ":hover": role.bgBase },
    boxShadow: `inset 0 0 0 1px ${role.borderSecondaryTranslucent}`,
    color: role.contentPrimary,
  },
  tabButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    height: "100%",
    paddingBlock: 0,
    paddingInlineStart: 10,
    paddingInlineEnd: 6,
    borderRadius: button.radiusMd,
    backgroundColor: "transparent",
    color: "inherit",
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
    cursor: "default",
    userSelect: "none",
  },
  /** Without a close button the label keeps the same distance from both edges. */
  tabButtonUnclosable: { paddingInlineEnd: 10 },
  /** A pinned tab is its glyph alone, centred in a square. */
  tabButtonPinned: { justifyContent: "center", paddingInline: 0 },
  glyph: {
    display: { default: "grid", ":empty": "none" },
    placeItems: "center",
    width: glyph.box,
    height: glyph.box,
    flexShrink: 0,
  },
  label: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  splitMark: { display: "inline-flex", flexShrink: 0, color: role.contentTertiary },
  unread: {
    width: 6,
    height: 6,
    flexShrink: 0,
    borderRadius: "50%",
    backgroundColor: role.contentInteractiveTertiary,
  },
  unreadPinned: { position: "absolute", insetBlockStart: 4, insetInlineEnd: 4 },
  close: { display: "inline-flex", flexShrink: 0, opacity: "var(--_close-opacity)" },
  closeVisible: { opacity: 1 },
  control: { display: "inline-flex", flexShrink: 0, WebkitAppRegion: "no-drag" },
  shortcut: { display: "inline-flex", alignItems: "center", gap: 8 },
  keys: { display: "inline-flex", gap: 2 },
  key: {
    transitionProperty: "background-color, color",
    transitionDuration: motion.durationInstant,
  },
  held: { backgroundColor: role.bgInteractivePrimaryTranslucent, color: role.contentPrimary },
});
