import { readFileSync } from "node:fs";
import path from "node:path";

/*
 * Reads the generated `--nyte-*` variables straight from @nyte-ai/ui so the
 * table can never disagree with the package. The CSS file is regenerated by
 * `pnpm --dir packages/ui sync:tokens` and checked by `check:tokens`.
 */
// Resolved by path rather than through the package export so the bundler
// treats it as data, not as a stylesheet to be placed in a chunk.
const tokensCss = readFileSync(
  path.resolve(process.cwd(), "../ui/src/platform-tokens.css"),
  "utf8",
);

const declaration = /(--nyte-[a-z0-9-]+):\s*([^;]+);/g;

function readTokens(prefix: string) {
  const rows: { name: string; value: string }[] = [];
  for (const match of tokensCss.matchAll(declaration)) {
    const [, name, value] = match;
    if (name?.startsWith(prefix) && value) rows.push({ name, value: value.trim() });
  }
  return rows;
}

function isColor(value: string) {
  return value.startsWith("light-dark(") || value.startsWith("#");
}

export function TokenTable({ prefix }: { prefix: string }) {
  const rows = readTokens(prefix);

  return (
    <table className="cloud-token-table">
      <thead>
        <tr>
          <th>Token</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((row) => (
          <tr key={row.name}>
            <td>
              <code>{row.name}</code>
            </td>
            <td>
              {isColor(row.value) && (
                <span
                  aria-hidden
                  className="cloud-swatch"
                  style={{ background: `var(${row.name})` }}
                />
              )}
              <code>{row.value}</code>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
