/**
 * The desktop's app layout measurements, keyed by the custom property each
 * compiles to. A control or row size reads the component token it is; the
 * rest are Nyte's own. The design tokens they build on live in
 * `@nyte-ai/ui/tokens.stylex`; importing this file ships both.
 */
import { defineVars } from "@stylexjs/stylex";
import "@nyte-ai/ui/tokens.stylex";

/** The measurements `schema.stylex.ts` names; each is documented at its handle. */
export const layout = defineVars({
  "--nyte-titlebar-height": "35px",
  // Main and preload keep the traffic lights in this lane at any zoom.
  "--nyte-titlebar-traffic-light-inset": "calc(72px / var(--nyte-window-zoom, 1))",
  "--nyte-sidebar-width": "220px",
  "--nyte-sidebar-handle-width": "8px",
  "--nyte-sidebar-row-height": "var(--nyte-row-height-md)",
  "--nyte-sidebar-gutter": "8px",
  "--nyte-sidebar-row-padding-inline": "var(--nyte-row-padding-inline-md)",
  "--nyte-sidebar-row-gap": "var(--nyte-row-gap)",
  "--nyte-sidebar-section-gap": "8px",
  "--nyte-sidebar-list-gap": "1px",
  "--nyte-sidebar-icon-slot": "20px",
  "--nyte-sidebar-action-size": "var(--nyte-btn-height-sm)",
  "--nyte-sidebar-trailing-width": "44px",
  "--nyte-sidebar-meta-width": "40px",
  "--nyte-settings-content-width": "680px",
  "--nyte-settings-content-gutter": "16px",
  "--nyte-settings-row-min-height": "61px",
  "--nyte-settings-slider-row-min-height": "76px",
  "--nyte-settings-section-gap": "28px",
  "--nyte-settings-card-gap": "8px",
  "--nyte-settings-row-padding": "12px",
  "--nyte-settings-control-height": "var(--nyte-btn-height-sm)",
  "--nyte-settings-control-max-width": "160px",
  "--nyte-settings-page-title-size": "calc(var(--nyte-font-size-base) + 4px)",
  "--nyte-settings-page-title-line-height": "calc(var(--nyte-font-size-base) + 8px)",
  "--nyte-suggestion-item-height": "var(--nyte-row-height-md)",
  "--nyte-suggestion-item-gap": "8px",
  "--nyte-conversation-measure": "840px",
  "--nyte-prose-measure": "840px",
  "--nyte-prose-paragraph-gap": "16px",
  "--nyte-conversation-gutter": "16px",
  "--nyte-conversation-header-height": "35px",
  "--nyte-conversation-turn-gap": "14px",
  "--nyte-conversation-row-gap": "8px",
  "--nyte-conversation-row-min-height": "22px",
  "--nyte-conversation-edge-fade": "32px",
  "--nyte-composer-inset": "14px",
  "--nyte-composer-new-chat-radius": "22px",
  "--nyte-composer-expanded-radius": "18px",
  "--nyte-tray-radius": "var(--nyte-radius-12)",
  "--nyte-tray-gap": "6px",
  "--nyte-tray-padding-inline": "12px",
  "--nyte-tray-header-height": "36px",
  "--nyte-tray-row-height": "var(--nyte-row-height-md)",
  "--nyte-tray-row-inset": "6px",
  "--nyte-workbench-rail-width": "210px",
  "--nyte-workbench-rail-gap": "16px",
  "--nyte-workbench-row-height": "var(--nyte-row-height-md)",
  "--nyte-workbench-row-gap": "var(--nyte-row-gap)",
  "--nyte-workbench-row-padding-inline": "6px",
  "--nyte-workbench-heading-height": "24px",
  "--nyte-workbench-panel-width": "384px",
  "--nyte-workbench-header-height": "35px",
  "--nyte-workbench-file-list-width": "200px",
  "--nyte-pane-sash-size": "9px",
  "--nyte-pane-divider-gap": "5px",
  "--nyte-diff-line-height": "20px",
  "--nyte-diff-preview-max-height": "min(480px, 60vh)",
});
