import { create } from "@stylexjs/stylex";
import { role, type } from "@nyte-ai/ui/vars.stylex";

export const terminalStyles = create({
  root: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    backgroundColor: role.bgBase,
  },
  body: { position: "relative", flex: 1, minHeight: 0, minWidth: 0 },
  panel: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    outlineStyle: "none",
    backgroundColor: role.bgBase,
  },
  hidden: { display: "none" },
  canvas: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    paddingBlock: 8,
    paddingInline: 6,
    overflow: "clip",
  },
  state: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingBlock: 8,
    paddingInline: 12,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  failure: { color: role.contentSecondary },
  empty: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    textAlign: "center",
  },
});
