import { create } from "@stylexjs/stylex";
import { layer, row } from "@nyte-ai/ui/schema.stylex";
import { workbench } from "../theme/schema.stylex.ts";
import { appearance, role, shadow, type } from "@nyte-ai/ui/vars.stylex";

export const workbenchStyles = create({
  root: {
    position: "relative",
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    flexShrink: 0,
    backgroundColor: role.bgBase,
  },
  panel: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    backgroundColor: role.bgBase,
  },
  /** The header row every panel opens with: its controls and, at the end, its side-tree toggle. */
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: { default: 2, "@media (pointer: coarse)": 8 },
    minHeight: workbench.headerHeight,
    paddingBlock: { default: 0, "@media (pointer: coarse)": 4 },
    flexShrink: 0,
    paddingInline: 6,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: role.borderSecondaryTranslucent,
  },
  panelOpen: {
    minWidth: workbench.panelWidth,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: role.borderSecondaryTranslucent,
  },
  railHost: { width: workbench.railWidth, minWidth: workbench.railWidth },
  railHostCompact: {
    width: { default: 46, "@media (pointer: coarse)": 64 },
    minWidth: { default: 46, "@media (pointer: coarse)": 64 },
  },
  panelOverlay: {
    position: "absolute",
    zIndex: layer.workbench,
    insetBlock: 0,
    insetInlineEnd: 0,
    minWidth: 0,
    maxWidth: "100vw",
    boxShadow: shadow.shadowWorkbench,
  },
  panelHidden: { display: "none" },
  panelBody: { display: "flex", flex: 1, minWidth: 0, minHeight: 0, flexDirection: "column" },
  rail: {
    display: "flex",
    flexDirection: "column",
    gap: workbench.railGap,
    width: "100%",
    minWidth: 0,
    paddingBlock: 4,
    paddingInline: 8,
    color: role.contentSecondary,
  },
  railSection: {
    display: "flex",
    flexDirection: "column",
    gap: { default: 1, "@media (pointer: coarse)": 8 },
    minWidth: 0,
  },
  railHeading: {
    display: "flex",
    alignItems: "center",
    minHeight: workbench.headingHeight,
    paddingInline: workbench.rowPaddingInline,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  railHeadingText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chevronLayout: { marginInlineEnd: -4 },
  doubleChevron: { display: "inline-flex", alignItems: "center" },
  doubleChevronBack: { transform: "scaleX(-1)" },
  doubleChevronTrail: { display: "inline-flex", marginInlineStart: -4 },
  railRow: {
    minHeight: row.heightMd,
    gap: workbench.rowGap,
    "--_row-padding-inline": workbench.rowPaddingInline,
    paddingBlock: 2,
    backgroundImage: { default: "none", ":active": role.layerPressed },
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
  },
  // The stats follow the label rather than the row's end.
  railLabel: { flex: "0 1 auto" },
  railStats: {
    display: "inline-flex",
    gap: workbench.rowGap,
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  },
  railAdded: { color: role.contentSecondary },
  railRemoved: { color: role.contentSecondary },
  iconRail: {
    display: "flex",
    flexDirection: "column",
    gap: { default: 1, "@media (pointer: coarse)": 8 },
    boxSizing: "border-box",
    width: { default: 34, "@media (pointer: coarse)": 52 },
    marginBlockStart: 4,
    marginInline: 6,
    padding: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    borderRadius: 10,
    backgroundColor: role.bgElevated,
    color: role.contentSecondary,
    boxShadow: shadow.shadowSm,
  },
  iconRailDivider: { height: 1, marginInline: 2, backgroundColor: role.borderSecondaryTranslucent },
  panelSlot: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  panelSlotHidden: { display: "none" },
  sash: {
    position: "absolute",
    zIndex: 2,
    insetBlock: 0,
    insetInlineStart: { default: -24, "@media (pointer: coarse)": -44 },
    width: { default: 24, "@media (pointer: coarse)": 44 },
    borderStyle: "none",
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 1,
    outlineColor: appearance.focusRing,
    outlineOffset: -1,
    backgroundColor: "transparent",
    "--_sash-rule": {
      default: role.borderSecondaryTranslucent,
      ":hover": role.bgInteractiveStrong,
      ":focus-visible": role.bgInteractiveStrong,
    },
    "::after": {
      content: "''",
      position: "absolute",
      insetBlock: 0,
      insetInlineEnd: 0,
      width: 1,
      backgroundColor: "var(--_sash-rule)",
    },
    cursor: "col-resize",
    touchAction: "none",
    WebkitAppRegion: "no-drag",
  },
  sashActive: { "--_sash-rule": role.bgInteractiveStrong },
  treeTheme: {
    "--trees-bg-override": role.bgBase,
    "--trees-bg-muted-override": role.bgHover,
    "--trees-fg-override": role.contentSecondary,
    "--trees-fg-muted-override": role.contentTertiary,
    "--trees-accent-override": role.contentInteractiveTertiary,
    "--trees-border-color-override": role.borderSecondaryTranslucent,
    "--trees-indent-guide-bg-override": role.borderSecondaryTranslucent,
    "--trees-selected-bg-override": role.bgInteractiveSecondaryTranslucent,
    "--trees-selected-fg-override": role.contentPrimary,
    "--trees-focus-ring-color-override": appearance.focusRing,
    "--trees-input-bg-override": role.bgElevated,
    "--trees-search-bg-override": role.bgElevated,
    "--trees-search-fg-override": role.contentPrimary,
    "--trees-scrollbar-thumb-override": role.scrollbarThumb,
    "--trees-font-family-override": type.fontSans,
    "--trees-font-size-override": type.fontSm,
    "--trees-status-ignored-override": role.contentDisabled,
  },
  treeStatus: (added: string, modified: string, deleted: string) => ({
    "--trees-status-added-override": added,
    "--trees-status-untracked-override": added,
    "--trees-status-modified-override": modified,
    "--trees-status-renamed-override": modified,
    "--trees-status-deleted-override": deleted,
  }),
});
