import { create } from "@stylexjs/stylex";
import { layer } from "@nyte-ai/ui/schema.stylex";
import { workbench } from "../theme/schema.stylex.ts";
import { t } from "@nyte-ai/ui/vars.stylex";

export const workbenchStyles = create({
  root: {
    position: "relative",
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    flexShrink: 0,
    backgroundColor: t.bgPage,
  },
  panel: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    backgroundColor: t.bgPage,
  },
  /** The header row every panel opens with: its controls and, at the end, its side-tree toggle. */
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    height: workbench.headerHeight,
    flexShrink: 0,
    paddingInline: 6,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.strokeSecondary,
  },
  panelOpen: {
    minWidth: workbench.panelWidth,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.strokeSecondary,
  },
  railHost: { width: workbench.railWidth, minWidth: workbench.railWidth },
  railHostCompact: { width: 46, minWidth: 46 },
  panelOverlay: {
    position: "absolute",
    zIndex: layer.workbench,
    insetBlock: 0,
    insetInlineEnd: 0,
    minWidth: 0,
    maxWidth: "100vw",
    boxShadow: t.shadowWorkbench,
  },
  panelHidden: { display: "none" },
  panelBody: { display: "flex", flex: 1, minWidth: 0, minHeight: 0, flexDirection: "column" },
  rail: {
    display: "flex",
    flexDirection: "column",
    gap: workbench.railGap,
    width: "100%",
    minWidth: 0,
    paddingBlock: 4,
    paddingInline: 8,
    color: t.textSecondary,
  },
  railSection: { display: "flex", flexDirection: "column", gap: 1, minWidth: 0 },
  railHeading: {
    display: "flex",
    alignItems: "center",
    minHeight: workbench.headingHeight,
    paddingInline: workbench.rowPaddingInline,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  railHeadingText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chevronLayout: { marginInlineEnd: -4 },
  doubleChevron: { display: "inline-flex", alignItems: "center" },
  doubleChevronBack: { transform: "scaleX(-1)" },
  doubleChevronTrail: { display: "inline-flex", marginInlineStart: -4 },
  railRow: {
    "--nyte-row-height": workbench.rowHeight,
    "--nyte-row-gap": workbench.rowGap,
    "--nyte-row-padding-inline": workbench.rowPaddingInline,
    paddingBlock: 2,
    backgroundImage: { default: "none", ":active": t.layerPressed },
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  // The stats follow the label rather than the row's end.
  railLabel: { flex: "0 1 auto" },
  railStats: {
    display: "inline-flex",
    gap: workbench.rowGap,
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  },
  railAdded: { color: t.textSuccess },
  railRemoved: { color: t.textDanger },
  iconRail: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    boxSizing: "border-box",
    width: 34,
    marginBlockStart: 4,
    marginInline: 6,
    padding: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    borderRadius: 10,
    backgroundColor: t.bgRaised,
    color: t.textSecondary,
    boxShadow: t.shadowButton,
  },
  iconRailDivider: { height: 1, marginInline: 2, backgroundColor: t.strokeSecondary },
  panelSlot: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  panelSlotHidden: { display: "none" },
  sash: {
    position: "absolute",
    zIndex: 2,
    insetBlock: 0,
    insetInlineStart: -6,
    width: 12,
    borderStyle: "none",
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 1,
    outlineColor: t.focusRing,
    outlineOffset: -1,
    backgroundColor: { default: "transparent", ":hover": t.fillHover },
    cursor: "col-resize",
    touchAction: "none",
    WebkitAppRegion: "no-drag",
  },
  sashActive: { backgroundColor: t.strokeFocused },
  treeTheme: {
    "--trees-bg-override": t.bgPage,
    "--trees-bg-muted-override": t.fillHover,
    "--trees-fg-override": t.textSecondary,
    "--trees-fg-muted-override": t.textTertiary,
    "--trees-accent-override": t.accent,
    "--trees-border-color-override": t.strokeSecondary,
    "--trees-indent-guide-bg-override": t.strokeTertiary,
    "--trees-selected-bg-override": t.fillSelected,
    "--trees-selected-fg-override": t.textPrimary,
    "--trees-focus-ring-color-override": t.focusRing,
    "--trees-input-bg-override": t.bgRaised,
    "--trees-search-bg-override": t.bgRaised,
    "--trees-search-fg-override": t.textPrimary,
    "--trees-scrollbar-thumb-override": t.scrollbarThumb,
    "--trees-font-family-override": t.fontSans,
    "--trees-font-size-override": t.fontSm,
    "--trees-status-added-override": t.textSuccess,
    "--trees-status-untracked-override": t.textSuccess,
    "--trees-status-modified-override": t.textWarning,
    "--trees-status-renamed-override": t.textWarning,
    "--trees-status-deleted-override": t.textDanger,
    "--trees-status-ignored-override": t.textQuaternary,
  },
});
