import { create } from "@stylexjs/stylex";
import { layer } from "@nyte-ai/ui/schema.stylex";
import { workbench } from "../theme/schema.stylex.ts";
import { ramp, t } from "@nyte-ai/ui/vars.stylex";

export const workbenchStyles = create({
  root: {
    position: "relative",
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    flexShrink: 0,
    backgroundColor: t.bgBase,
  },
  panel: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    backgroundColor: t.bgBase,
  },
  /** The header row every panel opens with: its controls and, at the end, its side-tree toggle. */
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    height: workbench.headerHeight,
    flexShrink: 0,
    paddingInline: 6,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.borderSecondaryTranslucent,
  },
  panelOpen: {
    minWidth: workbench.panelWidth,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: t.borderSecondaryTranslucent,
  },
  railHost: { width: workbench.railWidth, minWidth: workbench.railWidth },
  railHostCompact: { width: 46, minWidth: 46 },
  panelOverlay: {
    position: "absolute",
    zIndex: layer.workbench,
    insetBlock: 0,
    insetInlineEnd: 0,
    minWidth: 0,
    maxWidth: "100vw",
    boxShadow: t.shadowWorkbench,
  },
  panelHidden: { display: "none" },
  panelBody: { display: "flex", flex: 1, minWidth: 0, minHeight: 0, flexDirection: "column" },
  rail: {
    display: "flex",
    flexDirection: "column",
    gap: workbench.railGap,
    width: "100%",
    minWidth: 0,
    paddingBlock: 4,
    paddingInline: 8,
    color: t.contentSecondary,
  },
  railSection: { display: "flex", flexDirection: "column", gap: 1, minWidth: 0 },
  railHeading: {
    display: "flex",
    alignItems: "center",
    minHeight: workbench.headingHeight,
    paddingInline: workbench.rowPaddingInline,
    color: t.contentSecondary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  railHeadingText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chevronLayout: { marginInlineEnd: -4 },
  doubleChevron: { display: "inline-flex", alignItems: "center" },
  doubleChevronBack: { transform: "scaleX(-1)" },
  doubleChevronTrail: { display: "inline-flex", marginInlineStart: -4 },
  railRow: {
    "--nyte-row-height": workbench.rowHeight,
    "--nyte-row-gap": workbench.rowGap,
    "--nyte-row-padding-inline": workbench.rowPaddingInline,
    paddingBlock: 2,
    backgroundImage: { default: "none", ":active": t.layerPressed },
    color: t.contentSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  // The stats follow the label rather than the row's end.
  railLabel: { flex: "0 1 auto" },
  railStats: {
    display: "inline-flex",
    gap: workbench.rowGap,
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  },
  railAdded: { color: t.intentSuccessContent },
  railRemoved: { color: t.intentDangerContent },
  iconRail: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    boxSizing: "border-box",
    width: 34,
    marginBlockStart: 4,
    marginInline: 6,
    padding: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.borderSecondaryTranslucent,
    borderRadius: 10,
    backgroundColor: t.bgElevated,
    color: t.contentSecondary,
    boxShadow: t.shadowSm,
  },
  iconRailDivider: { height: 1, marginInline: 2, backgroundColor: t.borderSecondaryTranslucent },
  panelSlot: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  panelSlotHidden: { display: "none" },
  sash: {
    position: "absolute",
    zIndex: 2,
    insetBlock: 0,
    insetInlineStart: -6,
    width: 12,
    borderStyle: "none",
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 1,
    outlineColor: t.focusRing,
    outlineOffset: -1,
    backgroundColor: { default: "transparent", ":hover": t.bgHover },
    cursor: "col-resize",
    touchAction: "none",
    WebkitAppRegion: "no-drag",
  },
  sashActive: { backgroundColor: ramp.blue80 },
  treeTheme: {
    "--trees-bg-override": t.bgBase,
    "--trees-bg-muted-override": t.bgHover,
    "--trees-fg-override": t.contentSecondary,
    "--trees-fg-muted-override": t.contentTertiary,
    "--trees-accent-override": ramp.blue80,
    "--trees-border-color-override": t.borderSecondaryTranslucent,
    "--trees-indent-guide-bg-override": t.borderSecondaryTranslucent,
    "--trees-selected-bg-override": t.bgInteractiveSecondaryTranslucent,
    "--trees-selected-fg-override": t.contentPrimary,
    "--trees-focus-ring-color-override": t.focusRing,
    "--trees-input-bg-override": t.bgElevated,
    "--trees-search-bg-override": t.bgElevated,
    "--trees-search-fg-override": t.contentPrimary,
    "--trees-scrollbar-thumb-override": t.scrollbarThumb,
    "--trees-font-family-override": t.fontSans,
    "--trees-font-size-override": t.fontSm,
    "--trees-status-added-override": t.intentSuccessContent,
    "--trees-status-untracked-override": t.intentSuccessContent,
    "--trees-status-modified-override": t.intentWarningContent,
    "--trees-status-renamed-override": t.intentWarningContent,
    "--trees-status-deleted-override": t.intentDangerContent,
    "--trees-status-ignored-override": t.contentDisabled,
  },
});
