import { avatar, radius } from "@nyte-ai/ui/schema.stylex";
import { settings } from "@nyte-ai/app/theme/schema.stylex.ts";
import { create } from "@stylexjs/stylex";
import { role, type } from "@nyte-ai/ui/vars.stylex";

export const customizeStyles = create({
  surface: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    backgroundColor: role.bgBase,
    containerType: "inline-size",
  },
  column: {
    display: "flex",
    flexDirection: "column",
    gap: settings.sectionGap,
    width: "100%",
    maxWidth: settings.contentWidth,
    marginInline: "auto",
    paddingInline: settings.contentGutter,
    paddingBlock: "32px 64px",
  },
  pageCopy: { display: "flex", flexDirection: "column", gap: 4, flex: 1, minWidth: 0 },
  sectionHeader: { display: "flex", alignItems: "flex-end", gap: 16, paddingInline: 4 },
  sectionCopy: { display: "flex", flexDirection: "column", gap: 4, flex: 1, minWidth: 0 },
  code: {
    fontFamily: type.fontMono,
    fontSize: "0.92em",
    color: role.contentPrimary,
  },

  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 8,
  },
  subheading: {
    paddingInline: 4,
    paddingBlockStart: 8,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  card: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
    padding: 12,
    borderWidth: 0,
    borderRadius: radius.card,
    backgroundColor: {
      default: role.bgMutedTranslucent,
      ":hover": { "@media (hover: hover) and (pointer: fine)": role.bgHover },
    },
    color: "inherit",
    font: "inherit",
    textAlign: "start",
    cursor: "pointer",
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 1,
    outlineColor: role.borderInteractivePrimary,
  },
  tile: {
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    width: avatar.lg,
    height: avatar.lg,
    borderRadius: radius.control,
    backgroundColor: role.bgBase,
    boxShadow: `inset 0 0 0 1px ${role.borderSecondaryTranslucent}`,
    color: role.contentPrimary,
  },
  tileLarge: { width: 48, height: 48, borderRadius: radius.card },
  cardCopy: { display: "flex", flexDirection: "column", minWidth: 0, flex: 1 },
  cardTitle: {
    overflow: "hidden",
    color: role.contentPrimary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
    whiteSpace: "nowrap",
  },
  tag: {
    paddingInline: 6,
    borderRadius: radius.indicator,
    backgroundColor: role.bgMutedTranslucent,
    color: role.contentSecondary,
    fontSize: type.fontXs,
    lineHeight: type.leadingSm,
  },

  empty: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: 16,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: role.borderPrimaryTranslucent,
    borderRadius: radius.card,
  },
  emptyCopy: { display: "flex", flexDirection: "column", gap: 2, flex: 1, minWidth: 0 },
  emptyTitle: { color: role.contentPrimary },
  muted: { color: role.contentSecondary },
  actions: { display: "flex", alignItems: "center", gap: 4, flexShrink: 0 },

  folderHeading: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingBlock: 8,
    paddingInline: "20px 12px",
    borderBlockEndWidth: 1,
    borderBlockEndStyle: "solid",
    borderBlockEndColor: role.borderSecondaryTranslucent,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  folderPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    fontFamily: type.fontMono,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  back: { alignSelf: "flex-start", marginInlineStart: -8, marginBlockEnd: -24 },
  detailHeader: { display: "flex", alignItems: "center", gap: 16 },
  frame: { height: "calc(100dvh - 96px)", minHeight: 640 },
  facts: {
    display: "flex",
    alignItems: "center",
    gap: 32,
    padding: settings.rowPadding,
    borderRadius: radius.card,
    backgroundColor: role.bgMutedTranslucent,
  },
  fact: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 },
  factLabel: {
    color: role.contentSecondary,
    fontSize: type.fontXs,
    lineHeight: type.leadingXs,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  factValue: {
    overflow: "hidden",
    color: role.contentPrimary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  factPath: { fontFamily: type.fontMono, fontSize: type.fontSm },
  factGrow: { flex: 1 },

  contribution: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    padding: settings.rowPadding,
    "::before": {
      position: "absolute",
      insetInline: settings.rowPaddingInline,
      insetBlockStart: 0,
      height: 1,
      backgroundColor: role.borderSecondaryTranslucent,
      content: '""',
    },
    position: "relative",
    ":first-child::before": { display: "none" },
  },
  contributionName: {
    flexShrink: 0,
    minWidth: 160,
    color: role.contentPrimary,
    fontFamily: type.fontMono,
    fontSize: type.fontSm,
  },
  contributionDescription: { color: role.contentSecondary, minWidth: 0 },

  failure: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 16,
    borderRadius: radius.card,
    backgroundColor: role.bgMutedTranslucent,
    boxShadow: `inset 0 0 0 1px ${role.borderInteractivePrimaryTranslucent}`,
  },
  failureHead: { display: "flex", alignItems: "center", gap: 8, color: role.contentPrimary },
  failureIcon: { color: role.contentInteractivePrimary },
  trace: {
    margin: 0,
    padding: 12,
    overflowX: "auto",
    borderRadius: radius.control,
    backgroundColor: role.bgBase,
    color: role.contentSecondary,
    fontFamily: type.fontMono,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  listRow: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    padding: "12px 16px",
    borderWidth: 0,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": role.bgHover },
    },
    color: "inherit",
    font: "inherit",
    textAlign: "start",
    cursor: "pointer",
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 1,
    outlineColor: role.borderInteractivePrimary,
    outlineOffset: -1,
    "::before": {
      position: "absolute",
      insetInline: 16,
      insetBlockStart: 0,
      height: 1,
      backgroundColor: role.borderSecondaryTranslucent,
      content: '""',
    },
    ":first-child::before": { display: "none" },
  },
  listDescription: {
    overflow: "hidden",
    color: role.contentSecondary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chevron: { color: role.contentTertiary },
});
