import {
  Icon3dBoxTopDefault,
  IconAnalyticsDefault,
  IconAppsDefault,
  IconArchive1Default,
  IconArrowCornerDownLeftDefault,
  IconArrowDownDefault,
  IconArrowLeftDefault,
  IconArrowRightDefault,
  IconArrowRotateClockwiseDefault,
  IconArrowUpDefault,
  IconArrowWallLeftDefault,
  IconBellDefault,
  IconBlocksDefault,
  IconBoltDefault,
  IconBookDefault,
  IconBranchDefault,
  IconBubbleQuestionDefault,
  IconBugDefault,
  IconBuildingBlocksDefault,
  IconCanvasGridDefault,
  IconChangesDefault,
  IconCheckmark1MediumDefault,
  IconChevronDownMediumDefault,
  IconChevronRightMediumDefault,
  IconCircleXDefault,
  IconCirclesThreeDefault,
  IconClaudeaiDefault,
  IconClipboardDefault,
  IconCloudApiDefault,
  IconCloudSimpleDefault,
  IconCodeBracketsDefault,
  IconCollaborationPointerRightDefault,
  IconComputerUseDefault,
  IconConsoleDefault,
  IconCrossLargeDefault,
  IconCrossSmallDefault,
  IconCursorAiDefault,
  IconDevicesDefault,
  IconDotGrid1x3HorizontalTightDefault,
  IconDotGrid1x3VerticalTightDefault,
  IconDotGrid2x3Default,
  IconDraftDefault,
  IconExclamationTriangleDefault,
  IconExpand45Default,
  IconEyeOpenDefault,
  IconFileTextDefault,
  IconFolder1Default,
  IconFolderAddRightDefault,
  IconFolderOpenDefault,
  IconGitDefault,
  IconGithubDefault,
  IconGlobeDefault,
  IconGrokDefault,
  IconInboxCheckedDefault,
  IconInboxEmptyDefault,
  IconJavascriptDefault,
  IconKey1Default,
  IconKeyboardDefault,
  IconKimiDefault,
  IconLayersTwoDefault,
  IconLayoutLeftRightDefault,
  IconLayoutTopBottomDefault,
  IconLinearDefault,
  IconListBulletsDefault,
  IconLoaderDefault,
  IconLockDefault,
  IconMacbookDefault,
  IconMagnifyingGlassDefault,
  IconMergedDefault,
  IconMinimize45Default,
  IconModelcontextprotocolDefault,
  IconOngoingDefault,
  IconOpenaiDefault,
  IconOpencodeDefault,
  IconPaperclip1Default,
  IconPencilLineDefault,
  IconPhoneDefault,
  IconPinDefault,
  IconPlusMediumDefault,
  IconPlusSmallDefault,
  IconPullRequestClosedSimpleDefault,
  IconPullRequestDefault,
  IconReactDefault,
  IconServerDefault,
  IconSettingsGear2Default,
  IconSettingsSliderHorDefault,
  IconShieldDefault,
  IconSidebarHiddenLeftWideDefault,
  IconSidebarHiddenRightWideDefault,
  IconSlackDefault,
  IconSparklesSoftDefault,
  IconSquareChecklistDefault,
  IconStopDefault,
  IconTestTubeDefault,
  IconTrashCanDefault,
  IconTrending4Default,
  IconTypescriptDefault,
  IconUnarchivDefault,
  IconUnpinDefault,
  IconUserDefault,
  IconUserKeyDefault,
  IconWebsiteDefault,
  IconWindowAppDefault,
  IconZaiDefault,
} from "central-icons-filled";
import {
  Icon3dBoxTop,
  IconAnalytics,
  IconApps,
  IconArchive1,
  IconArrowCornerDownLeft,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowRotateClockwise,
  IconArrowUp,
  IconArrowWallLeft,
  IconBell,
  IconBlocks,
  IconBolt,
  IconBook,
  IconBranch,
  IconBubbleQuestion,
  IconBug,
  IconBuildingBlocks,
  IconCanvasGrid,
  IconChanges,
  IconCheckmark1Medium,
  IconChevronDownMedium,
  IconChevronRightMedium,
  IconCircleX,
  IconCirclesThree,
  IconClaudeai,
  IconClipboard,
  IconCloudApi,
  IconCloudSimple,
  IconCodeBrackets,
  IconCollaborationPointerRight,
  IconComputerUse,
  IconConsole,
  IconCrossLarge,
  IconCrossSmall,
  IconCursorAi,
  IconDevices,
  IconDotGrid1x3HorizontalTight,
  IconDotGrid1x3VerticalTight,
  IconDotGrid2x3,
  IconDraft,
  IconExclamationTriangle,
  IconExpand45,
  IconEyeOpen,
  IconFileText,
  IconFolder1,
  IconFolderAddRight,
  IconFolderOpen,
  IconGit,
  IconGithub,
  IconGlobe,
  IconGrok,
  IconInboxChecked,
  IconInboxEmpty,
  IconJavascript,
  IconKey1,
  IconKeyboard,
  IconKimi,
  IconLayersTwo,
  IconLayoutLeftRight,
  IconLayoutTopBottom,
  IconLinear,
  IconListBullets,
  IconLoader,
  IconLock,
  IconMacbook,
  IconMagnifyingGlass,
  IconMerged,
  IconMinimize45,
  IconModelcontextprotocol,
  IconOngoing,
  IconOpenai,
  IconOpencode,
  IconPaperclip1,
  IconPencilLine,
  IconPhone,
  IconPin,
  IconPlusMedium,
  IconPlusSmall,
  IconPullRequest,
  IconPullRequestClosedSimple,
  IconReact,
  IconServer,
  IconSettingsGear2,
  IconSettingsSliderHor,
  IconShield,
  IconSidebarHiddenLeftWide,
  IconSidebarHiddenRightWide,
  IconSlack,
  IconSparklesSoft,
  IconSquareChecklist,
  IconStop,
  IconTestTube,
  IconTrashCan,
  IconTrending4,
  IconTypescript,
  IconUnarchiv,
  IconUnpin,
  IconUser,
  IconUserKey,
  IconWebsite,
  IconWindowApp,
  IconZai,
} from "central-icons";
import type { IconName } from "../src/icon.tsx";
import type { ComponentType } from "react";

export const iconReferences = [
  { name: "agent", outlined: IconCursorAi, filled: IconCursorAiDefault },
  { name: "apps", outlined: IconApps, filled: IconAppsDefault },
  { name: "archive", outlined: IconArchive1, filled: IconArchive1Default },
  { name: "arrow-down", outlined: IconArrowDown, filled: IconArrowDownDefault },
  { name: "arrow-left", outlined: IconArrowLeft, filled: IconArrowLeftDefault },
  { name: "arrow-right", outlined: IconArrowRight, filled: IconArrowRightDefault },
  { name: "arrow-up", outlined: IconArrowUp, filled: IconArrowUpDefault },
  { name: "arrow-wall-left", outlined: IconArrowWallLeft, filled: IconArrowWallLeftDefault },
  { name: "bell", outlined: IconBell, filled: IconBellDefault },
  { name: "bolt", outlined: IconBolt, filled: IconBoltDefault },
  { name: "book", outlined: IconBook, filled: IconBookDefault },
  { name: "box-3d", outlined: Icon3dBoxTop, filled: Icon3dBoxTopDefault },
  { name: "bubble-question", outlined: IconBubbleQuestion, filled: IconBubbleQuestionDefault },
  { name: "bug", outlined: IconBug, filled: IconBugDefault },
  { name: "canvas-grid", outlined: IconCanvasGrid, filled: IconCanvasGridDefault },
  { name: "chart", outlined: IconAnalytics, filled: IconAnalyticsDefault },
  { name: "checkmark", outlined: IconCheckmark1Medium, filled: IconCheckmark1MediumDefault },
  { name: "chevron-down", outlined: IconChevronDownMedium, filled: IconChevronDownMediumDefault },
  {
    name: "chevron-right",
    outlined: IconChevronRightMedium,
    filled: IconChevronRightMediumDefault,
  },
  { name: "circle-x", outlined: IconCircleX, filled: IconCircleXDefault },
  { name: "circles", outlined: IconCirclesThree, filled: IconCirclesThreeDefault },
  { name: "clock", outlined: IconOngoing, filled: IconOngoingDefault },
  { name: "close", outlined: IconCrossLarge, filled: IconCrossLargeDefault },
  { name: "cloud", outlined: IconCloudSimple, filled: IconCloudSimpleDefault },
  { name: "cloud-api", outlined: IconCloudApi, filled: IconCloudApiDefault },
  { name: "code-brackets", outlined: IconCodeBrackets, filled: IconCodeBracketsDefault },
  { name: "computer", outlined: IconComputerUse, filled: IconComputerUseDefault },
  { name: "console", outlined: IconConsole, filled: IconConsoleDefault },
  { name: "copy", outlined: IconClipboard, filled: IconClipboardDefault },
  { name: "customize", outlined: IconBlocks, filled: IconBlocksDefault },
  { name: "devices", outlined: IconDevices, filled: IconDevicesDefault },
  { name: "drag-handle", outlined: IconDotGrid2x3, filled: IconDotGrid2x3Default },
  { name: "draft", outlined: IconDraft, filled: IconDraftDefault },
  { name: "expand", outlined: IconExpand45, filled: IconExpand45Default },
  { name: "eye", outlined: IconEyeOpen, filled: IconEyeOpenDefault },
  { name: "file", outlined: IconChanges, filled: IconChangesDefault },
  { name: "file-text", outlined: IconFileText, filled: IconFileTextDefault },
  { name: "filters", outlined: IconSettingsSliderHor, filled: IconSettingsSliderHorDefault },
  { name: "folder", outlined: IconFolder1, filled: IconFolder1Default },
  { name: "folder-add", outlined: IconFolderAddRight, filled: IconFolderAddRightDefault },
  { name: "folder-open", outlined: IconFolderOpen, filled: IconFolderOpenDefault },
  { name: "git", outlined: IconGit, filled: IconGitDefault },
  { name: "git-branch", outlined: IconBranch, filled: IconBranchDefault },
  { name: "github", outlined: IconGithub, filled: IconGithubDefault },
  { name: "globe", outlined: IconGlobe, filled: IconGlobeDefault },
  { name: "grok", outlined: IconGrok, filled: IconGrokDefault },
  { name: "inbox-checked", outlined: IconInboxChecked, filled: IconInboxCheckedDefault },
  { name: "inbox-empty", outlined: IconInboxEmpty, filled: IconInboxEmptyDefault },
  { name: "javascript", outlined: IconJavascript, filled: IconJavascriptDefault },
  { name: "key", outlined: IconKey1, filled: IconKey1Default },
  { name: "keyboard", outlined: IconKeyboard, filled: IconKeyboardDefault },
  { name: "laptop", outlined: IconMacbook, filled: IconMacbookDefault },
  { name: "layers", outlined: IconLayersTwo, filled: IconLayersTwoDefault },
  { name: "linear", outlined: IconLinear, filled: IconLinearDefault },
  { name: "list", outlined: IconListBullets, filled: IconListBulletsDefault },
  { name: "loader", outlined: IconLoader, filled: IconLoaderDefault },
  { name: "lock", outlined: IconLock, filled: IconLockDefault },
  { name: "mcp", outlined: IconModelcontextprotocol, filled: IconModelcontextprotocolDefault },
  { name: "merged", outlined: IconMerged, filled: IconMergedDefault },
  { name: "minimize", outlined: IconMinimize45, filled: IconMinimize45Default },
  { name: "model-anthropic", outlined: IconClaudeai, filled: IconClaudeaiDefault },
  { name: "model-generic", outlined: IconGlobe, filled: IconGlobeDefault },
  { name: "model-kimi", outlined: IconKimi, filled: IconKimiDefault },
  { name: "model-openai", outlined: IconOpenai, filled: IconOpenaiDefault },
  { name: "model-zai", outlined: IconZai, filled: IconZaiDefault },
  {
    name: "more",
    outlined: IconDotGrid1x3VerticalTight,
    filled: IconDotGrid1x3VerticalTightDefault,
  },
  {
    name: "more-horizontal",
    outlined: IconDotGrid1x3HorizontalTight,
    filled: IconDotGrid1x3HorizontalTightDefault,
  },
  {
    name: "new-chat",
    outlined: IconCollaborationPointerRight,
    filled: IconCollaborationPointerRightDefault,
  },
  { name: "new-chat-folder", outlined: IconPlusMedium, filled: IconPlusMediumDefault },
  {
    name: "panel-left",
    outlined: IconSidebarHiddenLeftWide,
    filled: IconSidebarHiddenLeftWideDefault,
  },
  {
    name: "panel-right",
    outlined: IconSidebarHiddenRightWide,
    filled: IconSidebarHiddenRightWideDefault,
  },
  { name: "paperclip", outlined: IconPaperclip1, filled: IconPaperclip1Default },
  { name: "pencil", outlined: IconPencilLine, filled: IconPencilLineDefault },
  { name: "phone", outlined: IconPhone, filled: IconPhoneDefault },
  { name: "pin", outlined: IconPin, filled: IconPinDefault },
  { name: "plus", outlined: IconPlusSmall, filled: IconPlusSmallDefault },
  { name: "provider-opencode", outlined: IconOpencode, filled: IconOpencodeDefault },
  { name: "pull-request", outlined: IconPullRequest, filled: IconPullRequestDefault },
  {
    name: "pull-request-closed",
    outlined: IconPullRequestClosedSimple,
    filled: IconPullRequestClosedSimpleDefault,
  },
  { name: "react", outlined: IconReact, filled: IconReactDefault },
  { name: "refresh", outlined: IconArrowRotateClockwise, filled: IconArrowRotateClockwiseDefault },
  { name: "return", outlined: IconArrowCornerDownLeft, filled: IconArrowCornerDownLeftDefault },
  { name: "search", outlined: IconMagnifyingGlass, filled: IconMagnifyingGlassDefault },
  { name: "server", outlined: IconServer, filled: IconServerDefault },
  { name: "settings", outlined: IconSettingsGear2, filled: IconSettingsGear2Default },
  { name: "shield", outlined: IconShield, filled: IconShieldDefault },
  { name: "slack", outlined: IconSlack, filled: IconSlackDefault },
  { name: "skills", outlined: IconBuildingBlocks, filled: IconBuildingBlocksDefault },
  { name: "sparkle", outlined: IconSparklesSoft, filled: IconSparklesSoftDefault },
  { name: "split-down", outlined: IconLayoutTopBottom, filled: IconLayoutTopBottomDefault },
  { name: "split-right", outlined: IconLayoutLeftRight, filled: IconLayoutLeftRightDefault },
  { name: "square", outlined: IconStop, filled: IconStopDefault },
  { name: "square-checklist", outlined: IconSquareChecklist, filled: IconSquareChecklistDefault },
  { name: "test-tube", outlined: IconTestTube, filled: IconTestTubeDefault },
  { name: "trash", outlined: IconTrashCan, filled: IconTrashCanDefault },
  { name: "trending", outlined: IconTrending4, filled: IconTrending4Default },
  { name: "typescript", outlined: IconTypescript, filled: IconTypescriptDefault },
  { name: "unarchive", outlined: IconUnarchiv, filled: IconUnarchivDefault },
  { name: "unpin", outlined: IconUnpin, filled: IconUnpinDefault },
  { name: "user", outlined: IconUser, filled: IconUserDefault },
  { name: "user-key", outlined: IconUserKey, filled: IconUserKeyDefault },
  { name: "warning", outlined: IconExclamationTriangle, filled: IconExclamationTriangleDefault },
  { name: "website", outlined: IconWebsite, filled: IconWebsiteDefault },
  { name: "window-app", outlined: IconWindowApp, filled: IconWindowAppDefault },
  { name: "x", outlined: IconCrossSmall, filled: IconCrossSmallDefault },
] as const satisfies readonly {
  name: IconName;
  outlined: ComponentType<{ size?: number; mode?: "raw"; ariaHidden?: boolean }>;
  filled: ComponentType<{ size?: number; mode?: "raw"; ariaHidden?: boolean }>;
}[];
