/**
 * Conversation presentation has one StyleX owner. Renderers keep behavior and
 * semantics; this module keeps the shared hierarchy, geometry, and states
 * coherent across prose, tools, diffs, reasoning, and the composer.
 *
 * Based on https://github.com/b-nnett/grok-bot-0.18-reconstructed/blob/a9f633e09d49a85829b8236331b9e21f7e612634/frontend/src/recovered/features/conversation/workspace/view.css
 */
import { create, keyframes } from "@stylexjs/stylex";
import {
  button,
  clipboardPreview,
  glyph,
  layer,
  menu,
  row,
  radius,
  target,
} from "@nyte-ai/ui/schema.stylex";
import { conversation, diffView, pane, tray } from "../theme/schema.stylex.ts";
import { appearance, motion, role, shadow, type } from "@nyte-ai/ui/vars.stylex";

const CHIP_LABEL_FADE =
  "linear-gradient(to right, black calc(100% - 28px), transparent calc(100% - 8px))";

const caretBlink = keyframes({
  "0%, 49%": { opacity: 1 },
  "50%, 100%": { opacity: 0 },
});

const activityShine = keyframes({
  "0%": { backgroundPosition: "200% 0" },
  "100%": { backgroundPosition: "-200% 0" },
});

const textShimmer = keyframes({
  from: { backgroundPosition: "100% 0" },
  to: { backgroundPosition: "-100% 0" },
});

const ACTIVITY_SHIMMER = `linear-gradient(90deg, ${role.contentSecondary} 0%, ${role.contentSecondary} 28%, ${role.contentPrimary} 58%, ${role.contentSecondary} 76%, ${role.contentSecondary} 100%)`;

const CODE_RING = `inset 0 0 0 1px ${role.borderSecondaryTranslucent}`;

const COMPOSER_RING_DROP = `0 0 0 2px ${role.borderInteractivePrimary}`;
const COMPOSER_COMPACT_HEIGHT = 40;

export const proseStyles = create({
  root: {
    display: "flow-root",
    width: "100%",
    minWidth: 0,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    letterSpacing: type.letterLg,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  measure: { width: "100%", maxWidth: conversation.proseMeasure },
  paragraph: {
    marginInline: 0,
    marginBlockStart: {
      default: conversation.paragraphGap,
      ":is(h1 + p, h2 + p, h3 + p, h4 + p, h5 + p, h6 + p)": 4,
      ":is(li > p)": 0,
      ":first-child": 0,
    },
    marginBlockEnd: {
      default: conversation.paragraphGap,
      ":has(+ ul, + ol)": 8,
      ":has(+ figure, + blockquote, + [data-prose-table])": 12,
      ":is(li > p)": 0,
      ":last-child": 0,
    },
    whiteSpace: "normal",
  },
  heading: {
    marginInline: 0,
    marginBlockStart: { default: type.leadingLg, ":first-child": 0 },
    marginBlockEnd: { default: 4, ":last-child": 0 },
    fontWeight: 590,
    lineHeight: 1.42,
    textWrap: "balance",
  },
  h1: { fontSize: "1.214em" },
  h2: { fontSize: "1.214em" },
  h3: { fontSize: "1.133em" },
  h4: { fontSize: "1em", marginBlockStart: { default: 12, ":first-child": 0 } },
  h5: { fontSize: "0.866em", color: role.contentSecondary },
  h6: { fontSize: "0.8em", color: role.contentSecondary },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginInline: 0,
    marginBlockStart: { default: 8, ":is(li > ul, li > ol)": 4, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    paddingInlineStart: "2em",
  },
  listItem: { whiteSpace: "normal" },
  strong: { color: `var(--_prose-strong-color, ${role.contentPrimary})`, fontWeight: 590 },
  inlineCode: {
    paddingInline: { default: 2, ":is(a code)": 0 },
    paddingBlock: { default: 1, ":is(a code)": 0 },
    borderRadius: { default: radius.indicator, ":is(a code)": 0 },
    backgroundColor: { default: role.bgMutedTranslucent, ":is(a code)": "transparent" },
    color: "inherit",
    fontFamily: type.fontMono,
    fontSize: "0.9em",
    letterSpacing: "normal",
    lineHeight: "inherit",
    whiteSpace: "break-spaces",
    overflowWrap: "break-word",
    wordBreak: "normal",
    boxDecorationBreak: "clone",
  },
  link: {
    color: role.contentSecondary,
    backgroundColor: {
      default: "transparent",
      ":hover": {
        "@media (hover: hover) and (pointer: fine)": role.bgInteractiveSecondaryTranslucent,
      },
    },
    display: "inline",
    marginInline: -2,
    paddingInline: 2,
    paddingBlock: 2,
    borderRadius: radius.indicator,
    fontWeight: 500,
    textDecorationLine: "none",
    boxDecorationBreak: "clone",
    cursor: appearance.cursorInteractive,
    transitionProperty: "background-color, color",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
  linkLead: { whiteSpace: "nowrap" },
  linkIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "1em",
    height: "1em",
    marginInlineEnd: "0.3em",
    overflow: "visible",
    verticalAlign: "middle",
    transform: "translateY(-0.085em)",
    userSelect: "none",
  },
  blockquote: {
    marginInline: 0,
    marginBlockStart: { default: 12, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    paddingInlineStart: 12,
    borderInlineStartWidth: 2,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: role.borderPrimaryTranslucent,
    color: role.contentSecondary,
  },
  rule: {
    width: "100%",
    maxWidth: conversation.proseMeasure,
    height: 1,
    marginBlock: 8,
    borderStyle: "none",
    backgroundColor: role.borderSecondaryTranslucent,
  },
  tableWrap: {
    marginBlockStart: { default: 12, ":first-child": 0 },
    marginBlockEnd: { default: 16, ":last-child": 0 },
    width: "100%",
    maxWidth: "100%",
    overflowX: "auto",
    // A horizontal scroller must not become a vertical one: `overflow-x: auto`
    // alone computes `overflow-y` to `auto`, which latches the wheel and stops
    // the conversation under the reader. The transcript owns vertical scroll.
    overflowY: "hidden",
    borderRadius: radius.control,
    boxShadow: CODE_RING,
  },
  table: {
    width: "max-content",
    minWidth: "100%",
    borderCollapse: "collapse",
    fontSize: type.fontBase,
  },
  cell: {
    paddingBlock: 4,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    textAlign: "left",
    verticalAlign: "top",
  },
  headerCell: { backgroundColor: role.bgMutedTranslucent, fontWeight: 600 },
  fallbackPre: {
    width: "100%",
    marginBlockStart: { default: 8, ":first-child": 0 },
    marginBlockEnd: { default: 8, ":last-child": 0 },
    marginInline: 0,
    paddingBlock: 6,
    paddingInline: 10,
    overflowX: "auto",
    overflowY: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    borderRadius: radius.card,
    backgroundColor: role.bgBase,
    color: role.contentPrimary,
    fontFamily: type.fontMono,
    fontSize: type.fontCode,
    lineHeight: type.leadingBase,
    whiteSpace: "pre",
  },
  imageLabel: { color: role.contentSecondary },
});

export const codeBlockStyles = create({
  figure: {
    position: "relative",
    marginBlockStart: { default: 8, ":first-child": 0 },
    marginBlockEnd: { default: 8, ":last-child": 0 },
    marginInline: 0,
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    borderRadius: radius.card,
    backgroundColor: role.bgBase,
    "--_code-copy-opacity": {
      default: 0,
      ":hover": 1,
      ":focus-within": 1,
      ":has([data-copied])": 1,
    },
  },
  scroll: { maxWidth: "100%", overflowX: "auto", overflowY: "hidden" },
  pre: {
    margin: 0,
    paddingBlock: 6,
    paddingInline: 10,
    color: role.contentPrimary,
    fontFamily: type.fontMono,
    fontSize: type.fontCode,
    fontWeight: 400,
    lineHeight: type.leadingCode,
    whiteSpace: "pre",
    userSelect: "text",
  },
  copy: {
    position: "absolute",
    insetBlockStart: 4,
    insetInlineEnd: 4,
    zIndex: 1,
    display: "flex",
    opacity: "var(--_code-copy-opacity)",
    transitionProperty: "opacity",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
});

const COMPOSER_PILL_HALF_HEIGHT = 20;

const PILLS_ROW_OFFSET = 8;

/** The prompt's own padding; a message edit keeps its text and images where the bubble had them. */
const USER_PROMPT_PADDING_BLOCK = 8;

const USER_PROMPT_PADDING_INLINE = 10;

const USER_IMAGES_GAP = 8;

export const composerStyles = create({
  portalSlot: { display: "contents" },
  dockFloating: { "::before": { content: "none" } },
  regionFloating: { paddingInline: 0, paddingBottom: 0 },
  frameFloating: { boxShadow: shadow.shadowLg },
  floatingStatus: {
    display: "inline-flex",
    alignItems: "center",
    gap: button.gapSm,
    maxWidth: "100%",
    height: button.heightSm,
    paddingInline: button.pillPaddingInlineSm,
    borderRadius: radius.pill,
    backgroundColor: role.bgElevated,
    boxShadow: `inset 0 0 0 1px ${role.borderPrimary}, ${shadow.shadowSm}`,
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    pointerEvents: "auto",
  },
  floatingStatusText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dock: {
    position: "sticky",
    bottom: 0,
    zIndex: layer.stickyContent,
    flexShrink: 0,
    width: "100%",
    pointerEvents: "none",
    "::before": {
      content: "''",
      position: "absolute",
      insetInline: 0,
      insetBlockStart: `calc(-1 * ${conversation.edgeFade})`,
      bottom: 0,
      zIndex: -1,
      backgroundColor: role.bgBase,
      maskImage: `linear-gradient(to bottom, transparent, black calc(${conversation.edgeFade} + ${COMPOSER_PILL_HALF_HEIGHT}px))`,
      pointerEvents: "none",
    },
  },
  region: {
    display: "flex",
    flexDirection: "column",
    gap: tray.gap,
    width: `min(${conversation.measure}, 100%)`,
    marginInline: "auto",
    paddingInline: conversation.gutter,
    paddingBottom: conversation.composerInset,
  },
  inputStack: { position: "relative", minWidth: 0, pointerEvents: "auto" },
  preComposerOverlay: {
    position: "absolute",
    insetInline: 0,
    bottom: `calc(100% + ${PILLS_ROW_OFFSET}px)`,
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    pointerEvents: "none",
  },
  preComposerStack: {
    display: "flex",
    flexDirection: "column",
    gap: tray.gap,
    pointerEvents: "auto",
  },
  preComposerPills: {
    display: "flex",
    flexDirection: { default: "row", ":has([data-slot='tray'])": "column" },
    flexWrap: "wrap",
    alignItems: { default: "center", ":has([data-slot='tray'])": "stretch" },
    columnGap: 4,
    rowGap: tray.gap,
    width: { default: "fit-content", ":has([data-slot='tray'])": "100%" },
    maxWidth: "100%",
    minHeight: {
      default: 0,
      ":has([data-scroll-shown='true'])": button.heightSm,
    },
    marginTop: {
      default: 0,
      ":has(> :not(:empty):not([data-slot='scroll-to-bottom']), [data-scroll-shown='true'])":
        tray.gap,
    },
    paddingBottom: {
      default: 0,
      ":has([data-slot='tray']):has([data-scroll-shown='true'])": `calc(${button.heightSm} + ${tray.gap})`,
    },
    pointerEvents: "auto",
  },
  queueList: { maxHeight: 200 },
  queueRow: {
    "--_queue-actions-display": {
      default: "none",
      ":hover": "flex",
      ":focus-within": "flex",
      "[data-editing='true']": "flex",
      "[data-error='true']": "flex",
      "@media (hover: none), (pointer: coarse)": "flex",
    },
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    minWidth: 0,
    minHeight: tray.rowHeight,
    paddingBlock: 0,
    paddingInlineStart: tray.rowInset,
    paddingInlineEnd: 4,
    borderRadius: radius.control,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": role.bgHover },
      ":focus-within": role.bgHover,
      "[data-editing='true']": role.bgInteractiveSecondaryTranslucent,
    },
    boxShadow: {
      default: "none",
      "[data-editing='true']": `inset 0 0 0 1px ${role.borderPrimaryTranslucent}`,
    },
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    transitionProperty: "background-color",
    transitionDuration: {
      default: "100ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease-in-out",
  },
  queueMessage: { flex: 1, minWidth: 0 },
  queuePreview: {
    display: "-webkit-box",
    paddingBlock: 4,
    overflow: "hidden",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  queueActions: {
    display: "var(--_queue-actions-display)",
    alignItems: "center",
    flexShrink: 0,
    gap: 8,
    marginInlineStart: "auto",
  },
  queued: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: button.heightMd,
    paddingInline: 10,
    borderRadius: radius.control,
    backgroundColor: role.bgElevated,
    boxShadow: CODE_RING,
    color: role.contentSecondary,
    fontSize: type.fontSm,
  },
  queuedText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  queuedState: {
    display: "block",
    paddingBlockEnd: 4,
    color: role.contentSecondary,
    fontSize: type.fontXs,
    lineHeight: type.leadingXs,
    overflowWrap: "anywhere",
  },
  queuedError: { color: role.contentSecondary },
  queueHint: {
    color: role.contentSecondary,
    fontSize: type.fontSm,
  },
  frame: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: role.borderSecondaryTranslucent,
      ":hover": { "@media (hover: hover) and (pointer: fine)": role.borderPrimaryTranslucent },
      ":focus-within": role.borderPrimaryTranslucent,
    },
    backgroundColor: role.bgElevated,
    boxShadow: "none",
    transitionProperty: "border-color",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
  frameNewChat: {
    gap: 6,
    minHeight: 106,
    padding: "10px 12px 8px",
    borderRadius: conversation.composerNewChatRadius,
  },
  frameFollowUpCompact: {
    gap: 6,
    minHeight: COMPOSER_COMPACT_HEIGHT,
    padding: "4px 8px 4px 10px",
    borderRadius: radius.pill,
  },
  frameFollowUpExpanded: { borderRadius: conversation.composerExpandedRadius },
  frameMessageEdit: { borderRadius: radius.card },
  frameDragging: {
    borderColor: role.borderPrimaryTranslucent,
    boxShadow: COMPOSER_RING_DROP,
  },
  dropGuard: {
    position: "absolute",
    zIndex: 10,
    inset: 0,
    borderRadius: "inherit",
  },
  fileInput: { display: "none" },
  attachments: {
    display: "flex",
    gap: 8,
    width: "100%",
    margin: 0,
    padding: 0,
    listStyle: "none",
    paddingBlockStart: 6,
    overflowX: "auto",
    paddingInlineEnd: 4,
    scrollPaddingInline: 8,
  },
  attachmentsInset: { width: "auto", marginInline: 12 },
  attachmentsInsetCompact: { marginInline: 2 },
  attachmentsMessageEdit: {
    gap: USER_IMAGES_GAP,
    marginInline: USER_PROMPT_PADDING_INLINE,
    paddingBlockStart: USER_PROMPT_PADDING_BLOCK,
  },
  attachment: {
    position: "relative",
    display: "flex",
    flexShrink: 0,
    "--_attachment-remove-opacity": {
      default: 0,
      ":hover": 1,
      ":focus-within": 1,
      "@media (hover: none)": 1,
    },
  },
  attachmentRemove: {
    position: "absolute",
    insetBlockStart: 0,
    insetInlineEnd: 0,
    zIndex: 1,
    display: "flex",
    opacity: "var(--_attachment-remove-opacity)",
    transform: "translate(25%, -25%)",
    transitionProperty: "opacity",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
  attachmentError: {
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  attachmentErrorInset: { marginInline: 12 },
  attachmentErrorInsetCompact: { marginInline: 2 },
  input: {
    display: "block",
    boxSizing: "border-box",
    width: "100%",
    minWidth: 80,
    flex: 1,
    minHeight: type.leadingLg,
    maxHeight: 200,
    overflowY: "auto",
    overscrollBehavior: "contain",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    caretColor: { default: role.contentPrimary, "[data-custom-caret='true']": "transparent" },
    "[data-empty='true']::before": {
      content: "attr(data-placeholder)",
      position: "absolute",
      color: role.contentTertiary,
      pointerEvents: "none",
    },
    margin: 0,
    padding: 0,
    resize: "none",
    borderStyle: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: role.contentPrimary,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    "::placeholder": { color: role.contentTertiary },
  },
  editorHost: { position: "relative", flex: 1, minWidth: 64 },
  editorParagraph: { margin: 0 },
  composerUrlPill: {
    color: role.contentSecondary,
    backgroundColor: role.bgMutedTranslucent,
    borderRadius: radius.control,
    paddingInline: 4,
    paddingBlock: 0,
    textDecorationLine: "none",
  },
  readOnly: {
    outlineStyle: "none",
    minWidth: 0,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  editorCaret: {
    position: "absolute",
    insetBlockStart: 0,
    insetInlineStart: 0,
    width: 1.5,
    borderRadius: 1,
    backgroundColor: role.contentPrimary,
    color: "transparent",
    userSelect: "none",
    pointerEvents: "none",
    animationName: { default: caretBlink, "@media (prefers-reduced-motion: reduce)": "none" },
    animationDuration: "1.1s",
    animationTimingFunction: "step-end",
    animationIterationCount: "infinite",
  },
  inputNewChat: { minHeight: 54, maxHeight: 340 },
  inputCompact: {
    minHeight: type.leadingLg,
    minWidth: 0,
    overflowX: "auto",
    overflowY: "hidden",
    overflowWrap: "normal",
    whiteSpace: "nowrap",
    wordBreak: "normal",
    "[data-empty='true']::before": {
      width: "100%",
      overflow: "hidden",
      textOverflow: "clip",
      whiteSpace: "nowrap",
    },
  },
  editor: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    columnGap: 4,
    width: "100%",
    minWidth: 0,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    letterSpacing: type.letterLg,
  },
  editorCompact: {
    gridColumn: 2,
    gridRow: 1,
    minWidth: 64,
    overflow: "hidden",
    flexWrap: "nowrap",
  },
  editorExpanded: { minHeight: 54, paddingBlock: 8, paddingInline: 12 },
  editorMessageEdit: {
    minHeight: type.leadingLg,
    paddingBlock: USER_PROMPT_PADDING_BLOCK,
    paddingInline: USER_PROMPT_PADDING_INLINE,
  },
  // Clips a multi-line draft to the compact row; `inputCompact`'s nowrap does not stop hard line breaks.
  editorCollapsed: { maxHeight: type.leadingLg },
  mentionChip: {
    position: "relative",
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "baseline",
    verticalAlign: "baseline",
    gap: 2,
    color: role.contentSecondary,
    fontSize: "inherit",
    fontWeight: 400,
    lineHeight: "inherit",
    whiteSpace: "nowrap",
  },
  mentionChipLabel: {
    display: "inline-flex",
    alignItems: "baseline",
    WebkitMaskImage: "var(--_chip-label-mask)",
    maskImage: "var(--_chip-label-mask)",
  },
  mentionChipLeading: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    flexShrink: 0,
    width: "1em",
    height: "1em",
    marginInlineEnd: 4,
  },
  /** Like a workbench tab: the remove button appears over the faded end of the label. */
  mentionChipRemovable: {
    "--_chip-remove-opacity": {
      default: "0",
      ":hover": "1",
      ":has(:focus-visible)": "1",
      "@media (hover: none)": "1",
    },
    "--_chip-remove-pointer-events": {
      default: "none",
      ":hover": "auto",
      ":has(:focus-visible)": "auto",
      "@media (hover: none)": "auto",
    },
    "--_chip-label-mask": {
      default: "none",
      ":hover": CHIP_LABEL_FADE,
      ":has(:focus-visible)": CHIP_LABEL_FADE,
      "@media (hover: none)": CHIP_LABEL_FADE,
    },
  },
  mentionChipRemove: {
    position: "absolute",
    insetBlock: 0,
    insetInlineEnd: 0,
    zIndex: 1,
    display: "flex",
    alignItems: "center",
    opacity: "var(--_chip-remove-opacity)",
    pointerEvents: "var(--_chip-remove-pointer-events)",
    transitionProperty: "opacity",
    transitionDuration: motion.durationFast,
    transitionTimingFunction: motion.easeOut,
  },
  /** A pasted snippet, scrolling past its bounds. */
  clipboardPreview: {
    display: "block",
    maxWidth: clipboardPreview.maxWidth,
    maxHeight: clipboardPreview.maxHeight,
    overflowY: "auto",
    overflowWrap: "anywhere",
    color: role.contentSecondary,
    fontFamily: type.fontMono,
    fontSize: type.fontXs,
    lineHeight: type.leadingXs,
    whiteSpace: "pre-wrap",
  },
  layout: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  layoutNewChat: { gap: 6 },
  layoutCompact: {
    display: "grid",
    gridTemplateColumns: `${button.heightMd} minmax(64px, 1fr) minmax(0, auto) auto`,
    alignItems: "center",
    gap: 8,
  },
  controls: {
    display: "flex",
    alignItems: "center",
    gap: target.gap,
    minHeight: button.heightMd,
  },
  controlsInset: { paddingInline: 8, paddingBlockEnd: 8 },
  controlsCompact: { display: "contents" },
  addButtonCompact: { gridColumn: 1, gridRow: 1 },
  /** Composer actions keep the frame's pill corners. */
  pillButton: { borderRadius: radius.pill },
  addMenu: { width: 260, maxWidth: "calc(100vw - 24px)" },
  modelSlot: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  modelSlotCompact: {
    gridColumn: 3,
    gridRow: 1,
    minWidth: 0,
    maxWidth: 220,
  },
  spacer: { flex: 1 },
  spacerCompact: { display: "none" },
  suggestionPositioner: {
    borderRadius: radius.card,
    boxShadow: "none",
  },
  suggestionMenu: {
    display: "flex",
    flexDirection: "column",
    width: "var(--anchor-width)",
    maxHeight: "min(280px, var(--available-height))",
    padding: 0,
    boxShadow: shadow.shadowSm,
    // The frame clips and carries the inset hairline; the list inside scrolls.
    // An absolutely positioned hairline on a scroll container would travel
    // with the content.
    overflow: "hidden",
    opacity: 1,
    scale: 1,
  },
  suggestionList: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarWidth: "none",
    "::-webkit-scrollbar": { display: "none" },
  },
  suggestionItem: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "12px minmax(0, 1fr) auto",
    boxSizing: "border-box",
    alignItems: "center",
    columnGap: menu.itemGap,
    minHeight: menu.itemHeight,
    paddingBlock: 4,
    paddingInline: 12,
    borderStyle: "none",
    outline: "none",
    backgroundColor: {
      default: "transparent",
      "[aria-selected='true']": role.bgHover,
    },
    color: {
      default: role.contentSecondary,
      ":hover": role.contentPrimary,
      "[aria-selected='true']": role.contentPrimary,
    },
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    letterSpacing: type.letterBase,
    cursor: appearance.cursorInteractive,
    userSelect: "none",
  },
  suggestionIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 12,
  },
  suggestionText: {
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    gap: 8,
    overflow: "hidden",
  },
  suggestionLabel: {
    minWidth: 0,
    flexShrink: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionDescription: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionMatch: { color: role.contentSecondary, fontWeight: "inherit" },
  suggestionShortcut: {
    minWidth: 0,
    paddingInlineStart: 8,
    overflow: "hidden",
    color: role.contentSecondary,
    fontSize: type.fontXs,
    lineHeight: type.leadingXs,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  suggestionGroupStart: {
    marginBlockStart: pane.dividerGap,
    // A section divider sits in the gap, independent of the row highlight.
    "::before": {
      content: '""',
      position: "absolute",
      insetInline: 0,
      top: -3,
      height: 1,
      backgroundColor: role.borderSecondaryTranslucent,
      pointerEvents: "none",
    },
  },
  suggestionEmpty: {
    minHeight: COMPOSER_COMPACT_HEIGHT,
    display: "flex",
    alignItems: "center",
    paddingInline: 12,
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
  },
  suggestionPreview: {
    display: "flex",
    flexDirection: "column",
    width: 280,
    maxWidth: "min(280px, var(--available-width))",
    maxHeight: "min(300px, var(--available-height))",
    padding: 10,
    borderRadius: radius.card,
    overflowY: "auto",
    opacity: 1,
    scale: 1,
  },
  suggestionPreviewTitle: {
    color: role.contentPrimary,
    fontSize: type.fontBase,
    fontWeight: 500,
    lineHeight: type.leadingBase,
  },
  suggestionPreviewAttribution: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginBlockStart: 6,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  suggestionPreviewIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: glyph.sm,
    height: glyph.sm,
    color: role.contentTertiary,
  },
  suggestionPreviewDescription: {
    marginBlockStart: 8,
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  // One row per folder on the way to the mention, each stepped in from the one
  // above it, so the path reads as the walk down to what was mentioned.
  suggestionPreviewPath: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    marginBlockStart: 8,
  },
  suggestionPreviewPathRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  // The same box Pierre's file-type glyph occupies, so folder and file rows
  // hang their labels on one line.
  suggestionPreviewPathIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: glyph.md,
    height: glyph.md,
    color: role.contentTertiary,
  },
  suggestionPreviewPathIndent: (depth: number) => ({ paddingInlineStart: depth * 12 }),
  suggestionPreviewPathLeaf: { color: role.contentPrimary },
  suggestionPreviewPathLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sendActions: { display: "flex", alignItems: "center", gap: 8 },
  sendCompact: { gridColumn: 4, gridRow: 1 },
});

export const diffStyles = create({
  surface: {
    boxSizing: "border-box",
    minWidth: 0,
    overflow: "hidden",
    borderRadius: radius.control,
    backgroundColor: role.bgMutedTranslucent,
  },
  inline: {
    marginTop: 4,
    marginBottom: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    backgroundColor: role.bgBase,
  },
  card: { borderRadius: 0, backgroundColor: role.bgBase },
  workbench: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100%",
    margin: 0,
    borderRadius: radius.control,
    boxShadow: CODE_RING,
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    margin: 0,
    borderRadius: 0,
    boxShadow: "none",
    backgroundColor: role.bgBase,
  },
  stackSection: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: role.borderSecondaryTranslucent,
    backgroundColor: role.bgBase,
  },
  stackHeader: {
    "--_stack-icon-display": {
      default: "flex",
      ":hover": "none",
      "[aria-expanded='false']": "none",
    },
    "--_stack-chevron-display": {
      default: "none",
      ":hover": "flex",
      "[aria-expanded='false']": "flex",
    },
    appearance: "none",
    position: "sticky",
    top: 0,
    zIndex: 5,
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    minHeight: row.heightLg,
    margin: 0,
    paddingLeft: 12,
    paddingRight: 8,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: role.borderSecondaryTranslucent,
    backgroundColor: role.bgBase,
    color: "inherit",
    font: "inherit",
    textAlign: "start",
    cursor: appearance.cursorInteractive,
    flexShrink: 0,
  },
  stackHeaderGlyph: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: glyph.md,
    height: glyph.md,
    flexShrink: 0,
  },
  stackHeaderIcon: { display: "var(--_stack-icon-display)" },
  stackHeaderChevron: { display: "var(--_stack-chevron-display)" },
  stackPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    color: role.contentSecondary,
    fontFamily: type.fontSans,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    whiteSpace: "nowrap",
  },
  stackStats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: type.fontBase,
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: row.heightMd,
    paddingInline: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: role.borderSecondaryTranslucent,
    flexShrink: 0,
  },
  path: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    color: role.contentSecondary,
    fontFamily: type.fontMono,
    fontSize: type.fontCode,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: type.fontCode,
  },
  added: { color: role.contentSecondary },
  removed: { color: role.contentSecondary },
  body: { minWidth: 0, overflow: "auto" },
  bodyInline: { maxHeight: diffView.previewMaxHeight },
  bodyWorkbench: { flex: 1, minHeight: 0, maxHeight: "none" },
  bodyStack: { overflow: "visible", maxHeight: "none" },
  // Pierre's :host remaps these through *-override / light-dark tokens.
  patch: {
    display: "block",
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    "--diffs-light-bg": "transparent",
    "--diffs-dark-bg": "transparent",
    "--diffs-light": role.contentPrimary,
    "--diffs-dark": role.contentPrimary,
    "--diffs-bg-buffer-override": role.bgBase,
    "--diffs-bg-context-override": role.bgBase,
    "--diffs-bg-context-gutter-override": role.bgBase,
    "--diffs-bg-separator-override": role.bgMutedTranslucent,
    "--diffs-fg-number-override": role.contentTertiary,
    "--diffs-bg-selection-override": role.bgInteractiveSecondaryTranslucent,
    "--diffs-gap-style": "none",
    // Pierre pads the code grid top and bottom. The section header already
    // spaces the patch, and the stack's height arithmetic counts rows alone.
    "--diffs-gap-block": "0px",
    "--diffs-min-number-column-width": "calc(4ch + 8px)",
    "--diffs-font-family": type.fontMono,
    "--diffs-header-font-family": type.fontSans,
    "--diffs-font-size": type.fontCode,
    "--diffs-line-height": diffView.lineHeight,
    "--diffs-tab-size": 4,
  },
});

export const activityStyles = create({
  shimmer: {
    animationName: {
      default: activityShine,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: {
      default: "2.4s",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    backgroundImage: {
      default: ACTIVITY_SHIMMER,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundSize: "200% 100%",
    backgroundClip: "text",
    color: {
      default: "transparent",
      "@media (prefers-reduced-motion: reduce)": role.contentSecondary,
    },
  },
});

/** A stopped call stays legible but recedes: between the secondary and tertiary content roles. */
const DIMMED = `color-mix(in oklab, ${role.contentSecondary} 55%, ${role.contentTertiary})`;

export const toolCallStyles = create({
  root: { display: "flex", flexDirection: "column", minWidth: 0 },
  line: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: button.heightSm,
    paddingInline: 0,
    overflow: "hidden",
    borderStyle: "none",
    backgroundColor: "transparent",
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    textAlign: "left",
    whiteSpace: "nowrap",
    cursor: appearance.cursorInteractive,
    userSelect: "none",
    "--_verb-color": {
      default: role.contentSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": role.contentPrimary },
    },
    "--_detail-color": {
      default: role.contentSecondary,
      ":hover": { "@media (hover: hover) and (pointer: fine)": role.contentPrimary },
    },
  },
  editLine: { minHeight: button.heightMd },
  lineStatic: {
    cursor: "default",
    "--_verb-color": role.contentSecondary,
    "--_detail-color": role.contentSecondary,
  },
  lineDimmed: { "--_verb-color": DIMMED, "--_detail-color": DIMMED },
  lineDetailed: {
    width: "100%",
    minHeight: button.heightLg,
    paddingInline: 8,
    borderRadius: radius.control,
    backgroundColor: role.bgMutedTranslucent,
    boxShadow: CODE_RING,
  },
  verb: {
    flexShrink: 0,
    color: "var(--_verb-color)",
    transitionProperty: "color",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
  detail: {
    minWidth: 0,
    overflow: "hidden",
    color: "var(--_detail-color)",
    fontFamily: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    transitionProperty: "color",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: "inherit",
    lineHeight: "inherit",
  },
  editStats: { marginInlineStart: 4 },
  added: { color: role.contentSecondary },
  removed: { color: role.contentSecondary },
  chevron: {
    width: glyph.md,
    height: glyph.md,
    transitionTimingFunction: "ease-in-out",
  },
  /**
   * The body keeps the newest lines at the bottom (column-reverse): closed it is
   * five lines tall and fades at the top when clipped; open it scrolls, so
   * opening grows the tail upward and a running command stays in view.
   */
  output: {
    position: "relative",
    marginTop: 6,
    marginBottom: 4,
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    borderRadius: radius.control,
    backgroundColor: role.bgBase,
  },
  outputActions: {
    position: "absolute",
    insetBlockStart: 4,
    insetInlineEnd: 4,
    zIndex: 1,
  },
  outputBody: {
    appearance: "none",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column-reverse",
    width: "100%",
    margin: 0,
    paddingBlock: 6,
    paddingInline: 10,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: role.contentSecondary,
    fontFamily: type.fontMono,
    fontSize: type.fontCode,
    lineHeight: type.leadingCode,
    textAlign: "start",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  outputTail: {
    maxHeight: `calc(5 * ${type.leadingBase} + 12px)`,
    overflow: "hidden",
    cursor: appearance.cursorInteractive,
    maskImage: {
      default: null,
      "[data-overflow]": "linear-gradient(to bottom, transparent 0px, black 16px)",
    },
  },
  outputScroll: {
    maxHeight: diffView.previewMaxHeight,
    overflowY: "auto",
    userSelect: "text",
    paddingInlineEnd: `calc(${button.heightSm} + 8px)`,
  },
  outputContent: { display: "block", minWidth: 0 },
});

export const subagentCallStyles = create({
  root: { display: "flex", flexDirection: "column", minWidth: 0 },
  row: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    minWidth: 0,
    paddingBlock: 0,
    paddingInline: 0,
    minHeight: button.heightSm,
    textAlign: "left",
  },
  header: { paddingBlock: 6 },
  nested: { display: "flex", flexDirection: "column", marginTop: 10 },
  nestedRow: { paddingBlock: 2, paddingInlineStart: 12 },
  // One text line tall, so a moon and a 6px dot both centre on the title.
  indicator: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: glyph.lg,
    height: type.leadingLg,
    paddingLeft: 2,
  },
  dot: { width: 6, height: 6, borderRadius: radius.pill },
  attention: { backgroundColor: role.contentInteractiveTertiary },
  failed: { backgroundColor: role.bgInteractiveStrong },
  done: { backgroundColor: role.contentTertiary },
  text: {
    display: "flex",
    flex: "1 1 0",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
  },
  titleRow: { display: "flex", alignItems: "center", gap: 6, minWidth: 0 },
  title: {
    minWidth: 0,
    overflow: "hidden",
    color: role.contentPrimary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  model: {
    flexShrink: 2,
    minWidth: 0,
    overflow: "hidden",
    color: role.contentSecondary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  status: { display: "flex", minWidth: 0, color: role.contentSecondary },
  statusAttention: { color: role.contentSecondary },
});

export const stepGroupStyles = create({
  root: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    contain: "layout",
    "--_group-chevron-opacity": { default: 0, ":hover": 1, ":focus-within": 1 },
  },
  status: {
    display: "inline-flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    width: "fit-content",
    maxWidth: "100%",
    minHeight: conversation.rowMinHeight,
    color: role.contentSecondary,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
  },
  toggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    maxWidth: "100%",
    minHeight: button.heightSm,
    minWidth: 0,
    textAlign: "start",
    color: role.contentSecondary,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    userSelect: "none",
    "--_group-chevron-color": {
      default: role.contentTertiary,
      ":hover": role.contentSecondary,
      "[data-panel-open]": role.contentSecondary,
    },
    "--_group-chevron-opacity": { default: null, "[data-panel-open]": 1 },
  },
  chevron: {
    marginInlineStart: 2,
    color: "var(--_group-chevron-color, currentcolor)",
    opacity: "var(--_group-chevron-opacity, 1)",
    transitionProperty: "transform, color, opacity",
    transitionDuration: {
      default: `${motion.durationNormal}, ${motion.durationFast}, ${motion.durationFast}`,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
  },
  verb: { flexShrink: 0 },
  summary: {
    minWidth: 0,
    overflow: "hidden",
    color: role.contentSecondary,
    fontSize: "inherit",
    lineHeight: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stats: {
    display: "inline-flex",
    gap: 6,
    flexShrink: 0,
    fontSize: "inherit",
    lineHeight: "inherit",
  },
  added: { color: role.contentSecondary },
  removed: { color: role.contentSecondary },
  calls: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    paddingBlockStart: 6,
  },
  earlier: { alignSelf: "flex-start" },
  panel: { position: "relative" },
  preview: {
    boxSizing: "border-box",
    maxHeight: 144,
    overflowX: "hidden",
    overflowY: "auto",
    cursor: appearance.cursorInteractive,
    overscrollBehavior: "auto",
    maskImage: {
      default: null,
      "[data-overflow]": "linear-gradient(to bottom, rgba(0, 0, 0, 0.15) 0px, black 32px)",
    },
  },
  thinking: {
    minWidth: 0,
    color: role.contentSecondary,
    opacity: 0.5,
    "--_prose-strong-color": "currentcolor",
  },
});

export const USER_MESSAGE_PREVIEW_LINES = 3.5;

/** Room for a chip's background above the first line, which the clip would cut. */
const USER_PREVIEW_BLEED_TOP = 2;

/**
 * The collapsed-message fade spans the clipped fractional line
 * plus the whole line above it, and runs out through the prompt's bottom
 * padding. The half line is gone before the clip, so nothing reads as sliced
 * text against the prompt's edge.
 */
const USER_PREVIEW_FADE = `calc(${type.leadingLg} * ${(USER_MESSAGE_PREVIEW_LINES % 1) + 1} + ${USER_PROMPT_PADDING_BLOCK}px)`;

/**
 * The transcript's scroll frame. The viewport's rows dissolve at the top edge
 * and run on under the composer. A stuck prompt
 * covers that edge with its own opaque inset and turns the mask off: masking
 * the viewport would make the strip translucent again and let rows surface
 * above the prompt. Rows resize under the virtualizer's own corrections, so
 * the browser's anchoring stays out.
 */
export const messageScrollerStyles = create({
  viewport: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowAnchor: "none",
    outlineStyle: "none",
    maskImage: {
      default: null,
      "[data-top-fade='true']": `linear-gradient(to bottom, transparent, black ${conversation.edgeFade})`,
    },
  },
  // The container's height is the virtualizer's total; items sit inside it at
  // their measured offsets. Top and bottom padding live in the virtualizer
  // (`paddingStart`/`paddingEnd`), the turn gap on each item.
  content: {
    position: "relative",
    flexGrow: 1,
    flexShrink: 0,
    width: `min(${conversation.measure}, 100%)`,
    marginInline: "auto",
  },
  // `top` rather than a transform: the prompt inside is `position: sticky`,
  // and a transformed ancestor would pin it to the item instead of the
  // viewport. An item that renders nothing drops its gap like a missing flex
  // item would.
  item: {
    position: "absolute",
    insetInline: 0,
    paddingInline: conversation.gutter,
    paddingTop: { default: conversation.turnGap, ":empty": 0 },
    contain: "layout",
  },
  itemFirst: { paddingTop: 0 },
  button: {
    position: "absolute",
    insetBlockEnd: 0,
    insetInlineStart: "50%",
    translate: "-50% 0",
    transitionProperty: "opacity, visibility",
  },
  buttonShown: {
    opacity: 1,
    visibility: "visible",
    pointerEvents: "auto",
    transitionDuration: {
      default: motion.durationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
  buttonHidden: {
    opacity: 0,
    visibility: "hidden",
    pointerEvents: "none",
    transitionDuration: {
      default: "120ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "ease-in",
  },
  buttonControl: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: role.borderSecondaryTranslucent,
      ":hover": role.borderPrimaryTranslucent,
    },
    backgroundColor: role.bgElevated,
    backgroundImage: {
      default: "none",
      ":hover": "none",
      ":active": "none",
    },
    boxShadow: "none",
    transitionProperty: "border-color",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
});

/** The user prompt's side of a turn, spanning the measure behind its bubble. */
export const messageStyles = create({
  end: {
    position: "relative",
    width: "100%",
    minWidth: 0,
    borderRadius: radius.card,
    backgroundColor: role.conversationUserShellBg,
  },
});

export const bubbleStyles = create({
  default: {
    boxSizing: "border-box",
    display: "block",
    width: "100%",
    minWidth: 0,
    paddingBlock: USER_PROMPT_PADDING_BLOCK,
    paddingInline: USER_PROMPT_PADDING_INLINE,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: role.borderSecondaryTranslucent,
      ":has(:focus-visible)": role.borderPrimaryTranslucent,
      ':hover:has([data-slot="row-primary"])': {
        "@media (hover: hover) and (pointer: fine)": role.borderPrimaryTranslucent,
      },
    },
    borderRadius: radius.card,
    backgroundColor: role.bgElevated,
    boxShadow: "var(--_user-prompt-shadow, none)",
    color: role.contentPrimary,
    fontFamily: "inherit",
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    letterSpacing: type.letterLg,
    textAlign: "start",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    userSelect: "text",
    cursor: { default: null, ':has([data-slot="row-primary"])': appearance.cursorInteractive },
    outlineStyle: "none",
    transitionProperty: "border-color, box-shadow",
    transitionDuration: {
      default: motion.durationFast,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: motion.easeOut,
  },
});

export const markerStyles = create({
  default: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: conversation.rowMinHeight,
    paddingBlock: 2,
    color: role.contentSecondary,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    overflowWrap: "anywhere",
    userSelect: "text",
  },
  destructive: {
    color: role.contentSecondary,
  },
  retrying: {
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    minHeight: conversation.rowMinHeight,
    paddingBlock: 2,
    gap: 8,
    color: role.contentSecondary,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
  },
  shimmer: {
    minWidth: 0,
    backgroundImage: {
      default: ACTIVITY_SHIMMER,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundSize: "200% 100%",
    backgroundClip: {
      default: "text",
      "@media (prefers-reduced-motion: reduce)": "border-box",
    },
    WebkitBackgroundClip: {
      default: "text",
      "@media (prefers-reduced-motion: reduce)": "border-box",
    },
    WebkitTextFillColor: {
      default: "transparent",
      "@media (prefers-reduced-motion: reduce)": "unset",
    },
    animationName: {
      default: textShimmer,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
});

export const turnStyles = create({
  turn: {
    display: "flex",
    flexDirection: "column",
    gap: conversation.rowGap,
    width: "100%",
    minWidth: 0,
    // The sticky prompt sticks against the outer scrollport, not its turn;
    // layout containment leaves that alone (no overflow clip, no scroller).
    contain: "layout",
  },
  // The row's inset is the transcript's top edge while the prompt is stuck:
  // it paints the pane colour, so rows scrolling past vanish behind it instead
  // of surfacing above the prompt. The scrollport drops its own fade then,
  // which would otherwise make this strip translucent.
  userRow: {
    position: { default: "sticky", "[data-sticky-disabled='true']": "relative" },
    zIndex: { default: layer.stickyContent, "[data-sticky-disabled='true']": "auto" },
    top: 0,
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    paddingTop: 10,
    marginBottom: 4,
    backgroundColor: { default: null, "[data-sticky-active='true']": role.bgBase },
    "--_user-prompt-shadow": {
      default: "none",
      "[data-sticky-active='true']": shadow.shadowSm,
    },
  },
  userPreview: { display: "block", minWidth: 0 },
  userPreviewCollapsed: {
    overflow: "hidden",
    maxHeight: `calc(${type.leadingLg} * ${USER_MESSAGE_PREVIEW_LINES})`,
  },
  // The preview bleeds into the prompt's padding so the fade has somewhere to
  // finish; negative margins give the bleed back, leaving the row's height and
  // the toggle's place unchanged.
  userPreviewFade: {
    maxHeight: `calc(${type.leadingLg} * ${USER_MESSAGE_PREVIEW_LINES} + ${USER_PREVIEW_BLEED_TOP + USER_PROMPT_PADDING_BLOCK}px)`,
    paddingTop: USER_PREVIEW_BLEED_TOP,
    marginTop: -USER_PREVIEW_BLEED_TOP,
    paddingBottom: USER_PROMPT_PADDING_BLOCK,
    marginBottom: -USER_PROMPT_PADDING_BLOCK,
    maskImage: `linear-gradient(to bottom, #000 calc(100% - ${USER_PREVIEW_FADE}), transparent 100%)`,
  },
  userPreviewToggle: { marginBlockStart: 4 },
  userImages: {
    display: "flex",
    flexWrap: "wrap",
    gap: USER_IMAGES_GAP,
    paddingBlockEnd: USER_IMAGES_GAP,
  },
  changesCard: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 2,
    width: "100%",
    paddingBlock: 8,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    borderRadius: radius.card,
    backgroundColor: role.bgElevated,
    color: role.contentPrimary,
  },
  changesHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  changesTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
  },
  changesReview: { marginBlock: -2 },
  changesList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  changesFile: {
    minHeight: row.heightMd,
    paddingInline: row.paddingInlineMd,
    backgroundImage: { default: "none", ":active": role.layerPressed },
    color: role.contentSecondary,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
  },
  changesFileIcon: { width: glyph.md, transform: "translateY(1px)" },
  changesStats: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  },
  changesAdded: { color: role.contentSecondary },
  changesRemoved: { color: role.contentSecondary },
  // The edit is the composer frame itself; this only stacks an error line above it.
  userEdit: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    minWidth: 0,
  },
  userEditError: {
    minWidth: 0,
    paddingInlineStart: 4,
    overflow: "hidden",
    color: role.contentSecondary,
    fontSize: type.fontXs,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  disclosureToggle: {
    width: "fit-content",
    minHeight: conversation.rowMinHeight,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
  },
  history: { display: "flex", flexDirection: "column", minWidth: 0 },
  historyBody: {
    boxSizing: "border-box",
    width: "100%",
    marginTop: 4,
    paddingBlock: 2,
    paddingInlineStart: 12,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: role.borderPrimaryTranslucent,
    color: role.contentSecondary,
  },
});
