import { create } from "@stylexjs/stylex";
import { conversation, layer, pane } from "../theme/schema.stylex.ts";
import { t } from "../theme/vars.stylex.ts";

export const threadStyles = create({
  stage: {
    display: "flex",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  panes: {
    position: "relative",
    display: "flex",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  splitRight: { flexDirection: "row" },
  splitDown: { flexDirection: "column" },
  pane: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    backgroundColor: t.bgBase,
  },
  paneSingle: { flex: 1 },
  paneLeading: (ratio: number) => ({
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: `${String(ratio * 100)}%`,
  }),
  paneTrailing: { flex: 1 },
  screen: { display: "flex", flexDirection: "column", flex: 1, minHeight: 0 },
  embeddedScreen: {
    width: "100%",
    minWidth: 0,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: conversation.headerHeight,
    paddingInline: 12,
    flexShrink: 0,
  },
  title: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: t.fontBase,
    fontWeight: 600,
    color: t.textPrimary,
  },
  headerActions: { display: "inline-flex", alignItems: "center", gap: 2, flexShrink: 0 },
  renameInput: {
    flex: 1,
    minWidth: 0,
    height: 24,
    paddingInline: 6,
    borderRadius: t.radiusSm,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: t.strokeSecondary, ":focus-visible": t.strokeFocused },
    backgroundColor: t.bgElevated,
    color: t.textPrimary,
    fontSize: t.fontBase,
    fontWeight: 600,
    outline: "none",
  },
  body: { position: "relative", display: "flex", flex: 1, minHeight: 0, minWidth: 0 },
  conversation: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0, minHeight: 0 },
  // Rows dissolve at the top edge the way they do at the composer, over the
  // same distance. A stuck prompt covers that edge with its own opaque inset
  // and turns the mask off: masking the scrollport would make the strip
  // translucent again and let rows surface above the prompt.
  //
  // Rows resize under the virtualizer's own corrections, so the browser's
  // anchoring stays out.
  scroll: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowAnchor: "none",
    maskImage: {
      default: null,
      "[data-top-fade='true']": `linear-gradient(to bottom, transparent, black ${conversation.edgeFade})`,
    },
  },
  // The container's height is the virtualizer's total; rows sit inside it at
  // their measured offsets. Top and bottom padding live in the virtualizer
  // (`paddingStart`/`paddingEnd`), the turn gap on each row.
  transcript: {
    position: "relative",
    flexGrow: 1,
    flexShrink: 0,
    width: `min(${conversation.measure}, 100%)`,
    marginInline: "auto",
  },
  // `top` rather than a transform: the prompt inside is `position: sticky`,
  // and a transformed ancestor would pin it to the row instead of the
  // scrollport. A row that renders nothing drops its gap like a missing flex
  // item would.
  row: {
    position: "absolute",
    insetInline: 0,
    paddingInline: conversation.gutter,
    paddingTop: { default: conversation.turnGap, ":empty": 0 },
    contain: "layout",
  },
  rowFirst: { paddingTop: 0 },
  banner: {
    width: "fit-content",
    padding: "4px 10px",
    borderRadius: t.radiusLg,
    backgroundColor: t.fillWarningSubtle,
    color: t.textWarning,
    fontSize: t.fontSm,
  },
  bannerAction: {
    padding: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "inherit",
    fontSize: "inherit",
    textDecorationLine: "underline",
    cursor: "pointer",
  },
  blank: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    minHeight: 0,
  },
  blankColumn: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "min(608px, calc(100% - 40px))",
  },
  greeting: { paddingInlineStart: 4, color: t.textTertiary, fontSize: t.fontLg },
  workspaceContext: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    paddingInline: 4,
    color: t.textSecondary,
    fontSize: t.fontBase,
  },
  workspaceContextItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  workspaceContextButton: {
    height: 26,
    paddingInline: 4,
    borderStyle: "none",
    borderRadius: t.radiusBase,
    backgroundColor: {
      default: "transparent",
      ":hover": { "@media (hover: hover) and (pointer: fine)": t.fillGhostHover },
      "[data-popup-open]": t.fillGhostSelected,
    },
    color: "inherit",
    cursor: "pointer",
  },
  workspaceContextPath: { maxWidth: 280 },
  workspaceContextStatic: { height: 26, paddingInline: 4 },
  workspaceContextText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  blankHint: { paddingInlineStart: 4, color: t.textTertiary, fontSize: t.fontBase },
  blankActions: { display: "flex", gap: 8, paddingInlineStart: 4 },
  error: { paddingInlineStart: 4, color: t.textDanger, fontSize: t.fontBase },
  sash: {
    position: "relative",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    zIndex: 4,
    touchAction: "none",
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 2,
    outlineColor: t.focusRing,
    outlineOffset: -2,
  },
  sashRight: { width: pane.sashSize, cursor: "col-resize" },
  sashDown: { height: pane.sashSize, cursor: "row-resize" },
  sashLine: { backgroundColor: t.strokeTertiary, pointerEvents: "none" },
  sashLineRight: { width: 1, height: "100%" },
  sashLineDown: { width: "100%", height: 1 },
  dropPreviewLayer: {
    position: "absolute",
    inset: 2,
    zIndex: layer.dragPreview,
    overflow: "hidden",
    pointerEvents: "none",
  },
  dropPreview: {
    position: "absolute",
    borderRadius: t.radiusSm,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: t.fillAccent,
    backgroundColor: `color-mix(in srgb, ${t.fillAccent} 8%, transparent)`,
    pointerEvents: "none",
  },
});
