/** Customize inventory feature styles. */
import * as stylex from "@stylexjs/stylex";
import { t } from "@nyte-ai/ui/vars.stylex";

export const customizeStyles = stylex.create({
  surface: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    backgroundColor: t.bgBase,
  },
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: 720,
    minHeight: "100%",
    marginInline: "auto",
    padding: "16px 24px 40px",
    gap: 12,
  },
  searchRow: { display: "flex", alignItems: "center", gap: 8 },
  searchField: {
    width: "100%",
    height: 32,
    gap: 6,
    paddingInline: 10,
    borderRadius: t.radius8,
    borderColor: t.borderSecondaryTranslucent,
    outlineStyle: { default: "none", ":focus-within": "solid" },
    outlineWidth: 1,
    outlineColor: t.focusRing,
    outlineOffset: -1,
  },
  searchInput: { height: "100%" },
  inventory: { display: "flex", flexDirection: "column", gap: 8, minWidth: 0 },
  inventoryHeading: { display: "flex", alignItems: "baseline", gap: 6, paddingInline: 6 },
  inventoryTitle: {
    margin: 0,
    color: t.contentPrimary,
    fontSize: t.fontBase,
    fontWeight: 600,
    lineHeight: t.leadingBase,
  },
  inventoryCount: { color: t.contentSecondary, fontSize: t.fontSm, lineHeight: t.leadingSm },
  settingsNote: {
    paddingInline: 6,
    color: t.contentSecondary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    padding: 1,
    overflow: "hidden",
    borderRadius: t.radius12,
    backgroundColor: t.borderSecondaryTranslucent,
  },
  row: {
    "--nyte-row-height": "48px",
    "--nyte-row-gap": "10px",
    "--nyte-row-padding-inline": "10px",
    "--nyte-row-leading-size": "16px",
    // The list paints its hairlines as 1px gaps in its own background, so every
    // row needs an opaque resting fill and square corners to cover them.
    "--_row-fill": t.bgBase,
    paddingBlock: 6,
    borderRadius: 0,
  },
  rowTitle: { fontWeight: 500 },
  badge: {
    flexShrink: 0,
    padding: "2px 6px",
    borderRadius: t.radiusFull,
    backgroundColor: t.bgMutedTranslucent,
    color: t.contentSecondary,
    fontSize: t.fontXs,
    lineHeight: t.leadingXs,
  },
  failedBadge: { backgroundColor: t.intentDangerBg, color: t.intentDangerContent },
  quiet: {
    minHeight: 48,
    display: "flex",
    alignItems: "center",
    paddingInline: 10,
    backgroundColor: t.bgBase,
    color: t.contentSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  loadingLine: {
    width: "42%",
    height: 8,
    borderRadius: t.radiusFull,
    backgroundColor: t.bgMutedTranslucent,
  },
  error: { color: t.intentDangerContent, fontSize: t.fontSm, lineHeight: t.leadingSm },
});
