/** Settings › Models geometry beyond the shared settings patterns. */
import * as stylex from "@stylexjs/stylex";
import { t } from "@nyte-ai/ui/vars.stylex";

export const modelsSettingsStyles = stylex.create({
  search: { height: "auto", minHeight: 28, paddingBlock: 6 },
  groupHeading: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: 8,
    minHeight: 44,
    paddingInline: 6,
    paddingBlock: 4,
  },
  groupTrigger: {
    borderRadius: t.radiusBase,
  },
  groupLabel: {
    display: "flex",
    alignItems: "center",
    flex: "1 1 auto",
    minWidth: 0,
    minHeight: 36,
    gap: 8,
    padding: 6,
    color: t.iconSecondary,
  },
  groupPanel: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: t.strokeSecondary,
  },
  groupTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: t.textPrimary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    letterSpacing: t.letterBase,
  },
  groupMeta: {
    flex: 1,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
  },
  groupActions: { display: "inline-flex", gap: 2, marginInlineStart: "auto" },
  modelRow: {
    "::after": {
      position: "absolute",
      insetInline: 12,
      insetBlockEnd: 0,
      height: 1,
      backgroundColor: t.strokeSecondary,
      content: '""',
    },
    ":last-child::after": { display: "none" },
  },
  quiet: {
    display: "flex",
    alignItems: "center",
    minHeight: 44,
    paddingInline: 12,
    borderRadius: t.radiusXl,
    backgroundColor: t.fillQuiet,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
  },
  keyForm: { display: "flex", flexDirection: "column", gap: 6 },
  keyRow: { display: "flex", alignItems: "center", gap: 6 },
  keyInput: {
    flex: 1,
    height: 26,
    backgroundColor: t.bgPage,
    fontFamily: t.fontMono,
    "::placeholder": { fontFamily: t.fontSans },
  },
  keyHint: { color: t.textTertiary, fontSize: t.fontSm, lineHeight: t.leadingSm },
  deviceCodePanel: { display: "flex", flexDirection: "column", gap: 8 },
  deviceCodeLead: {
    color: t.textSecondary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    overflowWrap: "anywhere",
  },
  deviceCodeRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 6 },
  // The code is the one thing to read here: mono, wide-tracked, and selected
  // whole so a click cannot grab half of it.
  deviceCode: {
    boxSizing: "border-box",
    minHeight: 32,
    paddingInline: 10,
    paddingBlock: 4,
    borderRadius: t.radiusBase,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    backgroundColor: t.bgPage,
    color: t.textPrimary,
    fontFamily: t.fontMono,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: "0.12em",
    userSelect: "all",
    whiteSpace: "nowrap",
  },
  deviceCodeNote: {
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    overflowWrap: "anywhere",
  },
  alert: { color: t.textDanger, fontSize: t.fontSm, lineHeight: t.leadingSm },
});
