import { shape } from "@nyte-ai/ui/schema.stylex";
/** Settings › Models geometry beyond the shared settings patterns. */
import { create } from "@stylexjs/stylex";
import { role, type } from "@nyte-ai/ui/vars.stylex";
import { settings } from "../theme/schema.stylex.ts";

export const modelsSettingsStyles = create({
  providers: { display: "flex", flexDirection: "column", gap: settings.sectionGap },
  providerList: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
  },
  providerTitle: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    paddingBlock: 2,
    whiteSpace: "normal",
  },
  providerBadge: {
    display: "inline-flex",
    alignItems: "center",
    paddingInline: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    borderRadius: shape.indicator,
    backgroundColor: role.bgMutedTranslucent,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    fontWeight: 400,
    lineHeight: type.leadingSm,
  },
  search: { height: "auto", minHeight: 28, paddingBlock: 6 },
  groupHeading: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: 8,
    minHeight: 44,
    paddingInline: 6,
    paddingBlock: 4,
  },
  groupTrigger: {
    borderRadius: shape.control,
  },
  groupLabel: {
    display: "flex",
    alignItems: "center",
    flex: "1 1 auto",
    minWidth: 0,
    minHeight: 36,
    gap: 8,
    padding: 6,
    color: role.contentSecondary,
  },
  groupPanel: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: role.borderSecondaryTranslucent,
  },
  groupTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: role.contentPrimary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    letterSpacing: type.letterBase,
  },
  groupMeta: {
    flex: 1,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  groupActions: { display: "inline-flex", gap: 8, flexWrap: "wrap", marginInlineStart: "auto" },
  quiet: {
    display: "flex",
    alignItems: "center",
    minHeight: 44,
    paddingInline: 12,
    borderRadius: shape.card,
    backgroundColor: role.bgMutedTranslucent,
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
  },
  keyForm: { display: "flex", flexDirection: "column", gap: 6 },
  keyRow: { display: "flex", alignItems: "center", gap: 8 },
  keyInput: {
    flex: 1,
    height: 26,
    backgroundColor: role.bgBase,
    fontFamily: type.fontMono,
    "::placeholder": { fontFamily: type.fontSans },
  },
  keyHint: { color: role.contentSecondary, fontSize: type.fontSm, lineHeight: type.leadingSm },
  deviceCodePanel: { display: "flex", flexDirection: "column", gap: 8 },
  deviceCodeLead: {
    color: role.contentSecondary,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    overflowWrap: "anywhere",
  },
  deviceCodeRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 8 },
  // The code is the one thing to read here: mono, wide-tracked, and selected
  // whole so a click cannot grab half of it.
  deviceCode: {
    boxSizing: "border-box",
    minHeight: 32,
    paddingInline: 10,
    paddingBlock: 4,
    borderRadius: shape.control,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: role.borderSecondaryTranslucent,
    backgroundColor: role.bgBase,
    color: role.contentPrimary,
    fontFamily: type.fontMono,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    letterSpacing: "0.12em",
    userSelect: "all",
    whiteSpace: "nowrap",
  },
  deviceCodeNote: {
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
    overflowWrap: "anywhere",
  },
  alert: { color: role.contentSecondary, fontSize: type.fontSm, lineHeight: type.leadingSm },
});
