import * as stylex from "@stylexjs/stylex";
import { t } from "@nyte-ai/ui/vars.stylex";

export const searchPaletteStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    flex: 1,
  },
  searchRow: {
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 10,
    minHeight: 56,
    paddingInline: 20,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.strokeSecondary,
    color: t.iconSecondary,
  },
  input: { height: 40 },
  tabs: {
    paddingInline: 8,
    paddingBlock: 6,
    overflowX: "auto",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.strokeSecondary,
  },
  results: {
    minHeight: 0,
    maxHeight: "min(320px, calc(100vh - 220px))",
    flexGrow: 1,
    flexShrink: 1,
    padding: 8,
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  groupLabel: {
    paddingInline: 12,
    paddingBlockStart: 12,
    paddingBlockEnd: 6,
    color: t.textTertiary,
    fontSize: t.fontSm,
    lineHeight: t.leadingSm,
    userSelect: "none",
  },
  result: {
    boxSizing: "border-box",
    gridTemplateColumns: "16px minmax(0, 1fr) auto",
    minHeight: 40,
    alignItems: "center",
    paddingBlock: 8,
    paddingInline: 12,
    columnGap: 10,
    borderRadius: t.radiusXl,
    backgroundColor: {
      default: "transparent",
      ":is([data-highlighted])": t.fillHover,
    },
    color: t.textPrimary,
    fontSize: t.fontLg,
    lineHeight: t.leadingLg,
    letterSpacing: t.letterLg,
  },
  resultIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 16,
    height: 16,
    color: t.iconSecondary,
  },
  empty: {
    display: "grid",
    placeItems: "center",
    minHeight: 152,
    padding: 24,
    color: t.textTertiary,
    fontSize: t.fontBase,
    lineHeight: t.leadingBase,
    textAlign: "center",
  },
});
