import { create } from "@stylexjs/stylex";
import { button, layer } from "@nyte-ai/ui/schema.stylex";
import { shell, sidebar, workbench } from "../theme/schema.stylex.ts";
import { role, type } from "@nyte-ai/ui/vars.stylex";

export const titlebarStyles = create({
  bar: {
    position: "relative",
    zIndex: layer.chrome,
    display: "flex",
    alignItems: "center",
    height: shell.titlebarHeight,
    minHeight: button.heightMd,
    paddingInlineEnd: 10,
    paddingInlineStart: 10,
    flexShrink: 0,
    WebkitAppRegion: "drag",
  },
  contentFill: {
    position: "absolute",
    insetBlock: 0,
    insetInlineStart: sidebar.width,
    insetInlineEnd: 0,
    backgroundColor: role.bgBase,
    pointerEvents: "none",
  },
  contentFillSidebarHidden: { insetInlineStart: 0 },
  workbenchTrack: {
    position: "absolute",
    zIndex: 3,
    insetBlock: 0,
    insetInlineEnd: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: workbench.activeWidth,
    minWidth: 0,
    paddingInlineStart: 6,
    paddingInlineEnd: 10,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: role.borderSecondaryTranslucent,
    boxShadow: `inset 0 -1px ${role.borderSecondaryTranslucent}`,
    backgroundColor: role.bgBase,
    WebkitAppRegion: "drag",
  },
  /** Window tabs: the strip sits on the chrome, over the workbench column of the inset card. */
  workbenchTrackTabbed: {
    insetInlineEnd: 8,
    borderInlineStartWidth: 0,
    boxShadow: "none",
    backgroundColor: "transparent",
  },
  workbenchTrackSidebarHiddenMac: {
    maxWidth: `calc(100% - ${shell.trafficLightInset} - ${button.heightMd} - 12px)`,
  },
  workbenchTrackSidebarHidden: { maxWidth: `calc(100% - ${button.heightMd} - 20px)` },
  workbenchReservation: {
    width: `calc(${workbench.activeWidth} - 10px)`,
    flexShrink: 0,
  },
  workbenchReservationTabbed: { width: `calc(${workbench.activeWidth} - 2px)` },
  tabSlot: { pointerEvents: "auto" },
  tabSlotWorkbenchOpen: { insetInlineEnd: `calc(${workbench.activeWidth} + 52px)` },
  titleSlotWorkbenchOpen: {
    insetInlineEnd: `calc(${workbench.activeWidth} + 44px)`,
  },
  // macOS reserves a traffic-light lane at the leading edge.
  barMac: { paddingInlineStart: shell.trafficLightInset },
  actionTrack: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: button.heightMd,
    height: button.heightMd,
    flexShrink: 0,
    position: "relative",
    zIndex: 1,
    WebkitAppRegion: "no-drag",
  },
  navigationTrack: {
    position: "absolute",
    zIndex: 2,
    insetInlineStart: `calc(${sidebar.width} - ${button.heightMd} * 2 - 16px)`,
    insetBlock: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    WebkitAppRegion: "drag",
  },
  navigationTrackMac: {
    insetInlineStart: `max(calc(${sidebar.width} - ${button.heightMd} * 2 - 16px), calc(${shell.trafficLightInset} + ${button.heightMd} + 8px))`,
  },
  titleSlotMac: {
    insetInlineStart: `max(calc(${sidebar.width} + 12px), calc(${shell.trafficLightInset} + ${button.heightMd} * 3 + 28px))`,
  },
  historyControl: {
    display: "inline-flex",
    flexDirection: "column",
    flexShrink: 0,
    width: button.heightMd,
    height: button.heightMd,
    overflow: "clip",
    overflowClipMargin: 2,
    WebkitAppRegion: "no-drag",
  },
  control: { display: "inline-flex", flexShrink: 0, WebkitAppRegion: "no-drag" },
  spacer: { flex: 1, minWidth: 0 },
  titleSlot: {
    position: "absolute",
    zIndex: 1,
    insetBlock: 0,
    insetInlineStart: `calc(${sidebar.width} + 12px)`,
    insetInlineEnd: 96,
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    pointerEvents: "none",
  },
  // 72px of traffic lights, the 28px toggle, then a 12px title gap on macOS;
  // elsewhere the toggle alone.
  titleSlotSidebarHiddenMac: {
    insetInlineStart: `calc(${shell.trafficLightInset} + ${button.heightMd} + 12px)`,
  },
  titleSlotSidebarHidden: { insetInlineStart: `calc(${button.heightMd} + 20px)` },
  sessionTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  sessionBack: {
    display: "inline-flex",
    flexShrink: 0,
    pointerEvents: "auto",
    WebkitAppRegion: "no-drag",
  },
  /** A step of the chat's location: the title's type, one tone quieter. */
  sessionCrumb: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
    whiteSpace: "nowrap",
  },
  sessionCrumbDivider: {
    flexShrink: 0,
    color: role.contentDisabled,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  sessionTitle: {
    maxWidth: "min(420px, 50vw)",
    overflow: "hidden",
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
