import { button, glyph, radius } from "@nyte-ai/ui/schema.stylex";
import { shell, sidebar } from "@nyte-ai/app/theme/schema.stylex.ts";
import { create } from "@stylexjs/stylex";
import { role, type } from "@nyte-ai/ui/vars.stylex";

export const boardStyles = create({
  page: {
    height: "100%",
    overflowY: "auto",
    backgroundColor: role.bgBase,
    color: role.contentPrimary,
    fontFamily: type.fontSans,
    fontSize: type.fontBase,
    lineHeight: type.leadingBase,
    WebkitFontSmoothing: "antialiased",
  },
  header: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    paddingInline: 32,
    paddingBlockStart: 20,
    paddingBlockEnd: 8,
  },
  title: { fontSize: type.fontLg, lineHeight: type.leadingLg, fontWeight: 500 },
  subtitle: { color: role.contentSecondary, flex: 1, minWidth: 240 },
  legend: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: 16,
    rowGap: 6,
    paddingInline: 32,
    paddingBlockEnd: 16,
    color: role.contentSecondary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  legendItem: { display: "inline-flex", alignItems: "center", gap: 6 },
  trail: { paddingBlock: 10, paddingInline: 12 },
  trailHere: { color: role.contentPrimary, fontWeight: 600 },
});

export const windowStyles = create({
  frame: {
    display: "flex",
    flexDirection: "column",
    marginInline: 32,
    marginBlockEnd: 40,
    borderRadius: radius.card,
    boxShadow: `inset 0 0 0 1px ${role.borderSecondaryTranslucent}`,
    overflow: "hidden",
  },
  /** The chrome runs behind everything; the main area is a card set into it, as in Linear. */
  window: {
    display: "flex",
    flexDirection: "column",
    height: 700,
    backgroundColor: role.sidebarMaterial,
  },
  titlebar: { display: "flex", alignItems: "center", height: shell.titlebarHeight, flexShrink: 0 },
  lane: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    height: "100%",
    paddingInline: 8,
    flexShrink: 0,
  },
  laneSidebar: { width: sidebar.width },
  lights: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingInlineStart: 6,
    paddingInlineEnd: 10,
  },
  light: {
    width: 12,
    height: 12,
    borderRadius: radius.pill,
    backgroundColor: role.bgInteractivePrimaryTranslucent,
  },
  laneFill: { flex: 1 },
  titlebarActions: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    paddingInline: 8,
    flexShrink: 0,
  },
  crumbTitle: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  body: { display: "flex", flex: 1, minHeight: 0 },
  sidebar: { display: "flex", width: sidebar.width, flexShrink: 0 },
  main: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    marginInlineEnd: 8,
    marginBlockEnd: 8,
    borderRadius: radius.card,
    backgroundColor: role.bgBase,
    boxShadow: `0 0 0 1px ${role.borderSecondaryTranslucent}`,
    overflow: "hidden",
  },
  mainSidebarHidden: { marginInlineStart: 8 },
  panes: { display: "flex", flex: 1, minHeight: 0 },
  panesDown: { flexDirection: "column" },
  pane: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0, minHeight: 0 },
  divider: { flexShrink: 0, backgroundColor: role.borderSecondaryTranslucent },
  dividerRight: { width: 1 },
  dividerDown: { height: 1 },
  paneHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    height: button.heightLg,
    paddingInlineStart: 12,
    paddingInlineEnd: 4,
    flexShrink: 0,
    color: role.contentTertiary,
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
  },
  paneHeaderActive: { color: role.contentPrimary },
  paneBody: { display: "flex", flexDirection: "column", flex: 1, minHeight: 0, overflow: "auto" },
});

export const stripStyles = create({
  strip: { display: "flex", alignItems: "center", gap: 4, flex: 1, minWidth: 0, height: "100%" },
  list: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    flex: "0 1 auto",
    minWidth: 0,
    height: "100%",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
  },
  listDragging: { cursor: "grabbing" },
  slot: {
    position: "relative",
    display: "flex",
    flex: "0 1 240px",
    minWidth: 72,
    transitionProperty: "transform",
    transitionDuration: "150ms",
    transitionTimingFunction: "ease-out",
  },
  slotPinned: { flex: "none", minWidth: 0 },
  /** The tab under the pointer follows it exactly; only its neighbours ease aside. */
  slotDragging: { zIndex: 1, transitionDuration: "0s" },
  tab: {
    "--_close-opacity": { default: "0", ":hover": "1", ":focus-within": "1" },
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
    height: button.heightMd,
    paddingInlineStart: 10,
    paddingInlineEnd: 4,
    borderRadius: button.radiusMd,
    backgroundColor: { default: "transparent", ":hover": role.bgHover },
    color: { default: role.contentSecondary, ":hover": role.contentPrimary },
    fontSize: type.fontSm,
    lineHeight: type.leadingSm,
    cursor: "default",
    userSelect: "none",
  },
  /** A pinned tab is its glyph alone, centred in a square. */
  tabPinned: { flex: "none", width: button.heightMd, paddingInline: 0, justifyContent: "center" },
  tabActive: {
    backgroundColor: {
      default: role.bgInteractiveSecondary,
      ":hover": role.bgInteractiveSecondary,
    },
    color: role.contentPrimary,
  },
  glyph: {
    display: { default: "grid", ":empty": "none" },
    placeItems: "center",
    width: glyph.box,
    height: glyph.box,
    flexShrink: 0,
  },
  label: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  splitMark: { display: "inline-flex", flexShrink: 0, color: role.contentTertiary },
  close: { display: "inline-flex", flexShrink: 0, opacity: "var(--_close-opacity)" },
  closeVisible: { opacity: 1 },
  fill: { flex: 1, alignSelf: "stretch" },
});

export const railStyles = create({
  rail: { width: "100%", height: "100%", backgroundColor: role.sidebarMaterial },
});

export const placeStyles = create({
  thread: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0, minHeight: 0 },
  transcript: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    flex: 1,
    width: "100%",
    maxWidth: 680,
    marginInline: "auto",
    paddingInline: 24,
    paddingBlock: 32,
    overflowY: "auto",
  },
  userTurn: { alignSelf: "flex-end", maxWidth: "80%" },
  reply: { color: role.contentPrimary, fontSize: type.fontLg, lineHeight: type.leadingLg },
  failed: { color: role.contentSecondary },
  step: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: role.contentSecondary,
    fontSize: type.fontBase,
  },
  reviewCard: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    paddingInline: 12,
    paddingBlock: 10,
    borderWidth: 0,
    borderRadius: radius.surface,
    backgroundColor: { default: role.bgElevated, ":hover": role.bgHover },
    boxShadow: `0 0 0 1px ${role.borderSecondaryTranslucent}`,
    color: role.contentPrimary,
    fontFamily: type.fontSans,
    fontSize: type.fontBase,
    textAlign: "start",
    cursor: "pointer",
  },
  reviewCardNumber: { color: role.contentSecondary, flexShrink: 0 },
  reviewCardTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  reviewCardHint: { color: role.contentTertiary, fontSize: type.fontSm, flexShrink: 0 },
  dock: {
    width: "100%",
    maxWidth: 680,
    marginInline: "auto",
    paddingInline: 24,
    paddingBlockEnd: 20,
  },
  composer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 52,
    paddingInlineStart: 14,
    paddingInlineEnd: 10,
    borderRadius: radius.surface,
    backgroundColor: role.bgElevated,
    boxShadow: `0 0 0 1px ${role.borderSecondaryTranslucent}`,
    color: role.contentTertiary,
  },
  send: {
    display: "grid",
    placeItems: "center",
    width: button.heightMd,
    height: button.heightMd,
    borderRadius: radius.pill,
    backgroundColor: role.bgInteractivePrimaryTranslucent,
    color: role.contentInteractiveSecondary,
  },
  newChat: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 16,
    flex: 1,
  },
  newChatTitle: {
    margin: 0,
    textAlign: "center",
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
    fontWeight: 500,
  },
  page: { flex: 1, minHeight: 0, overflowY: "auto" },
  pageColumn: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    maxWidth: 820,
    marginInline: "auto",
    paddingInline: 32,
    paddingBlock: 24,
  },
  pageTitle: { margin: 0, fontSize: 22, lineHeight: "28px", fontWeight: 600 },
  pageMeta: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
    color: role.contentSecondary,
    fontSize: type.fontSm,
  },
  branch: { fontFamily: type.fontMono, fontSize: type.fontSm, color: role.contentTertiary },
  paragraph: {
    margin: 0,
    color: role.contentPrimary,
    fontSize: type.fontLg,
    lineHeight: type.leadingLg,
  },
  fileList: { display: "flex", flexDirection: "column", gap: 2 },
  fileListRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingBlock: 6,
    color: role.contentSecondary,
    fontFamily: type.fontMono,
    fontSize: type.fontSm,
  },
  files: { display: "flex", flexDirection: "column", gap: 12 },
  file: {
    borderRadius: radius.surface,
    boxShadow: `0 0 0 1px ${role.borderSecondaryTranslucent}`,
    overflow: "hidden",
  },
  fileHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    paddingInline: 12,
    paddingBlock: 8,
    backgroundColor: role.bgMuted,
    color: role.contentSecondary,
    fontFamily: type.fontMono,
    fontSize: type.fontSm,
  },
  code: {
    margin: 0,
    paddingBlock: 6,
    fontFamily: type.fontMono,
    fontSize: type.fontSm,
    lineHeight: "20px",
    overflowX: "auto",
  },
  line: { paddingInline: 12, whiteSpace: "pre", color: role.contentSecondary },
  lineAdd: {
    backgroundColor: "light-dark(rgb(22 163 74 / 0.1), rgb(74 222 128 / 0.1))",
    color: role.contentPrimary,
  },
  lineRemove: {
    backgroundColor: "light-dark(rgb(220 38 38 / 0.1), rgb(248 113 113 / 0.1))",
    color: role.contentPrimary,
  },
});
