/**
 * The desktop shell, NDS-painted, following the real structure:
 *
 *   titlebar          35px, traffic lights in their reserved lane
 *   rail              primary actions, workspace, session list, account
 *   pane              its own 35px header with title and actions, then body
 *   conversation      transcript centred on the measure, composer docked
 *
 * `screens/thread.tsx` paints the pane on `t.bgBase`, which resolves to
 * `--nyte-bg-chrome` rather than the editor tone — the composer is the lighter
 * surface, not the pane. That relationship is kept here: pane on wash,
 * composer on elevated.
 */
import * as stylex from "@stylexjs/stylex";
import { g, t } from "./vars.stylex";

export const frame = stylex.create({
  window: {
    position: "relative",
    display: "grid",
    gridTemplateRows: `${g.titlebarHeight} minmax(0, 1fr)`,
    width: "100%",
    minWidth: 0,
    height: 600,
    overflow: "hidden",
    borderRadius: 10,
    backgroundColor: t.surfaceWash,
    boxShadow: "0 24px 60px -12px #00000055, 0 0 0 1px #00000022",
    color: t.textPrimary,
    /* Inter Variable is what makes 450/550/650 mean anything. */
    fontFamily: "var(--font-inter), Inter, system-ui, sans-serif",
    fontSize: g.body,
    lineHeight: g.bodyLeading,
    fontWeight: t.weightRegular,
    fontVariantNumeric: "tabular-nums",
    WebkitFontSmoothing: "antialiased",
    userSelect: "none",
  },
  titlebar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingInline: 12,
    backgroundColor: t.surfaceSunken,
  },
  lights: { display: "flex", gap: 8, width: g.trafficLightInset },
  light: { width: 12, height: 12, borderRadius: g.radiusFull },
  lightClose: { backgroundColor: "#ff5f57" },
  lightMin: { backgroundColor: "#febc2e" },
  lightMax: { backgroundColor: "#28c840" },
  body: {
    display: "grid",
    gridTemplateColumns: `${g.sidebarWidth} minmax(0, 1fr)`,
    minWidth: 0,
    minHeight: 0,
  },
});

export const rail = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    paddingInline: g.sidebarGutter,
    paddingBottom: 6,
    overflow: "hidden",
    backgroundColor: t.surfaceSunken,
  },
  group: { display: "flex", flexDirection: "column", gap: 1 },
  scroll: { flex: 1, minHeight: 0, overflow: "hidden", marginTop: 2 },
  heading: {
    display: "flex",
    alignItems: "center",
    height: 24,
    margin: "10px 0 2px",
    paddingInline: g.sidebarRowPaddingInline,
    color: t.textQuaternary,
    fontSize: g.bodyXs,
    lineHeight: g.bodyXsLeading,
    fontWeight: t.weightSemibold,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  headingAction: {
    position: "relative",
    marginLeft: "auto",
    display: "grid",
    placeItems: "center",
    width: g.sidebarActionSize,
    height: g.sidebarActionSize,
    borderStyle: "none",
    borderRadius: g.radius6,
    backgroundColor: { default: "transparent", ":hover": t.stateHover },
    color: t.iconTertiary,
    cursor: "default",
    /* A 24px control reaches a 40px target without changing what is drawn. */
    "::after": { content: '""', position: "absolute", insetBlock: -8, insetInline: -1 },
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: g.sidebarRowGap,
    width: "100%",
    height: g.sidebarRowHeight,
    paddingInline: g.sidebarRowPaddingInline,
    borderStyle: "none",
    borderRadius: g.radius8,
    backgroundColor: {
      default: "transparent",
      ":hover": t.stateHover,
      ":active": t.statePressed,
    },
    color: { default: t.textSecondary, ":hover": t.textPrimary },
    fontSize: g.body,
    fontWeight: t.weightRegular,
    textAlign: "left",
    cursor: "default",
    flexShrink: 0,
    transitionProperty: "background-color, color",
    transitionDuration: g.durationFast,
    transitionTimingFunction: t.easeDefault,
  },
  rowActive: {
    backgroundColor: { default: t.stateSelected, ":hover": t.stateSelectedHover },
    color: t.textPrimary,
    fontWeight: t.weightMedium,
  },
  glyph: {
    display: "grid",
    placeItems: "center",
    width: g.sidebarIconSlot,
    height: g.sidebarIconSlot,
    flexShrink: 0,
    color: t.iconSecondary,
    fontSize: g.bodySm,
  },
  dot: { width: 7, height: 7, borderRadius: g.radiusFull, backgroundColor: "currentColor" },
  dotRun: { color: t.success },
  dotFail: { color: t.danger },
  dotIdle: { color: t.iconQuaternary },
  label: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  meta: {
    minWidth: g.sidebarTrailingWidth,
    textAlign: "right",
    color: t.textQuaternary,
    fontSize: g.bodyXs,
  },
  shortcut: { color: t.textQuaternary, fontSize: g.bodyXs },
  account: {
    marginTop: "auto",
    paddingTop: 6,
  },
  avatar: {
    display: "grid",
    placeItems: "center",
    width: 18,
    height: 18,
    borderRadius: "42%",
    backgroundColor: t.infoWash,
    color: t.blue600,
    fontSize: "9px",
    fontWeight: t.weightSemibold,
  },
});

export const pane = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
    backgroundColor: t.surfaceWash,
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: g.headerHeight,
    paddingInline: 12,
    flexShrink: 0,
  },
  title: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: t.textPrimary,
    fontSize: g.body,
    fontWeight: t.weightSemibold,
  },
  actions: { display: "inline-flex", alignItems: "center", gap: 2, flexShrink: 0 },
  iconButton: {
    position: "relative",
    display: "grid",
    placeItems: "center",
    width: g.sidebarActionSize,
    height: g.sidebarActionSize,
    borderStyle: "none",
    borderRadius: g.radius6,
    backgroundColor: {
      default: "transparent",
      ":hover": t.stateHover,
      ":active": t.statePressed,
    },
    color: t.iconSecondary,
    cursor: "default",
    /* A 24px control reaches a 40px target without changing what is drawn. */
    "::after": { content: '""', position: "absolute", insetBlock: -8, insetInline: -1 },
  },
  body: { position: "relative", display: "flex", flex: 1, minHeight: 0, minWidth: 0 },
  conversation: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
});

export const thread = stylex.create({
  scroll: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehavior: "contain",
    paddingInline: g.conversationGutter,
    /* Rows dissolve at the top edge the way `screens/thread.tsx` fades them. */
    maskImage: "linear-gradient(to bottom, transparent, black 32px)",
    WebkitMaskImage: "linear-gradient(to bottom, transparent, black 32px)",
    scrollbarWidth: "thin",
    scrollbarColor: `${t.iconQuaternary} transparent`,
  },
  measure: {
    display: "flex",
    flexDirection: "column",
    gap: g.turnGap,
    width: "100%",
    maxWidth: g.conversationMeasure,
    marginInline: "auto",
    paddingBlock: g.conversationGutter,
  },
  userPrompt: {
    width: "100%",
    paddingBlock: 6,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    borderRadius: g.radius12,
    backgroundColor: t.surfaceElevated,
    boxShadow: t.shadowXs,
    fontSize: g.bodyLg,
    lineHeight: g.bodyLgLeading,
    letterSpacing: "-0.24px",
  },
  turn: {
    display: "flex",
    flexDirection: "column",
    gap: g.rowGap,
    fontSize: g.bodyLg,
    lineHeight: g.bodyLgLeading,
    letterSpacing: "-0.24px",
  },
  para: { margin: 0 },
  technical: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: 26,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    borderRadius: g.radius8,
    backgroundColor: t.surfaceElevated,
    color: t.textSecondary,
    fontSize: g.bodySm,
    fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
  },
  ok: { marginLeft: "auto", color: t.green600 },
  diff: {
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    borderRadius: g.radius8,
    backgroundColor: t.surfaceElevated,
    fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
    fontSize: g.bodySm,
    lineHeight: "20px",
  },
  diffHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: 26,
    paddingInline: 10,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: t.strokeSecondary,
    color: t.textTertiary,
    fontSize: g.bodyXs,
  },
  diffStat: { marginLeft: "auto", display: "flex", gap: 6 },
  statAdd: { color: t.green600 },
  statDel: { color: t.red600 },
  diffLine: { paddingInline: 10 },
  thinking: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: t.textTertiary,
    fontSize: g.bodySm,
    lineHeight: g.bodySmLeading,
  },
  changesCard: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    paddingBlock: 8,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: t.strokeSecondary,
    borderRadius: g.radius12,
    backgroundColor: t.surfaceElevated,
    fontSize: g.bodySm,
    lineHeight: g.bodySmLeading,
  },
  changesHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: t.textSecondary,
    fontWeight: t.weightMedium,
  },
  changesRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: t.textTertiary,
    fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
    fontSize: g.bodyXs,
  },
  changesName: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis" },
  working: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: t.textTertiary,
    fontSize: g.bodySm,
  },
  caret: {
    width: 7,
    height: 14,
    borderRadius: 1,
    backgroundColor: t.textTertiary,
  },
  diffAdd: { backgroundColor: t.successWash },
  diffDel: { backgroundColor: t.dangerWash },
});

export const composer = stylex.create({
  dock: { paddingInline: g.conversationGutter, paddingBottom: g.composerInset },
  frame: {
    width: "100%",
    maxWidth: g.conversationMeasure,
    marginInline: "auto",
    padding: "10px 12px 8px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: t.strokeSecondary, ":focus-within": t.strokePrimary },
    borderRadius: g.composerExpandedRadius,
    backgroundColor: t.surfaceElevated,
    boxShadow: t.shadowXs,
    color: t.textQuaternary,
    fontSize: g.bodyLg,
    lineHeight: g.bodyLgLeading,
    transitionProperty: "border-color",
    transitionDuration: g.durationFast,
    transitionTimingFunction: t.easeDefault,
  },
  footer: { display: "flex", alignItems: "center", gap: 6, marginTop: 10 },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    paddingBlock: 3,
    paddingInline: 8,
    borderRadius: g.radiusFull,
    backgroundColor: t.stateHover,
    color: t.textSecondary,
    fontSize: g.bodyXs,
    lineHeight: g.bodyXsLeading,
  },
  pill: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    height: 22,
    paddingInline: 8,
    borderStyle: "none",
    borderRadius: g.radiusFull,
    backgroundColor: {
      default: "transparent",
      ":hover": t.stateHover,
      ":active": t.statePressed,
    },
    color: t.textSecondary,
    fontSize: g.bodyXs,
    fontWeight: t.weightMedium,
    cursor: "default",
  },
  send: {
    position: "relative",
    display: "grid",
    placeItems: "center",
    width: 24,
    height: 24,
    marginLeft: "auto",
    borderStyle: "none",
    borderRadius: g.radiusFull,
    backgroundColor: t.surfaceContrast,
    color: t.textContrast,
    cursor: "default",
    /* A 24px control reaches a 40px target without changing what is drawn. */
    "::after": { content: '""', position: "absolute", insetBlock: -8, insetInline: -1 },
  },
});
