// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'pnpm models:generate' from the repository root

import values from "./data/openai-codex.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const OPENAI_CODEX_MODELS: ModelCatalog<typeof values, "openai-codex"> = flattenModelCatalog(
  "openai-codex",
  values,
);
